### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by bluesunsoftware** [javamelody/javamelody#1004]
I am getting a number format exception when hitting the /monitoring  URL on version 1.86.0

Java details: 
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-8u272-b10-0ubuntu1~16.04-b10)
OpenJDK 64-Bit Server VM (build 25.272-b10, mixed mode)

Tomcat : 8.5.4

OS: 
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

21-Feb-2021 21:01:09.045 SEVERE [http-nio-8080-exec-26] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [default] in context with path [] threw exception
 javax.management.RuntimeMBeanException: java.lang.NumberFormatException: For input string: "18446744073709551615"
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:839)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:852)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:651)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
        at net.bull.javamelody.internal.model.MBeansAccessor.getAttribute(MBeansAccessor.java:95)
        at net.bull.javamelody.internal.model.MBeansAccessor.getLongFromOperatingSystem(MBeansAccessor.java:104)
        at net.bull.javamelody.internal.model.MemoryInformations.<init>(MemoryInformations.java:77)
        at net.bull.javamelody.internal.model.JavaInformations.<init>(JavaInformations.java:157)
        at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:158)
        at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:408)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by evernat** [comment]
The OS via the JVM says that the total physical memory of your Ubuntu 16.04.7 LTS is a bit more than 18446744073 GB. That's 18446 TB or exactly twice the max value of a long integer. I do not think that this value is reasonable.
Perhaps it would be better to configure the memory of your OS?
What do you think?

**Comment by evernat** [comment]
any news?

**Comment by bluesunsoftware** [comment]
What do you mean by configure the memory of your OS ?

**Comment by evernat** [comment]
By configure the memory of the OS, I mean configure something in the OS in order that the [OperatingSystemMXBean#getTotalPhysicalMemorySize()](https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getTotalPhysicalMemorySize--) method in the JVM does not try to return 18446744073709551615 and in fact not more than 9223372036854775807.

For that, I suggest to look at `grep MemTotal /proc/meminfo` or `free -b` in a shell on Ubuntu. And I suppose that you will see 18446744073709551615 again.
Then I do not know exactly how to configure that in Ubuntu. But I know that 18000 TB of physical memory is not reasonable and not real. And I know that the [OperatingSystemMXBean#getTotalPhysicalMemorySize()](https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getTotalPhysicalMemorySize--) method does not work for a value of 18446744073709551615.

**Comment by evernat** [comment]
For example for Docker, you could check the value of `cat /sys/fs/cgroup/memory/memory.limit_in_bytes` in the container.

**Comment by bluesunsoftware** [comment]
grep MemTotal /proc/meminfo returns:
MemTotal:       16321320 kB

**Comment by evernat** [comment]
I do not know why in your case, the [OperatingSystemMXBean#getTotalPhysicalMemorySize()](https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getTotalPhysicalMemorySize--) method in the JVM does try to return 18446744073709551615 which is not reasonable and why it throws an excpetion when doing that.
You could ask the JDK developers if needed.
This is not considered as a bug in javamelody itself. It is not planned to fix it.
