### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org/postgresql/Driver

### ISSUE THREAD

**Issue by lelmarir** [javamelody/javamelody#1028]
I have the same problem of this issue: https://github.com/javamelody/javamelody/issues/749

**some times, seemingly at random (after several days), Hikari is no more able to acquire JDBC Connections,**

I'm using Javamelody 1.79.0
i've now updated to 1.87.0 to try if might be already resolved, 

do you have any idea?

```
org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
    at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48) ~[hibernate-core-5.4.14.Final.jar:5.4.14.Final]
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42) ~[hibernate-core-5.4.14.Final.jar:5.4.14.Final]
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.4.14.Final.jar:5.4.14.Final]
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core-5.4.14.Final.jar:5.4.14.Final]
    at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:107) ~[hibernate-core-5.4.14.Final.jar:5.4.14.Final]
    at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:134) ~[hibernate-core-5.4.14.Final.jar:5.4.14.Final]
    at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:250) ~[hibernate-core-5.4.14.Final.jar:5.4.14.Final]
    at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:258) ~[hibernate-core-5.4.14.Final.jar:5.4.14.Final]
    at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246) ~[hibernate-core-5.4.14.Final.jar:5.4.14.Final]
    at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-5.4.14.Final.jar:5.4.14.Final]
    at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66) ~[guice-persist-4.1.0.jar:?]
    at com.digibelt.ldp.tasks.MachineDowntimeTask.doWriteDowntime(MachineDowntimeTask.java:591) ~[classes/:2.6.2-postgres-SNAPSHOT]
    at com.digibelt.ldp.tasks.MachineDowntimeTask.doWriteDowntime(MachineDowntimeTask.java:584) ~[classes/:2.6.2-postgres-SNAPSHOT]
    at com.digibelt.ldp.tasks.MachineDowntimeTask.openDowntime(MachineDowntimeTask.java:537) ~[classes/:2.6.2-postgres-SNAPSHOT]
    at com.digibelt.ldp.tasks.MachineDowntimeTask.doHandleTagValue(MachineDowntimeTask.java:436) ~[classes/:2.6.2-postgres-SNAPSHOT]
    at com.digibelt.commons.ldp.shiro.RunAsSystemInterceptor.lambda$invoke$0(RunAsSystemInterceptor.java:25) ~[ldp-commons-1.11.10-postgres-SNAPSHOT.jar:?]
    at uk.q3c.krail.core.shiro.KrailSecurityManager.runAsSubject(KrailSecurityManager.java:274) ~[krail-2.0.10.jar:?]
    at uk.q3c.krail.core.shiro.KrailSecurityManager.runAsSystem(KrailSecurityManager.java:310) ~[krail-2.0.10.jar:?]
    at com.digibelt.commons.persistence.datamodel.services.impl.AbstractSecurityService.runAsSystem(AbstractSecurityService.java:184) ~[ldp-commons-1.11.10-postgres-SNAPSHOT.jar:?]
    at com.digibelt.commons.ldp.shiro.RunAsSystemInterceptor.invoke(RunAsSystemInterceptor.java:23) ~[ldp-commons-1.11.10-postgres-SNAPSHOT.jar:?]
    at com.google.inject.persist.jpa.UnitOfWorkInterceptor.invoke(UnitOfWorkInterceptor.java:26) ~[ldp-commons-1.11.10-postgres-SNAPSHOT.jar:?]
    at com.digibelt.ldp.tasks.MachineDowntimeTask.lambda$handleTagValue$7(MachineDowntimeTask.java:416) ~[classes/:2.6.2-postgres-SNAPSHOT]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 20000ms.
    at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-3.2.0.jar:?]
    at org.hibernate.hikaricp.internal.HikariCPConnectionProvider.getConnection(HikariCPConnectionProvider.java:77) ~[hibernate-hikaricp-5.4.14.Final.jar:5.4.14.Final]
    at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38) ~[hibernate-core-5.4.14.Final.jar:5.4.14.Final]
    at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:104) ~[hibernate-core-5.4.14.Final.jar:5.4.14.Final]
    ... 22 more
Caused by: java.sql.SQLException: org/postgresql/Driver
    at net.bull.javamelody.JdbcDriver.connect(JdbcDriver.java:99) ~[javamelody-core-1.86.0.jar:1.86.0]
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692) ~[HikariCP-3.2.0.jar:?]
    ... 4 more
Caused by: java.lang.ClassNotFoundException: org/postgresql/Driver
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
    at net.bull.javamelody.JdbcDriver.connect(JdbcDriver.java:96) ~[javamelody-core-1.86.0.jar:1.86.0]
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706) ~[HikariCP-3.2.0.jar:?]
    at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692) ~[HikariCP-3.2.0.jar:?]
    ... 4 more
```

**Comment by evernat** [comment]
Try to define the `driverClassName` hikari property perhaps.
Otherwise it seems to be related to classloaders in your application, but I don't know what classloaders you have for javamelody classes and for the postgres jdbc driver or if you use Tomcat for example.

**Comment by lelmarir** [comment]
I'm using Tomcat
