### ISSUE TITLE
error related to JavaMelody collecting data on all nodes.

### ISSUE THREAD

**Issue by supportservices24** [javamelody/javamelody#1041]
Hello,

We used JavaMelody on Confluence DataCenter  7.3.4 and we had an issue like Cluster panic.
Into their analyse Atlassian have notice that there is many errors into the logs about Java Melody collecting data.

Could you help us to understand what is the root cause of those error and to understand what are the impact and who to fixed them.

`2021-07-26 23:25:47,282 WARN [javamelody] [net.bull.javamelody] warn exception while collecting data: java.io.IOException: An unexpected network error occurred
 -- url: / | traceId: f79c53b785787600
java.io.IOException: An unexpected network error occurred
	at java.base/java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.base/java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:438)
	at java.base/java.io.File.getCanonicalPath(File.java:618)
	at org.jrobin.core.Util.getCanonicalPath(Util.java:707)
	at org.jrobin.core.RrdDbPool.requestRrdDb(RrdDbPool.java:86)
	at net.bull.javamelody.internal.model.JRobin.addValue(JRobin.java:378)
	at net.bull.javamelody.internal.model.Collector.addJRobinValue(Collector.java:644)
	at net.bull.javamelody.internal.model.Collector.collectJRobinValues(Collector.java:564)
	at net.bull.javamelody.internal.model.Collector.collectJavaInformations(Collector.java:422)
	at net.bull.javamelody.internal.model.Collector.collect(Collector.java:350)
	at net.bull.javamelody.internal.model.Collector.collectWithoutErrors(Collector.java:329)
	at net.bull.javamelody.internal.model.Collector.collectLocalContextWithoutErrors(Collector.java:318)
	at net.bull.javamelody.FilterContext$CollectTimerTask.run(FilterContext.java:82)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)`

Thanks.

Regards
Romain LORY

**Comment by evernat** [comment]
Hello,
First, I suppose that you are not writing to the same javamelody files from several instances of Confluence, because that would be a real problem. If you write to shared directories from several instances, check that the javamelody files (rrd and gz) from each instance are in different directories.

Then you are using the javamelody plugin in Confluence DataCenter, on Windows. (So javamelody is useful even in DataCenter eventually :wink:. In my case, I knew that for a long time.)

javamelody writes a few small files, every 60 secondes by default. I think that the errors from javamelody doing this reveals an issue, with network and/or disk access probably, and that javamelody is not the root cause. Of course, if there was a network and/or disk access issue, it may also be a big issue for Windows and Confluence, "like Cluster panic" as you said, whatever javamelody is trying to do. So I do not think that you should ask this question here.

If you search for "An unexpected network error occurred" or "ERROR_UNEXP_NET_ERR" for a Windows filesystem, you will find lots of pages. For me, it reminds me when trying, lot of years ago, to move big video files in a TV company between a browser on Windows and java servers on a saturated network: Windows was losing connection to its domain controller, even when moving files betwen simple Windows directories. My client understood this as "Windows ne sait plus où il habite". Anyway, I can't explain much about unexpected network errors in Windows without local tests, except that you may check your network and shared directories and monitor them like you do with Confluence.

For sure, the impact here is that sometimes or always, javamelody will not store metrics for graphs (rrd files) and statistics (gz files). So there will be holes in the data, nothing more than that.

As a workaround to your network issue, because it seems that you are using a shared directory on a network to store javamelody files, you may instead store the javamelody files on the local drive if you want javamelody monitoring even in case of network issues. Use the `storage-directory` javamelody parameter if you want to change to directory of javamelody files.
That will fix those javamelody errors, but probably not the "Cluster panic" when having those network issues.

Is it ok for you?

**Comment by supportservices24** [comment]
Hello,

Thanks for this answer.
I have check and JavaMelody files are well written on a network drive (smb), but each instance and application have their own Directories. And there is in JavaMelody folder a subdirectory for each node.
So in my understanding, I supposed that those errors related to JavaMelody have the same root cause as our main issue who made Confluence Outage. Are you agree with that?

Regards
