### ISSUE TITLE
Error 500 when I use Javamelody on Atlassian Bitbucket 7.21

### ISSUE THREAD

**Issue by VinceB833** [javamelody/javamelody#1103]
Hello guys,

I'm system admin in my company in charge of Atlassian products. I use to use JavaMelody as monitoring tool on all Atlassian apps and I like it. Unfortunately I'm facing an issue now on Bitbucket.

I recently upgraded our Atlassian Bitbucket to the latest version 7.21 and I wanted to use JavaMelody 1.91 like I did with the previous version. It does not work anymore and give an error 500. 
Logs gives the following error:

_"GET /monitoring HTTP/1.1" com.hazelcast.internal.util.XmlUtil Enabling XXE protection failed. The attribute http://javax.xml.XMLConstants/property/accessExternalDTD is not supported by the TransformerFactory. This usually mean an outdated XML processor is present on the classpath (e.g. Xerces, Xalan). If you are not able to resolve the issue by fixing the classpath, the hazelcast.ignoreXxeProtectionFailures system property can be used to disable XML External Entity protections. We don't recommend disabling the XXE as such the XML processor configuration is unsecure!!!_

and also

_2022-04-28 16:46:04,558 ERROR [https-jsse-nio-8443-exec-4] @CL3NBWx1006x242x1 1kjmzhn  "GET /mvc/error500 HTTP/1.1" c.a.s.i.web.ErrorPageController There was an unhandled exception loading [/monitoring]
javax.cache.CacheException: Error opening URI [hazelcast]
        at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:133)
        at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:162)
        at com.hazelcast.cache.HazelcastCachingProvider.getCacheManager(HazelcastCachingProvider.java:179)
        at net.bull.javamelody.internal.model.JCacheInformations.buildJCacheInformationsList(JCacheInformations.java:95)
        at net.bull.javamelody.internal.model.JavaInformations.<init>(JavaInformations.java:204)
        at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:158)
        at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:408)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206)
        at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:88)
        at net.bull.javamelody.JiraMonitoringFilter.doFilter(JiraMonitoringFilter.java:137)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:90)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73)
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:84)
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38)
        at java.lang.Thread.run(Thread.java:750)
        ... 62 frames trimmed
Caused by: java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
        at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:571)
        at com.hazelcast.internal.util.XmlUtil.setAttribute(XmlUtil.java:153)
        at com.hazelcast.internal.util.XmlUtil.getTransformerFactory(XmlUtil.java:66)
        at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:105)
        at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:164)
        at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:146)
        at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:139)
        at com.hazelcast.cache.impl.HazelcastServerCachingProvider.getDefaultConfig(HazelcastServerCachingProvider.java:159)
        at com.hazelcast.cache.impl.HazelcastServerCachingProvider.getDefaultInstance(HazelcastServerCachingProvider.java:129)
        at com.hazelcast.cache.impl.HazelcastServerCachingProvider.getOrCreateInstance(HazelcastServerCachingProvider.java:120)
        at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.createHazelcastCacheManager(AbstractHazelcastCachingProvider.java:246)
        at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:130)
        ... 16 common frames omitted
Not supported: http://javax.xml.XMLConstants/property/accessExternalDTDjavax.cache.CacheException: Error opening URI [hazelcast]_

Can you please help?

**Comment by astaf89** [comment]
Hello! We're facing the same issue after upgrade from 7.17.2 to 7.21.1.

**Comment by evernat** [comment]
This is caused by an upgrade of hazelcast in bitbucket and so including the fix for this hazelcast issue:
https://github.com/hazelcast/hazelcast/issues/20928
The problem is that Bitbucket has Xalan on the classpath as transformer factory as can be seen in your stack-trace:
```
Caused by: java.lang.IllegalArgumentException: Not supported: http://javax.xml.xmlconstants/property/accessExternalDTD
at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:571)
at com.hazelcast.internal.util.XmlUtil.setAttribute(XmlUtil.java:153)
```
and Xalan does not support this accessExternalDTD property.
If I remember well setting this accessExternalDTD property against xxe is not needed for Xalan because Xalan is not vulnerable to XXE.

When some xml properties are not supported like in this case, the code sometimes catches the exception to automatically ignore it. In XmlUtil of hazelcast, it is needed to set a system property `hazelcast.ignoreXxeProtectionFailures=true` at startup to log a warning instead of throwing an exception by default. I suggest to set this system property to acknowleged that Xalan present in Bitbucket 7.21 does not support this accessExternalDTD property and that it is not needed when Xalan is present.

@VinceB833 @astaf89 Is it ok for you with this system property `hazelcast.ignoreXxeProtectionFailures=true` ?

(Why Xalan is present in Bitbucket 7.21 is a question for someone else than javamelody.)

**Comment by astaf89** [comment]
I've tried to add `hazelcast.ignoreXxeProtectionFailures=true` to `bitbucket.properties` but the behavior was the same.

```
2022-07-11 21:54:12,825 ERROR [http-nio-7990-exec-2]  o.a.c.c.C.[.[.[/].[default] Servlet.service() for servlet [default] in context with path [] threw exception
javax.cache.CacheException: Error opening URI [hazelcast]
        at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:133)
        at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:162)
        at com.hazelcast.cache.HazelcastCachingProvider.getCacheManager(HazelcastCachingProvider.java:179)
        at net.bull.javamelody.internal.model.JCacheInformations.buildJCacheInformationsList(JCacheInformations.java:95)
        at net.bull.javamelody.internal.model.JavaInformations.<init>(JavaInformations.java:204)
        at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:158)
        at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:408)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206)
        at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:88)
        at net.bull.javamelody.JiraMonitoringFilter.doFilter(JiraMonitoringFilter.java:137)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:90)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73)
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:84)
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38)
        at java.lang.Thread.run(Thread.java:748)
        ... 62 frames trimmed
Caused by: java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
        at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:571)
        at com.hazelcast.internal.util.XmlUtil.setAttribute(XmlUtil.java:153)
        at com.hazelcast.internal.util.XmlUtil.getTransformerFactory(XmlUtil.java:66)
        at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:105)
        at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:164)
        at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:146)
        at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:139)
        at com.hazelcast.cache.impl.HazelcastServerCachingProvider.getDefaultConfig(HazelcastServerCachingProvider.java:159)
        at com.hazelcast.cache.impl.HazelcastServerCachingProvider.getDefaultInstance(HazelcastServerCachingProvider.java:129)
        at com.hazelcast.cache.impl.HazelcastServerCachingProvider.getOrCreateInstance(HazelcastServerCachingProvider.java:120)
        at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.createHazelcastCacheManager(AbstractHazelcastCachingProvider.java:246)
        at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:130)
        ... 16 common frames omitted


```

**Comment by evernat** [comment]
@astaf89 bitbucket.properties is not for system properties.
System property can be written with `-D` before each in the jvm command line for _start_webapp.sh/.bat : `-Dhazelcast.ignoreXxeProtectionFailures=true`.

You can put it in the JAVA_OPTS variable environment which is used in _start_webapp.sh/.bat for example :
`set JAVA_OPTS=-Dhazelcast.ignoreXxeProtectionFailures=true` for windows
or
`JAVA_OPTS=-Dhazelcast.ignoreXxeProtectionFailures=true` for linux

**Comment by hqp468** [comment]
Workaround works indeed, but documenations says:
_If enabled and when a problem occurs during enabling XML External Entity (XXE) protection, then the problem is ignored and only a warning message is logged.

This property should only be used as a last resort. Hazelcast uses the XXE protection by setting respective XML processor properties. These properties are supported in modern XML processors, e.g., the default one available in Java. An old processor on the classpath, such as Xerces and Xalan, may miss the support and throw an exception during enabling the XXE protection. Setting this system property to true allows ignoring such exceptions._
https://docs.hazelcast.com/imdg/4.2/system-properties

**Comment by evernat** [comment]
@hqp468 you can complain to Atlassian about the old processor Xalan being present and active in Bitbucket. With no release since 2014 and probably no security reviews, perhaps Xalan may be a potential security risk by itself in Bitbucket if we take a strict point of view.
Or you can complain to hazelcast about not taking Xalan as possible and about not saying what is safe with Xalan in XmlUtil (but as said, safety of Xalan without maintainer may be in question anyway).

**Comment by VinceB833** [comment]
Hi all and thanks for your help. 
Sorry for the late answer but I was in summer vacations. @evernat the workaround works fine.
However, I'm still a bit confused about security concerns with this change. Does it expose Bitbucket ?

**Comment by evernat** [comment]
I see that bitbucket 8.9.0 does not include xalan anymore like probably some previous versions of bitbucket.
Atlassian has finally agreed with my comment in this issue that the presence of xalan in bitbucket was a problem 😄  Or perhaps someone other told them 😄 😄 

So this issue is fixed by Atlassian, without needing the workaround in system properties given above.
