### ISSUE TITLE
Oracle UCP startup fail when use javamelody-spring-boot-starter

### ISSUE THREAD

**Issue by iMinusMinus** [javamelody/javamelody#1116]
major dependency like below:
org.springframework.boot:spring-boot-starter-parent:2.6.4
net.bull.javamelody:javamelody-spring-boot-starter:1.91.0
com.oracle.database.jdbc:ojdbc11:21.3.0.0
com.oracle.database.jdbc:ucp:21.3.0.0

important config like below:
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource

error like below:
Caused by: java.lang.IllegalArgumentException: methods with same signature createConnectionBuilder() but incompatible return types: [interface oracle.ucp.jdbc.UCPConnectionBuilder, interface java.sql.ConnectionBuilder]
	at java.base/java.lang.reflect.ProxyGenerator.checkReturnTypes(ProxyGenerator.java:311)
	at java.base/java.lang.reflect.ProxyGenerator.generateClassFile(ProxyGenerator.java:488)
	at java.base/java.lang.reflect.ProxyGenerator.generateProxyClass(ProxyGenerator.java:178)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.defineProxyClass(Proxy.java:558)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.build(Proxy.java:670)
	at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$1(Proxy.java:440)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
	at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:438)
	at java.base/java.lang.reflect.Proxy.getProxyClass(Proxy.java:398)
	at net.bull.javamelody.JdbcWrapperHelper.getProxyConstructor(JdbcWrapperHelper.java:584)
	at net.bull.javamelody.JdbcWrapperHelper.createProxy(JdbcWrapperHelper.java:566)
	at net.bull.javamelody.JdbcWrapper.createProxy(JdbcWrapper.java:898)
	at net.bull.javamelody.JdbcWrapper.createProxy(JdbcWrapper.java:886)
	at net.bull.javamelody.JdbcWrapper.createDataSourceProxy(JdbcWrapper.java:817)
	at net.bull.javamelody.SpringDataSourceBeanPostProcessor.postProcessAfterInitialization(SpringDataSourceBeanPostProcessor.java:102)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1808)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	... 67 common frames omitted

Process finished with exit code 1

**Comment by iMinusMinus** [comment]
it's my problem.
just downgrade jdk to 1.8 and use ojdbc8 will solve this problem.
