### ISSUE TITLE
Javamelody 1.86 JDK WLS 10.3.5 1.6.0_24 -> 1.6.0_26

### ISSUE THREAD

**Issue by titoparizotto** [javamelody/javamelody#1119]
Hello,

This issue is from a legacy application used WLS 10.3.5 1.6.0_24 and javamelody 1.86.
When upgrade the jrockit to the next patch 1.6.0_26 generate the stacktrace 

```txt
java.lang.UnsupportedOperationException: Thread allocated memory measurement is not supported.
javax.management.RuntimeMBeanException: java.lang.UnsupportedOperationException: Thread allocated memory measurement is not supported.
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:856)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:869)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:838)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:761)
	at weblogic.management.jmx.mbeanserver.WLSMBeanServerInterceptorBase$16.run(WLSMBeanServerInterceptorBase.java:449)
	at weblogic.management.jmx.mbeanserver.WLSMBeanServerInterceptorBase.invoke(WLSMBeanServerInterceptorBase.java:447)
	at weblogic.management.mbeanservers.internal.JMXContextInterceptor.invoke(JMXContextInterceptor.java:263)
	at weblogic.management.jmx.mbeanserver.WLSMBeanServerInterceptorBase$16.run(WLSMBeanServerInterceptorBase.java:449)
	at weblogic.management.jmx.mbeanserver.WLSMBeanServerInterceptorBase.invoke(WLSMBeanServerInterceptorBase.java:447)
	at weblogic.management.mbeanservers.internal.SecurityInterceptor.invoke(SecurityInterceptor.java:444)
	at weblogic.management.jmx.mbeanserver.WLSMBeanServer.invoke(WLSMBeanServer.java:323)
	at net.bull.javamelody.internal.model.MBeansAccessor.getThreadAllocatedBytes(MBeansAccessor.java:127)
	at net.bull.javamelody.internal.model.ThreadInformations.getThreadAllocatedBytes(ThreadInformations.java:102)
	at net.bull.javamelody.internal.model.ThreadInformations.getCurrentThreadAllocatedBytes(ThreadInformations.java:87)
	at net.bull.javamelody.internal.model.Counter.bindContextIncludingCpu(Counter.java:420)
	at net.bull.javamelody.JsfActionListener.processAction(JsfActionListener.java:65)
	at javax.faces.component.UICommand.broadcast(UICommand.java:315)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:794)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1259)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:300)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:27)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:105)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
		at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
	at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:27)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:61)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3729)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3695)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2285)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2184)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1459)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:209)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:178)
Caused by: java.lang.UnsupportedOperationException: Thread allocated memory measurement is not supported.
	at sun.management.ThreadImpl.verifyThreadAllocatedMemory(ThreadImpl.java:323)
	at sun.management.ThreadImpl.getThreadAllocatedBytes(ThreadImpl.java:331)
	at sun.management.ThreadImpl.getThreadAllocatedBytes(ThreadImpl.java:314)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:167)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:96)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:33)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:208)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:120)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:262)
	at javax.management.StandardMBean.invoke(StandardMBean.java:391)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:836)
```

This is the original WLS 10.3.5 jrockit 
```txt
jrockit_160_24_D1.1.2-4/bin/java.exe -version
java version "1.6.0_24"
Java(TM) SE Runtime Environment (build 1.6.0_24-b07)
Oracle JRockit(R) (build R28.1.3-11-141760-1.6.0_24-20110301-1429-windows-ia32, compiled mode)
```

This is the upgraded jrockit to jrockit-jdk1.6.0_26
```txtjrockit-jdk1.6.0_26/bin/java.exe -version
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Oracle JRockit(R) (build R28.1.4-7-144370-1.6.0_26-20110617-2130-windows-x86_64, compiled mode)
```

Extract for javamelody config 
```xml
<filter>
	<filter-name>javamelody</filter-name>
	<filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
	<init-param>
		<param-name>system-actions-enabled</param-name>
		<param-value>true</param-value>
	</init-param>
	<init-param>
		<param-name>javamelody.sampling-seconds</param-name>
		<param-value>1</param-value>
	</init-param>
	<init-param>
		<param-name>sampling-excluded-packages</param-name>
		<param-value>java,sun,com.sun,javax,org.apache,com.mysql</param-value>
	</init-param>
	<init-param>
		<param-name>log</param-name>
		<param-value>true</param-value>
	</init-param>
```

**Comment by titoparizotto** [comment]
The RCA from this problem is the rt.jar from de JRE patch updated.
The package com.sun.management.ThreadMXBean is used in net.bull.javamelody.internal.model.MBeansAccessor.java

```java
final class MBeansAccessor {
	private static final MBeanServer MBEAN_SERVER = MBeans.getPlatformMBeanServer();
	private static final Set<ObjectName> NIO_BUFFER_POOLS = getNioBufferPools();
	private static final ObjectName OPERATING_SYSTEM = createObjectName(
			"java.lang:type=OperatingSystem");
	private static final Set<String> OPERATING_SYSTEM_ATTRIBUTES = getAttributesNames(
			OPERATING_SYSTEM);
	private static final ObjectName THREADING = createObjectName("java.lang:type=Threading");
	private static final boolean MBEAN_ALLOCATED_BYTES_ENABLED = getAttributesNames(THREADING).contains("ThreadAllocatedMemoryEnabled");

static long getThreadAllocatedBytes(long threadId) {
		if (!MBEAN_ALLOCATED_BYTES_ENABLED) {
			return -1L;
		}
		try {
			return (Long) MBEAN_SERVER.invoke(THREADING, "getThreadAllocatedBytes",
					new Object[] { threadId }, THREAD_ALLOCATED_BYTES_SIGNATURE);
		} catch (final JMException e) {
			throw new IllegalStateException(e);
		}
	}
```
The property *ThreadAllocatedMemoryEnabled* from Mbean *com.sun.management.ThreadMXBean* is extended from *java.lang.Managment.ThreadMXBean.java* and this class doesn't have a setter for this property.

Debugging the get the MBean *java.lang:type=Threading"* show me this property is false in the JVM.
