### ISSUE TITLE
SQL Capture Will Not Work on Tomcat Releases From 10.1.0

### ISSUE THREAD

**Issue by gmtjlmartin** [javamelody/javamelody#1148]
Versions: 
JavaMelody 1.91.0
Tomcat 10.1.5
OpenJDK Runtime Environment, 17.0.5+8-LTS

After applying work around to get javamelody to run on Tomcat 10.1.5:  `<Loader jakartaConverter="TOMCAT" />`  in context.xml, it was noticed that SQL metrics were not being displayed in  javamelody. The debug log on the home page showed issues with rebinding :

- Debugging logs
-.
-.
-Thu Mar 02 07:41:15 EST 2023     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/ToyUSDataSource]
-Thu Mar 02 07:41:15 EST 2023     DEBUG     rebinding datasource java:comp/env/jdbc/ToyUSDataSource failed, skipping it
-.
-.
-.
-Thu Mar 02 07:41:18 EST 2023     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/ToyUSDataSource]
-Thu Mar 02 07:41:18 EST 2023     DEBUG     rebinding datasource java:comp/env/jdbc/ToyUSDataSource failed, skipping it 

Upon reviewing stack trace from error being reported in web app log the following was noticed:

-2023-03-02T07:41:15,856 main DEBUG (javamelody:59) - datasources found in JNDI: [java:comp/env/jdbc/ToyUSDataSource]
-2023-03-02T07:41:15,872 main DEBUG (javamelody:65) - rebinding datasource java:comp/env/jdbc/ToyUSDataSource failed, skipping it
-javax.naming.OperationNotSupportedException: Context is read only
        -at org.apache.naming.NamingContext.checkWritable(NamingContext.java:1002) ~[catalina.jar:10.1.5]
        -at org.apache.naming.NamingContext.bind(NamingContext.java:920) ~[catalina.jar:10.1.5]
        -at org.apache.naming.NamingContext.rebind(NamingContext.java:230) ~[catalina.jar:10.1.5]
        -at org.apache.naming.NamingContext.rebind(NamingContext.java:246) ~[catalina.jar:10.1.5]
        -at org.apache.naming.SelectorContext.rebind(SelectorContext.java:237) ~[catalina.jar:10.1.5]
        -at javax.naming.InitialContext.rebind(InitialContext.java:425) ~[?:?]
        -at net.bull.javamelody.JdbcWrapperHelper.rebindDataSource(JdbcWrapperHelper.java:128) ~[javamelody-core-1.91.0.jar:1.91.0]
        -at net.bull.javamelody.JdbcWrapper.rebindDataSources(JdbcWrapper.java:479) ~[javamelody-core-1.91.0.jar:1.91.0]
        -at net.bull.javamelody.SessionListener.contextInitialized(SessionListener.java:329) ~[javamelody-core-1.91.0.jar:1.91.0]`

The cause here is partly correct but does not provide the true root-cause. Debugging tomcat application startup shows that the root-cause of the problem is swallowed in a catch statement in the javamelody code found in Class#Method:   [JdbcWrapperHelper#changeContextWritable](https://github.com/javamelody/javamelody/blob/javamelody-core-1.91.0/javamelody-core/src/main/java/net/bull/javamelody/JdbcWrapperHelper.java#L443)

Here is the real root cause:
`java.lang.ClassCastException: class java.util.concurrent.ConcurrentHashMap cannot be cast to class java.util.Hashtable (java.util.concurrent.ConcurrentHashMap and java.util.Hashtable are in module java.base of loader 'bootstrap')`

What happened is that Tomcat changed the datatype of both  readOnlyContexts and securityTokens referenced in the tomcat specific block of code in code JdbcWrapperHelper#changeContextWritable.  So for those of us using tomcat 10.1.x the timebomb is in the following code:

`final Field field = Class.forName("org.apache.naming.ContextAccessController")
					.getDeclaredField("readOnlyContexts");`
			`setFieldAccessible(field);`
			`@SuppressWarnings("unchecked")`
			`final Hashtable<String, Object> readOnlyContexts = (Hashtable<String, Object>) field
					.get(null);`

Its the last line of code shown above that explodes for tomcat 10.1.0 and beyond because of the type mismatch. The change was made in Tomcat 10.1.0-M20 and beyond. Rolling Tomcat back from release 10.1.5 to version 10.1.0-M17 proved to fix the SQL metrics problem; however deploying an M release version of tomcat is not a feasible workaround for most production environments.

The good news is that this looks like it can be fixed without a javamelody code branch which will maintain working SQL metrics for tomcat users on versions prior to release 10.1.x and allow SQL metrics gathering to work for folks using tomcat 10.1.x and beyond. It could be as easy as adding one more layer of logic in the try code block of JdbcWrapperHelper#changeContextWritable  starting at [line 474](https://github.com/javamelody/javamelody/blob/javamelody-core-1.91.0/javamelody-core/src/main/java/net/bull/javamelody/JdbcWrapperHelper.java#L474)

Pseudocode for a :

try{
    if tomcat version less than 10, 
        then use current code  readOnlyContexts  and  securityTokens  as Hashtable 
   else
        write/use new code to handle  readOnlyContexts and  securityTokens as Map 
}

@evernat  I see that you have made some change to this code in version 1.92.0 I wouldn't mind helping to fix/review/test if needed. P.S. Thanks for all you do with javamelody. Been using it for a decade to help make our products stable and performant. Merci beaucoup!

**Comment by gmtjlmartin** [comment]
This issue is fixed with javamelody v1.92.0.  Much appreciated
