### ISSUE TITLE
Latest IBM Java 8 SDK breaks JavaMelody: MBeansAccessor.getThreadAllocatedBytes throws UnsupportedOperationException

### ISSUE THREAD

**Issue by wildberrylillet** [javamelody/javamelody#1165]
The latest IBM Java 8 SDK added partial support for the ThreadMXBean interface but is missing support support for thread memory allocation measurement. The resulting UnsupportedOperationException breaks the whole application.

### IBM Java 8 SDK:
java -version
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 8.0.8.5 - pxa6480sr8fp5-20230418_01(SR8 FP5))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230417_49632 (JIT enabled, AOT enabled)
OpenJ9   - 085a542
OMR      - 9f28c98
IBM      - 68444b7)
JCL - 20230329_01 based on Oracle jdk8u371-b11

### IBM Release Notes:
[source](https://www.ibm.com/docs/en/sdk-java-technology/8?topic=notes-version-0370)
Support added for the com.sun.management.ThreadMXBean interface
The OpenJ9 [ThreadMXbean interface](https://www.ibm.com/links?url=https%3A%2F%2Fwww.eclipse.org%2Fopenj9%2Fdocs%2Fapi-langmgmt%2F) (com.ibm.lang.management.ThreadMXBean) was extending the [java.lang.management.ThreadMXBean](https://www.ibm.com/links?url=https%3A%2F%2Fdocs.oracle.com%2Fjavase%2F8%2Fdocs%2Fapi%2Fjava%2Flang%2Fmanagement%2FThreadMXBean.html) interface. With this release, the OpenJ9 ThreadMXBean interface extends the [com.sun.management.ThreadMXBean](https://www.ibm.com/links?url=https%3A%2F%2Fdocs.oracle.com%2Fjavase%2F8%2Fdocs%2Fjre%2Fapi%2Fmanagement%2Fextension%2Fcom%2Fsun%2Fmanagement%2FThreadMXBean.html) interface, whereby it now contains all the methods of the java.lang.management.ThreadMXBean interface with additional methods from the com.sun.management.ThreadMXBean interface.

**The OpenJ9 VM implementation does not support thread memory allocation measurement (isThreadAllocatedMemorySupported method returns false).**

### Stacktrace:
Caused by: java.lang.UnsupportedOperationException
        at com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl.getThreadAllocatedBytes(ExtendedThreadMXBeanImpl.java:74) ~[?:2.9 (04-17-2023)]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90) ~[?:1.8.0]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[?:1.8.0]
        at java.lang.reflect.Method.invoke(Method.java:508) ~[?:1.8.0]
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:83) ~[?:1.8.0]
        at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[?:1.8.0]
        at java.lang.reflect.Method.invoke(Method.java:508) ~[?:1.8.0]
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:287) ~[?:1.8.0]
        at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:205) ~[?:1.8.0]
        at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:187) ~[?:1.8.0]
        at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:129) ~[?:1.8.0]
        at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:66) ~[?:1.8.0]
        at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:249) ~[?:1.8.0]
        at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:150) ~[?:1.8.0]
        at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:264) ~[?:1.8.0]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:831) ~[?:1.8.0]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:813) ~[?:1.8.0]
        at net.bull.javamelody.internal.model.MBeansAccessor.getThreadAllocatedBytes(MBeansAccessor.java:127) ~[javamelody-core-1.94.0.jar:1.94.0]

**Comment by wildberrylillet** [comment]
[see also](https://github.com/eclipse-openj9/openj9/pull/16915/commits/b975c9db29d48b02d5458bd7e64a965f3f45d06f)

**Comment by michaelknigge** [comment]
Same issue with newer versions of IBM Java 11:

java version "11.0.19" 2023-04-18
IBM Semeru Runtime Certified Edition for z/OS 11.0.19.0 (build 11.0.19+7)
IBM J9 VM 11.0.19.0 (build z/OS-Release-11.0.19.0-b01, JRE 11 z/OS s390x-64-Bit Compressed References 20230516_269 (JIT enabled, AOT enabled)
OpenJ9   - a92690a70a9
OMR      - 9f28c98e431
IBM      - 68444b7
JCL      - 05b3cf78a01 based on jdk-11.0.19+7)

I would be very grateful for a new release of JavaMeldoy with the fix...

**Comment by evernat** [comment]
PR reviewed

**Comment by gpsre** [comment]
Thank you, code adjusted according to review.

**Comment by wildberrylillet** [comment]
Looks good, thank you!
