### ISSUE TITLE
NPE in jira-confluence-javamelody-1.98.0

### ISSUE THREAD

**Issue by bugza** [javamelody/javamelody#1217]
NPE in any Atlassian Jira  versions and jira-confluence-javamelody-1.98.0.jar:

2024-04-29 06:11:43,072+0000 http-nio-8080-exec-49 ERROR      [o.a.c.c.C.[.[localhost].[/].[noopservlet]] Servlet.service() for servlet [noopservlet] in context with path [] threw exception
java.lang.NullPointerException: Deflater has been closed
at java.base/java.util.zip.Deflater.ensureOpen(Unknown Source)
at java.base/java.util.zip.Deflater.deflate(Unknown Source)
at java.base/java.util.zip.DeflaterOutputStream.flush(Unknown Source)
at com.atlassian.gzipfilter.GzipResponseStream.flush(GzipResponseStream.java:31)
at com.atlassian.gzipfilter.RoutableServletOutputStream.flush(RoutableServletOutputStream.java:138)
at net.bull.javamelody.internal.web.FilterServletOutputStream.flush(FilterServletOutputStream.java:69)
at net.bull.javamelody.internal.web.FilterServletResponseWrapper.flushStream(FilterServletResponseWrapper.java:169)
at net.bull.javamelody.internal.web.CounterServletResponseWrapper.flushStream(CounterServletResponseWrapper.java:30)
at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:241)
at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:88)
at net.bull.javamelody.JiraMonitoringFilter.doFilter(JiraMonitoringFilter.java:137)
... 22 filtered
at com.atlassian.jira.servermetrics.MetricsCollectorFilter.doFilter(MetricsCollectorFilter.java:25)
... 25 filtered
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
at java.base/java.lang.Thread.run(Unknown Source)

**Comment by evernat** [comment]
this is not a javamelody issue.

It happens for example in JIRA and Bitbucket without javamelody. See for example https://jira.atlassian.com/browse/BSERV-13561
So closing this as invalid.
