### ISSUE TITLE
used memory chart not loaded

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#139]
```

Getting following exception.kindly advice.

10:55:59,163  WARN [javamelody osc] (net.bull.javamelody.LOG:warn) - exception 
while collecting data
java.lang.ArithmeticException: / by zero
      at org.jrobin.core.Archive.archive(Unknown Source)
      at org.jrobin.core.RrdDb.archive(Unknown Source)
      at org.jrobin.core.Datasource.process(Unknown Source)
      at org.jrobin.core.RrdDb.store(Unknown Source)
      at org.jrobin.core.Sample.update(Unknown Source)
      at net.bull.javamelody.JRobin.addValue(JRobin.java:306)
      at net.bull.javamelody.Collector.collectJRobinValues(Collector.java:395)
      at net.bull.javamelody.Collector.collectJavaInformations(Collector.java:337)
      at net.bull.javamelody.Collector.collect(Collector.java:257)
      at net.bull.javamelody.Collector.collectWithoutErrors(Collector.java:243)
      at net.bull.javamelody.Collector.collectLocalContextWithoutErrors(Collector.java:233)
      at net.bull.javamelody.FilterContext$CollectTimerTask.run(FilterContext.java:52)
      at java.util.TimerThread.mainLoop(Unknown Source)
      at java.util.TimerThread.run(Unknown Source)
10:56:59,181  WARN [javamelody osc] (net.bull.javamelody.LOG:warn) - exception 
while collecting data
java.lang.ArithmeticException: / by zero
      at org.jrobin.core.Archive.archive(Unknown Source)
      at org.jrobin.core.RrdDb.archive(Unknown Source)
      at org.jrobin.core.Datasource.process(Unknown Source)
      at org.jrobin.core.RrdDb.store(Unknown Source)
      at org.jrobin.core.Sample.update(Unknown Source)
      at net.bull.javamelody.JRobin.addValue(JRobin.java:306)
      at net.bull.javamelody.Collector.collectJRobinValues(Collector.java:395)
      at net.bull.javamelody.Collector.collectJavaInformations(Collector.java:337)
      at net.bull.javamelody.Collector.collect(Collector.java:257)
      at net.bull.javamelody.Collector.collectWithoutErrors(Collector.java:243)
      at net.bull.javamelody.Collector.collectLocalContextWithoutErrors(Collector.java:233)
      at net.bull.javamelody.FilterContext$CollectTimerTask.run(FilterContext.java:52)
      at java.util.TimerThread.mainLoop(Unknown Source)
      at java.util.TimerThread.run(Unknown Source)


Please provide any additional information below.

Used Memory Chart not loaded



```

Original issue reported on code.google.com by `nklg...@gmail.com` on 19 Sep 2011 at 6:42

**Comment by evernat** [comment]
see also https://issues.jenkins-ci.org/browse/JENKINS-51590
