### ISSUE TITLE
heaphisto report failed -- unsatisfied link error with multiple webapps in tomcat 7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#398]
```
What steps will reproduce the problem?
1. deploy two webapps (with javamelody.jar in WEB-INF/lib or javamelody.jar in 
tomcat lib) in a tomcat7 instance
2. on each webapp do http://<host>:<port>/<app>/monitoring?part=heaphisto
3. see exception in the log

What is the expected output? What do you see instead?
For the first webapp. It is ok and always able to show the heap histogram.
For the second webapp. The front end show a pop up message request using the 
JDK. Then the "View memory histogram"  button disappear.
It is sure the tomcat startup with JDK.
And there is exception log.

the below show the exception log from windows. And it is also encounter in 
redhat.

java.lang.UnsatisfiedLinkError: Native Library C:\Program 
Files\Java\jdk1.6.0_35\jre\bin\attach.dll already loaded in another classloader
2014-03-31 10:28:02.977 WARN  [] [127.0.0.1] net.bull.javamelody - heaphisto 
report failed
java.lang.IllegalStateException: Memory histogram not supported because the 
server uses the JRE and not the JDK.
Check that a JDK is installed and check the environment variable JAVA_HOME or 
the launch file.
        at net.bull.javamelody.VirtualMachine.heapHisto(VirtualMachine.java:164) ~[javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.VirtualMachine.createHeapHistogram(VirtualMachine.java:175) ~[javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.HtmlController.doHeapHisto(HtmlController.java:222) [javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.HtmlController.doHtmlPartForSystemActions(HtmlController.java:152) [javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.HtmlController.doHtmlPart(HtmlController.java:140) [javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.HtmlController.doHtml(HtmlController.java:105) [javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.MonitoringController.doCompressedHtml(MonitoringController.java:240) [javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.MonitoringController.doReportCore(MonitoringController.java:197) [javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.MonitoringController.doReport(MonitoringController.java:185) [javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:143) [javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:349) [javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:172) [javamelody-core-1.49.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.42]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.42]
        at com.pccw.webppb.server.filter.RequestInfoLog.doFilter(RequestInfoLog.java:65) [RequestInfoLog.class:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.42]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.42]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) [spring-web-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.42]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.42]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.42]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.42]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:7.0.42]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.42]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.42]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [catalina.jar:7.0.42]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.42]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.42]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023) [tomcat-coyote.jar:7.0.42]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.42]
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1852) [tomcat-coyote.jar:7.0.42]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_35]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_35]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_35]
Caused by: com.sun.tools.attach.AttachNotSupportedException: no providers 
installed
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:190) ~[na:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_35]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_35]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_35]
        at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_35]
        at net.bull.javamelody.VirtualMachine.invoke(VirtualMachine.java:185) ~[javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.VirtualMachine.getJvmVirtualMachine(VirtualMachine.java:88) ~[javamelody-core-1.49.0.jar:na]
        at net.bull.javamelody.VirtualMachine.heapHisto(VirtualMachine.java:150) ~[javamelody-core-1.49.0.jar:na]
        ... 34 common frames omitted

What version of the product are you using? On what application server, JDK,
operating system?

a)
javamelody 1.49
Server version: Apache Tomcat/7.0.42
Server number:  7.0.42.0
OS Name:        Windows 7
OS Version:     Professional
Architecture:   Intel 32bit
JVM Version:    1.6.0_35
JVM Vendor:     Oracle

b)
javamelody 1.49
Server version: Apache Tomcat/7.0.47
Server number:  7.0.47.0
OS Name:        RedHat 
OS Version:     4.1.2-48
Architecture:   Intel 64bit
JVM Version:    1.7.0_25
JVM Vendor:     Oracle

Please provide any additional information below.
It is very similar to issue 273.

```

Original issue reported on code.google.com by `hei1...@gmail.com` on 31 Mar 2014 at 3:09

**Comment by evernat** [comment]
For the record, the tentative fix for this issue was at https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/VirtualMachine.java#L116 :
```java
final ClassLoader cl;
if (ClassLoader.getSystemClassLoader() instanceof URLClassLoader) {
	// The attachment API relies on JNI, so if we have other code in the JVM that tries to use the attach API
	// (like the monitoring of another webapp), it'll cause a failure (issue 398):
	// "UnsatisfiedLinkError: Native Library C:\Program Files\Java\jdk1.6.0_35\jre\bin\attach.dll already loaded in another classloader
	// [...] com.sun.tools.attach.AttachNotSupportedException: no providers installed"
	// So we try to load tools.jar into the system classloader, so that later attempts to load tools.jar will see it.
	cl = ClassLoader.getSystemClassLoader();
	// The URLClassLoader.addURL method is protected
	final Method addURL = URLClassLoader.class.getDeclaredMethod("addURL", URL.class);
	addURL.setAccessible(true);
	addURL.invoke(cl, url);
} else {
	final URL[] urls = { url };
	cl = URLClassLoader.newInstance(urls);
}
```

**Comment by evernat** [comment]
The fix for compatibility of the heap histogram with JDK 9 in javamelody 1.73.1 without VM attach has certainly fixed this issue in JDK 9 (and also in JDK 8). So closing as fixed.
