### ISSUE TITLE
net.sf.ehcache.transaction.TransactionException: transaction not started

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#402]
```
After adding javamelody to our project, I see lots of these exceptions in the 
log:

net.sf.ehcache.transaction.TransactionException: transaction not started
    at net.sf.ehcache.transaction.local.LocalTransactionStore.getCurrentTransactionContext(LocalTransactionStore.java:108) ~[ehcache-core-2.6.5.jar:na]
    at net.sf.ehcache.transaction.local.LocalTransactionStore.assertNotTimedOut(LocalTransactionStore.java:114) ~[ehcache-core-2.6.5.jar:na]
    at net.sf.ehcache.transaction.local.LocalTransactionStore.assertNotTimedOut(LocalTransactionStore.java:130) ~[ehcache-core-2.6.5.jar:na]
    at net.sf.ehcache.transaction.local.LocalTransactionStore.getSize(LocalTransactionStore.java:543) ~[ehcache-core-2.6.5.jar:na]
    at net.sf.ehcache.Cache.getSize(Cache.java:2588) ~[ehcache-core-2.6.5.jar:na]
    at net.sf.ehcache.Cache.getSizeBasedOnAccuracy(Cache.java:2598) ~[ehcache-core-2.6.5.jar:na]
    at net.sf.ehcache.Cache.getStatistics(Cache.java:3077) ~[ehcache-core-2.6.5.jar:na]
    at net.bull.javamelody.CacheInformations.<init>(CacheInformations.java:79) ~[javamelody-core-1.50.0.jar:1.50.0]
    at net.bull.javamelody.CacheInformations.buildCacheInformationsList(CacheInformations.java:165) ~[javamelody-core-1.50.0.jar:1.50.0]
    at net.bull.javamelody.JavaInformations.<init>(JavaInformations.java:188) [javamelody-core-1.50.0.jar:1.50.0]
    at net.bull.javamelody.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:141) [javamelody-core-1.50.0.jar:1.50.0]
    at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:348) [javamelody-core-1.50.0.jar:1.50.0]
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:171) [javamelody-core-1.50.0.jar:1.50.0]

I couldn't find anything in the documentation regarding ehcache and 
transactions.
```

Original issue reported on code.google.com by `adigu...@gmail.com` on 11 Apr 2014 at 8:02

**Comment by digulla** [comment]
We're using `transactionalMode="local"` since it's the only mode which makes sense at all. XA modes are brittle and can cause data corruption. So what we do is we hook into the DB transaction manager and when it tells us that the DB transaction has been committed, we submit the same changes to the ehcache manager. That way, we can flush the cache on any error (= will be repopulated from the database) and we can make sure changes become visible to other threads after they have been committed to the DB as well.

**Comment by evernat** [comment]
I have reduced the number of exceptions logged to one, at debug level, to not flood the logs.
Commit 31b920e876034e9199d95ff1bcea5ebfcd5d98ac
