### ISSUE TITLE
ClassNotFoundException: javax.persistence.spi.PersistenceProvider

### ISSUE THREAD

**Issue by iamkookz** [javamelody/javamelody#500]
My server has javamelody installed under Tomcat/lib

and i tried to install another more application to this tomcat but it's always fail with this error code

Caused by: java.lang.NoClassDefFoundError: javax/persistence/spi/PersistenceProvider
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1470)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1329)
	at javax.persistence.spi.PersistenceProviderResolverHolder$PersistenceProviderResolverPerClassLoader$CachingPersistenceProviderResolver.loadResolverClasses(PersistenceProviderResolverHolder.java:150)
	at javax.persistence.spi.PersistenceProviderResolverHolder$PersistenceProviderResolverPerClassLoader$CachingPersistenceProviderResolver.<init>(PersistenceProviderResolverHolder.java:130)
	at javax.persistence.spi.PersistenceProviderResolverHolder$PersistenceProviderResolverPerClassLoader.getPersistenceProviders(PersistenceProviderResolverHolder.java:88)
	at javax.persistence.Persistence.getProviders(Persistence.java:75)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:61)
	at org.springframework.orm.jpa.LocalEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalEntityManagerFactoryBean.java:96)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1625)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1562)
	... 64 more
Caused by: java.lang.ClassNotFoundException: javax.persistence.spi.PersistenceProvider
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 86 more

I try to investigate on this issue and i found that the root cause of this application error is because we have javamelody-1.56.0.jar installed on tomcat/lib

I've found 3 solution to make this application works
1. use  javamelody 1.49 or earlier
2. move hibernate-jpa-2.1-api-1.0.0.Final.jar into tomcat/lib
3. remove "javax.persistence.spi.PersistenceProvider" file from javamelody-1.57.0.jar\META-INF\services\

Do you have any suggestion for us? I know that all of my solutions above are quite bad case.

**Comment by evernat** [comment]
My suggestion would be as said in the user's guide put the javamelody jar file in your webapp/WEB-INF/lib and not in tomcat/lib. (javamelody in tomcat/lib is not officially supported as said in the Advanced user's guide.)
Otherwise, adding hibernate-jpa-2.1-api-1.0.0.Final.jar into tomcat/lib may work.
