### ISSUE TITLE
Javamelody not working with JIRA 7

### ISSUE THREAD

**Issue by jprusch** [javamelody/javamelody#503]
When trying to access the monitoring URL, we get error 500:

2015-10-16 12:22:57,340 http-nio-8080-exec-12 ERROR      [o.a.c.c.C.[.[.s.local].[/jira].[default]] Servlet.service() for servlet [default] in context with path [/jira] threw exception
java.lang.IllegalStateException: java.lang.NoSuchMethodException: com.atlassian.jira.ManagerFactory.getPermissionManager()
	at net.bull.javamelody.JiraMonitoringFilter.hasJiraSystemAdminPermission(JiraMonitoringFilter.java:220)
	at net.bull.javamelody.JiraMonitoringFilter.checkJiraAdminPermission(JiraMonitoringFilter.java:146)
	at net.bull.javamelody.JiraMonitoringFilter.hasNotPermission(JiraMonitoringFilter.java:128)
	at net.bull.javamelody.JiraMonitoringFilter.doFilter(JiraMonitoringFilter.java:97)
	at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:78)
	... 45 filtered
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodException: com.atlassian.jira.ManagerFactory.getPermissionManager()
	at java.lang.Class.getMethod(Class.java:1786)
	at net.bull.javamelody.JiraMonitoringFilter.hasJiraSystemAdminPermission(JiraMonitoringFilter.java:199)
	... 53 more

**Comment by evernat** [comment]
This is fixed in the JIRA / Confluence / Bamboo plugin **v.1.57.1** just released.
https://github.com/javamelody/javamelody/releases
Thanks for the issue.
