### ISSUE TITLE
javaMelody  - java.io.IOException 

### ISSUE THREAD

**Issue by wonderlq** [javamelody/javamelody#516]
i add the mail function ,so , i  receive many e-mails about  this exception, 
i'm going to crazy

11:38:56,807 WARN  [javamelody] exception while collecting data for application appcen
11:38:56,807 WARN  [javamelody] java.io.IOException: Server returned HTTP response code: 503  for URL: http://manage.testclouds.com/mystore/monitoring?collector=stop&format=serialized

java.io.IOException: Server returned HTTP response code: 503 for URL: http://manage.testclouds.com/mystore/monitoring?collector=stop&format=serialized at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
         at net.bull.javamelody.LabradorRetriever.call(LabradorRetriever.java:154)
         at net.bull.javamelody.RemoteCall.collectForUrl(RemoteCall.java:306)
         at net.bull.javamelody.RemoteCall.collectData(RemoteCall.java:108)
         at net.bull.javamelody.RemoteCollector.collectDataWithUrls(RemoteCollector.java:80)
         at net.bull.javamelody.RemoteCollector.collectData(RemoteCollector.java:62)
         at net.bull.javamelody.CollectorServer.collectForApplication(CollectorServer.java:201)
         at net.bull.javamelody.CollectorServer.collectForApplication(CollectorServer.java:175)
         at net.bull.javamelody.CollectorServer.collectForApplicationWithoutErrors(CollectorServer.java:125)
        at net.bull.javamelody.CollectorServer$2.run(CollectorServer.java:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

11:50:56,805 WARN  [javamelody] exception while collecting data for application appcen
11:50:56,805 WARN  [javamelody] java.io.IOException: Server returned HTTP response code: 503 for URL: http://manage.testclouds.com/mystore/monitoring?collector=stop&format=serialized

java.io.IOException: Server returned HTTP response code: 503 for URL: http://manage.testclouds.com/mystore/monitoring?collector=stop&format=serialized
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
        at net.bull.javamelody.LabradorRetriever.call(LabradorRetriever.java:154)
        at net.bull.javamelody.RemoteCall.collectForUrl(RemoteCall.java:306)
        at net.bull.javamelody.RemoteCall.collectData(RemoteCall.java:108)
        at net.bull.javamelody.RemoteCollector.collectDataWithUrls(RemoteCollector.java:80)
        at net.bull.javamelody.RemoteCollector.collectData(RemoteCollector.java:62)
        at net.bull.javamelody.CollectorServer.collectForApplication(CollectorServer.java:201)
        at net.bull.javamelody.CollectorServer.collectForApplication(CollectorServer.java:175)
        at net.bull.javamelody.CollectorServer.collectForApplicationWithoutErrors(CollectorServer.java:125)
        at net.bull.javamelody.CollectorServer$2.run(CollectorServer.java:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
.......

**Comment by evernat** [comment]
At some points in time, the monitored app returns http error code 503, which means "Service Unavailable". In that case, the optional collect server sends you an email to warn you about a critical problem: your app is not unavailable at that moment.
I suggest that you fix the problem in your app or you can remove the email parameter from the collect server.
