### ISSUE TITLE
trying to send daily reports to mail but struck with the error, please help me out in this

### ISSUE THREAD

**Issue by abhishek1623** [javamelody/javamelody#527]
I got this error while sending the email via javamelody, please help me in this?
i entered this URL for a test mail but getting the error,
"http://devops-7520n58y.cloudapp.net:8080/monitoring?action=mail_test"

Log's referral number: 14f5fe2c-968f-4e01-87e9-c53da950744e
Cause

Referer URL: Unknown

java.lang.IllegalStateException: mail-session has no value: add the mail-session parameter

    java.lang.IllegalStateException: mail-session has no value: add the mail-session parameter
    	at net.bull.javamelody.Action.mailTest(Action.java:294) [jira-javamelody-1.58.0.jar:?]
    	at net.bull.javamelody.Action.execute(Action.java:187) [jira-javamelody-1.58.0.jar:?]
    	at net.bull.javamelody.MonitoringController.executeActionIfNeeded(MonitoringController.java:123) [jira-javamelody-1.58.0.jar:?]
    	at net.bull.javamelody.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:137) [jira-javamelody-1.58.0.jar:?]
    	at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:344) [jira-javamelody-1.58.0.jar:?]
    	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:169) [jira-javamelody-1.58.0.jar:?]
    	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:85) [jira-javamelody-1.58.0.jar:?]
    	at net.bull.javamelody.JiraMonitoringFilter.doFilter(JiraMonitoringFilter.java:104) [jira-javamelody-1.58.0.jar:?]
    	at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:78) [atlassian-plugins-servlet-4.0.4.jar:?]
    	at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:42) [atlassian-plugins-servlet-4.0.4.jar:?]
    	at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:77) [atlassian-plugins-servlet-4.0.4.jar:?]
    	at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:63) [atlassian-plugins-servlet-4.0.4.jar:?]
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.17]
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.17]
    	at com.atlassian.jira.web.filters.steps.ChainedFilterStepRunner.doFilter(ChainedFilterStepRunner.java:74) [ChainedFilterStepRunner.class:?]
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.17]
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.17]
    	at com.atlassian.core.filters.cache.AbstractCachingFilter.doFilter(AbstractCachingFilter.java:33) [atlassian-core-5.0.3.jar:?]
    	at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31) [atlassian-core-5.0.3.jar:?]
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.17]
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.17]
    	at com.atlassian.core.filters.encoding.AbstractEncodingFilter.doFilter(AbstractEncodingFilter.java:41) [atlassian-core-5.0.3.jar:?]
    	at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31) [atlassian-core-5.0.3.jar:?]
    	at com.atlassian.jira.web.filters.PathMatchingEncodingFilter.doFilter(PathMatchingEncodingFilter.java:41) [PathMatchingEncodingFilter.class:?]
    	at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31) [atlassian-core-5.0.3.jar:?]
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.17]
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.17]
    	at com.atlassian.jira.startup.JiraStartupChecklistFilter.doFilter(JiraStartupChecklistFilter.java:65) [JiraStartupChecklistFilter.class:?]
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.17]
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.17]
    	at com.atlassian.jira.web.filters.MultipartBoundaryCheckFilter.doFilter(MultipartBoundaryCheckFilter.java:36) [MultipartBoundaryCheckFilter.class:?]
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.17]
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.17]
    	at com.atlassian.jira.web.filters.steps.ChainedFilterStepRunner.doFilter(ChainedFilterStepRunner.java:74) [ChainedFilterStepRunner.class:?]
    	at com.atlassian.jira.web.filters.JiraFirstFilter.doFilter(JiraFirstFilter.java:57) [JiraFirstFilter.class:?]
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.17]
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.17]
    	at com.atlassian.gzipfilter.GzipFilter.doFilterInternal(GzipFilter.java:115) [atlassian-gzipfilter-3.0.0.jar:?]
    	at com.atlassian.gzipfilter.GzipFilter.doFilter(GzipFilter.java:92) [atlassian-gzipfilter-3.0.0.jar:?]
    	at com.atlassian.jira.web.filters.gzip.JiraGzipFilter.doFilter(JiraGzipFilter.java:52) [JiraGzipFilter.class:?]
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.17]
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.17]
    	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.17]
    	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.17]
    	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.17]
    	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.17]
    	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.17]
    	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.17]
    	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.17]
    	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.17]
    	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.17]
    	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.17]
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.17]
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.17]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
    	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.17]
    	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by abhishek1623** [comment]
the problem is solved , i copied the the entire code below to the bottom of the files web.xml, server.xml and to the context.xml  ...and it solved the problem for me.

 <Resource name="mail/MySession" auth="Container" type="javax.mail.Session"
                mail.smtps.host="smtp.gmail.com"
                mail.smtps.user="abhisheksoni******@gmail.com"
                mail.from="abhishek"
                mail.smtps.auth="true"
                mail.smtps.password="*******"
                mail.transport.protocol="smtps"

        />
        <Parameter name='javamelody.admin-emails' value='abhishek*******@gmail.com,asoni***@csc.com' override='false'/>
        <Parameter name='javamelody.mail-session' value='mail/MySession' override='false'/>
        <Parameter name='javamelody.mail-periods' value='day,week,month' override='false'/>
