### ISSUE TITLE
Javamelody 1.58: getOutputStream() has already been called for this response

### ISSUE THREAD

**Issue by JonathanSandim** [javamelody/javamelody#530]
Hi, 

   I using Javamelody version 1.58. In server Javamelody Collector version Tomcat is:  6.0.39  and JVM 1.7.  Tomcat Client is old: 6.0.13 and JVM 1.6.  

    Has been appearing in log this error: 

java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at net.bull.javamelody.FilterServletResponseWrapper.getWriter(FilterServletResponseWrapper.java:120)
	at com.powerlogic.ecompany.controle.EcpCacheRequestProcessor.process(EcpCacheRequestProcessor.java:439)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1192)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:412)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.powerlogic.ecompany.controle.filter.EcpJMonitorFilter.doFilter(EcpJMonitorFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.powerlogic.jcompany.jsecurity.controle.PlcJSecurityFilter.doFilter(PlcJSecurityFilter.java:150)
	at com.powerlogic.jcompany.controle.filter.PlcMasterFilter.doFilter(PlcMasterFilter.java:240)
	at com.powerlogic.ecompany.controle.filter.EcpMasterFilter.doFilter(EcpMasterFilter.java:57)
	at com.pbh.ecompany.controle.filter.AppMasterFilter.doFilter(AppMasterFilter.java:17)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.powerlogic.ecompany.controle.filter.EcpUrlRewriteFilter.doFilter(EcpUrlRewriteFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.powerlogic.jcompany.jsecurity.controle.PlcJSecurityFilter.doFilter(PlcJSecurityFilter.java:150)
	at com.powerlogic.jcompany.controle.filter.PlcMasterFilter.doFilter(PlcMasterFilter.java:240)
	at com.powerlogic.ecompany.controle.filter.EcpMasterFilter.doFilter(EcpMasterFilter.java:57)
	at com.pbh.ecompany.controle.filter.AppMasterFilter.doFilter(AppMasterFilter.java:17)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:200)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:433)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:393)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:261)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:283)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:767)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:697)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:889)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:686)
	at java.lang.Thread.run(Thread.java:662)

I'm back version to 1.54 and not resolved. Any ideias?

**Comment by evernat** [comment]
It's probably an issue between the javamelody MonitoringFilter and one of your other filters.
Can you give the source code of a simple webapp (using Maven if possible) to reproduce the issue?

**Comment by evernat** [comment]
@JonathanSandim 
Any news about this issue?

**Comment by evernat** [comment]
No response from the reporter, so closing as invalid / incomplete.
