### ISSUE TITLE
Cannot flush a closed output stream

### ISSUE THREAD

**Issue by mikerohan** [javamelody/javamelody#532]
Hi,

we are getting this exception in our Tomcat8 after adding JavaMelody:

`18-Feb-2016 11:32:52.822 SEVERE [http-nio-10080-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() para servlet RCallServlet lanzó excepción
 java.io.IOException: Cannot flush a closed output stream
	at util.CompressionResponseStream.flush(CompressionResponseStream.java:150)
	at net.bull.javamelody.FilterServletOutputStream.flush(FilterServletOutputStream.java:65)
	at net.bull.javamelody.FilterServletResponseWrapper.flushBuffer(FilterServletResponseWrapper.java:153)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:202)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at repcon.RepconURLFilter.doFilter(RepconURLFilter.java:206)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at util.GzipFilter.doFilter(GzipFilter.java:155)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:613)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:291)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)`

any ideas?, thanks!

**Comment by evernat** [comment]
You have a util.GzipFilter which is before the MonitoringFilter and you have a response which uses an output stream (not a writer) and which closes the output stream itself.
And your util.CompressionResponseStream class from the GzipFilter does not accept that flush() is called by the MonitoringFilter on a closed output stream. This fact can be debatable.

Anyway, the MonitoringFilter does not try to flush an already closed output stream anymore.
This is merged in master ([d8f114a](https://github.com/javamelody/javamelody/commit/d8f114a4dbda659a9e34bfd2f24a3adc13a9e260)).
There is a nightly build available at:
https://javamelody.ci.cloudbees.com/job/javamelody/ws/javamelody-core/javamelody.jar

**Comment by evernat** [comment]
And thanks!

**Comment by mikerohan** [comment]
It works!

Thanks
