### ISSUE TITLE
IllegalArgumentException during metrics database update (JENKINS-33050)

### ISSUE THREAD

**Issue by oleg-nenashev** [javamelody/javamelody#533]
Hello, we see <code>IllegalArgumentException</code>s in JavaMelody metrics collector. Issue in Jenkins bugtracker: [JENKINS-33050](https://issues.jenkins-ci.org/browse/JENKINS-33050)

It seems like a missing bounds check in https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/RrdNioBackend.java#L146-L149 . The underlying buffer management code is http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/nio/Buffer.java#235 , so there's only one way to get this exception.

```
WARNING	net.bull.javamelody.JavaLogger#warn: exception while collecting data: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
at java.nio.Buffer.position(Buffer.java:244)
at net.bull.javamelody.RrdNioBackend.read(RrdNioBackend.java:147)
at org.jrobin.core.RrdBackend.readInt(RrdBackend.java:224)
at org.jrobin.core.RrdPrimitive.readInt(RrdPrimitive.java:63)
at org.jrobin.core.RrdInt.get(RrdInt.java:55)
at org.jrobin.core.Archive.<init>(Archive.java:69)
at org.jrobin.core.RrdDb.<init>(RrdDb.java:244)
at org.jrobin.core.RrdDb.<init>(RrdDb.java:203)
at org.jrobin.core.RrdDb.<init>(RrdDb.java:266)
at org.jrobin.core.RrdDbPool.requestRrdDb(RrdDbPool.java:103)
at net.bull.javamelody.JRobin.addValue(JRobin.java:334)
at net.bull.javamelody.Collector.collectJRobinValues(Collector.java:491)
at net.bull.javamelody.Collector.collectJavaInformations(Collector.java:382)
at net.bull.javamelody.Collector.collect(Collector.java:320)
at net.bull.javamelody.Collector.collectWithoutErrors(Collector.java:306)
at net.bull.javamelody.Collector.collectLocalContextWithoutErrors(Collector.java:295)
at net.bull.javamelody.FilterContext$CollectTimerTask.run(FilterContext.java:56)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)
```

**Comment by evernat** [comment]
I think that a file in the storage directory was corrupted somewhere in the middle of the file. And that javamelody / jrobin can't read it anymore.
You can try to find if ".rrd" file(s) in the storage directory do not have the same size as the others and to delete it.

I have added a catch in the code to auto-reset the file in this case. (2eff216)
And 1.59 release is planned soon including that fix.
