### ISSUE TITLE
JavaMelody not working with JIRA 7.1

### ISSUE THREAD

**Issue by tobiheinemann** [javamelody/javamelody#542]
Using JavaMelody 1.59.0 and HEAD of master branch leads to:

2016-04-06 15:54:41,681 http-nio-10.85.128.73-443-exec-14 ERROR      [o.a.c.c.C.[.[localhost].[/].[default]] Servlet.service() for servlet [default] in context with path [] threw exception
java.lang.IllegalStateException: java.lang.IllegalArgumentException: argument type mismatch
        at net.bull.javamelody.JiraMonitoringFilter.hasJiraSystemAdminPermission(JiraMonitoringFilter.java:224)
        at net.bull.javamelody.JiraMonitoringFilter.checkJiraAdminPermission(JiraMonitoringFilter.java:147)
        at net.bull.javamelody.JiraMonitoringFilter.hasNotPermission(JiraMonitoringFilter.java:129)
        at net.bull.javamelody.JiraMonitoringFilter.doFilter(JiraMonitoringFilter.java:98)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:64)
        ... 46 filtered
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.bull.javamelody.JiraMonitoringFilter.hasJiraSystemAdminPermission(JiraMonitoringFilter.java:210)

**Comment by evernat** [comment]
I do not reproduce the issue using JIRA 7.1.0.
What version exactly do you have?

**Comment by tobiheinemann** [comment]
I am using JIRA 7.1.4.

**Comment by tobiheinemann** [comment]
I put that into getUser method of JiraMonitoringFilter.java, but please handle with care. I don't know how old versions of JIRA will react with it.

		if (jira) {
			if (result instanceof Principal && jiraGetUserByNameExists){
				final String userName = ((Principal) result).getName();
				try {
					final Class<?> componentAccessorClass = Class
							.forName("com.atlassian.jira.component.ComponentAccessor");
					final Object userManager = componentAccessorClass
							.getMethod("getUserManager").invoke(componentAccessorClass, null);

					try {
						result = userManager.getClass().getMethod("getUserByName", String.class)
								.invoke(userManager, userName);
					} catch (final NoSuchMethodException e) {
						jiraGetUserByNameExists = false;
					}
				} catch (final Exception e) {
					throw new IllegalStateException(e);
				}

			}
		}

**Comment by evernat** [comment]
I do not reproduce the issue using JIRA 7.1.4.
In the getUser method above, what is the class of the "result" object?
And do you use a fresh JIRA install to reproduce the issue? (Or how can I reproduce the issue?)
Thanks

**Comment by evernat** [comment]
Any news?

**Comment by 1cec0ldAlpha** [comment]
Thanks for the reply. We support a LARGE environment and switching the jdbc
connection to a configuration noted by the Vendor that may not be
"optimized for Atlassian Applications" may not be the best approach to
simply gather additional database metrics for the suite.

On Sat, May 7, 2016 at 3:32 PM, evernat <notifications@github.com> wrote:

> Any news?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/javamelody/javamelody/issues/542#issuecomment-217663930>
>



-- 
"Blessed be the givers and Cursed be the Thief, may fortune smile upon the
Truth and Liars come to Grief" - *Golden Tarot*

**Comment by evernat** [comment]
@1cec0ldAlpha 
I think that you are on the wrong issue. You want probably #552 
I have anwsered in #552

**Comment by evernat** [comment]
No response from the reporter so closing as invalid/incomplete.

**Comment by tobiheinemann** [comment]
Sorry to bump that old issue. We have been using an outdated custom authenticator that pushed a wrong user object into the HTTP session. JavaMelody works fine with standard JIRA 7.x
