### ISSUE TITLE
SQL Stats doesn't work in tomcat 7

### ISSUE THREAD

**Issue by nicolasrosado** [javamelody/javamelody#545]
Hi,

I have severals environments. 

In integration and in local I can see SQL stats. 
See below logs in integration : 

JavaMelody 1.59.0 
 Debugging logs 
Thu Apr 21 17:21:08 CEST 2016     DEBUG     JavaMelody listener init started
Thu Apr 21 17:21:08 CEST 2016     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/------]
**Thu Apr 21 17:21:08 CEST 2016     DEBUG     datasource rebinded: java:comp/env/jdbc/------ from class org.apache.tomcat.dbcp.dbcp.BasicDataSource to class com.sun.proxy.$Proxy983**
Thu Apr 21 17:21:08 CEST 2016     DEBUG     JavaMelody listener init done in 15 ms
Thu Apr 21 17:21:18 CEST 2016     DEBUG     JavaMelody filter init started
Thu Apr 21 17:21:18 CEST 2016     DEBUG     OS: Linux unknown, amd64/64
Thu Apr 21 17:21:18 CEST 2016     DEBUG     Java: Java(TM) SE Runtime Environment, 1.7.0_71-b14
Thu Apr 21 17:21:18 CEST 2016     DEBUG     Server: Apache Tomcat/7.0.57
Thu Apr 21 17:21:18 CEST 2016     DEBUG     Webapp context: /------
Thu Apr 21 17:21:18 CEST 2016     DEBUG     JavaMelody version: 1.59.0
Thu Apr 21 17:21:18 CEST 2016     DEBUG     JavaMelody classes loaded from: file:/usr/share/apache-tomcat-7.0.57/webapps/------/WEB-INF/lib/javamelody-core-1.59.0.jar
Thu Apr 21 17:21:18 CEST 2016     DEBUG     Host: ------
Thu Apr 21 17:21:18 CEST 2016     DEBUG     parameter defined: storage-directory=logs/monitoring
Thu Apr 21 17:21:18 CEST 2016     DEBUG     parameter defined: log=false
Thu Apr 21 17:21:18 CEST 2016     DEBUG     parameter defined: authorized-users=------
Thu Apr 21 17:21:18 CEST 2016     DEBUG     parameter defined: disabled=false
Thu Apr 21 17:21:18 CEST 2016     DEBUG     parameter defined: mail-session=MailSession
Thu Apr 21 17:21:18 CEST 2016     DEBUG     parameter defined: admin-emails=------
Thu Apr 21 17:21:18 CEST 2016     DEBUG     parameter defined: mail-periods=month
Thu Apr 21 17:21:18 CEST 2016     DEBUG     log listeners initialized
Thu Apr 21 17:21:18 CEST 2016     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/------]
Thu Apr 21 17:21:18 CEST 2016     DEBUG     job global listener initialized
Thu Apr 21 17:21:18 CEST 2016     DEBUG     counters initialized
Thu Apr 21 17:21:18 CEST 2016     DEBUG     counters data read from files in ../temp/logs/monitoring/------
Thu Apr 21 17:21:18 CEST 2016     DEBUG     collect task scheduled every 60s
Thu Apr 21 17:21:18 CEST 2016     DEBUG     first collect of data done
Thu Apr 21 17:21:18 CEST 2016     DEBUG     mail report for the month period scheduled with next execution date at Sun May 01 00:00:00 CEST 2016
Thu Apr 21 17:21:18 CEST 2016     DEBUG     mail reports scheduled for ------
Thu Apr 21 17:21:18 CEST 2016     DEBUG     Authorized user: admin
Thu Apr 21 17:21:18 CEST 2016     DEBUG     JavaMelody filter init done in 325 ms
Thu Apr 21 17:21:18 CEST 2016     DEBUG     struts interceptor initialized
Thu Apr 21 17:21:18 CEST 2016     DEBUG     struts interceptor initialized

But in Beta environment, when I try to see SQL stats, JavaMelody displays that no data exist and in his logs, we can see the error below :
"rebinding datasources failed, skipping"

JavaMelody 1.59.0 
 Debugging logs 
Tue Apr 19 16:35:54 CEST 2016     DEBUG     JavaMelody listener init started
Tue Apr 19 16:35:54 CEST 2016     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/------]
**Tue Apr 19 16:35:54 CEST 2016     DEBUG     rebinding datasources failed, skipping**
Tue Apr 19 16:35:54 CEST 2016     DEBUG     JavaMelody listener init done in 15 ms
Tue Apr 19 16:36:07 CEST 2016     DEBUG     JavaMelody filter init started
Tue Apr 19 16:36:07 CEST 2016     DEBUG     OS: Linux unknown, amd64/64
Tue Apr 19 16:36:07 CEST 2016     DEBUG     Java: Java(TM) SE Runtime Environment, 1.7.0_21-b11
Tue Apr 19 16:36:07 CEST 2016     DEBUG     Server: Apache
Tue Apr 19 16:36:07 CEST 2016     DEBUG     Webapp context: /------
Tue Apr 19 16:36:07 CEST 2016     DEBUG     JavaMelody version: 1.59.0
Tue Apr 19 16:36:07 CEST 2016     DEBUG     JavaMelody classes loaded from: file:/usr/share/apache-tomcat-7.0.40/webapps/------/WEB-INF/lib/javamelody-core-1.59.0.jar
Tue Apr 19 16:36:07 CEST 2016     DEBUG     Host: ------
Tue Apr 19 16:36:07 CEST 2016     DEBUG     parameter defined: storage-directory=logs/monitoring
Tue Apr 19 16:36:07 CEST 2016     DEBUG     parameter defined: log=false
Tue Apr 19 16:36:07 CEST 2016     DEBUG     parameter defined: authorized-users=------
Tue Apr 19 16:36:07 CEST 2016     DEBUG     parameter defined: disabled=false
Tue Apr 19 16:36:07 CEST 2016     DEBUG     parameter defined: mail-session=MailSession
Tue Apr 19 16:36:07 CEST 2016     DEBUG     parameter defined: admin-emails=------
Tue Apr 19 16:36:07 CEST 2016     DEBUG     parameter defined: mail-periods=month
Tue Apr 19 16:36:07 CEST 2016     DEBUG     log listeners initialized
Tue Apr 19 16:36:07 CEST 2016     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/------]
Tue Apr 19 16:36:07 CEST 2016     DEBUG     rebinding datasources failed, skipping
Tue Apr 19 16:36:07 CEST 2016     DEBUG     job global listener initialized
Tue Apr 19 16:36:07 CEST 2016     DEBUG     counters initialized
Tue Apr 19 16:36:07 CEST 2016     DEBUG     counters data read from files in ../temp/logs/monitoring/------
Tue Apr 19 16:36:07 CEST 2016     DEBUG     collect task scheduled every 60s
Tue Apr 19 16:36:07 CEST 2016     DEBUG     first collect of data done
Tue Apr 19 16:36:07 CEST 2016     DEBUG     mail report for the month period scheduled with next execution date at Sun May 01 00:00:00 CEST 2016
Tue Apr 19 16:36:07 CEST 2016     DEBUG     mail reports scheduled for ------
Tue Apr 19 16:36:07 CEST 2016     DEBUG     Authorized user: admin
Tue Apr 19 16:36:07 CEST 2016     DEBUG     JavaMelody filter init done in 592 ms
Tue Apr 19 16:36:08 CEST 2016     DEBUG     struts interceptor initialized
Tue Apr 19 16:36:08 CEST 2016     DEBUG     struts interceptor initialized
Wed Apr 20 00:00:07 CEST 2016     DEBUG     Obsolete files deleted. JavaMelody disk usage: 9817 KB
Thu Apr 21 00:00:07 CEST 2016     DEBUG     Obsolete files deleted. JavaMelody disk usage: 9876 KB

Could you tell me how I can fix this problem ? 

Thanks in advance for your response and your time.

**Comment by okohll** [comment]
I have this problem too. It started after upgrading my servlet app from Hibernate 4.1 to the latest Hibernate 5.1. A stack trace is below.

15:48:47.725 [localhost-startStop-1] DEBUG net.bull.javamelody - JavaMelody listener init started
15:48:47.734 [localhost-startStop-1] DEBUG net.bull.javamelody - datasources found in JNDI: [java:comp/env/jdbc/agileBaseSchema, java:comp/env/jdbc/agileBaseDa$
15:48:47.758 [localhost-startStop-1] DEBUG net.bull.javamelody - rebinding datasources failed, skipping
javax.naming.OperationNotSupportedException: Context is read only
        at org.apache.naming.NamingContext.checkWritable(NamingContext.java:962) ~[tomcat-catalina-7.0.68.jar:7.0.68]
        at org.apache.naming.NamingContext.bind(NamingContext.java:885) ~[tomcat-catalina-7.0.68.jar:7.0.68]
        at org.apache.naming.NamingContext.rebind(NamingContext.java:225) ~[tomcat-catalina-7.0.68.jar:7.0.68]
        at org.apache.naming.NamingContext.rebind(NamingContext.java:241) ~[tomcat-catalina-7.0.68.jar:7.0.68]
        at org.apache.naming.SelectorContext.rebind(SelectorContext.java:232) ~[tomcat-catalina-7.0.68.jar:7.0.68]
        at javax.naming.InitialContext.rebind(InitialContext.java:433) ~[na:1.8.0_03-Ubuntu]
        at net.bull.javamelody.JdbcWrapperHelper.rebindDataSource(JdbcWrapperHelper.java:119) ~[javamelody.jar:na]
        at net.bull.javamelody.JdbcWrapper.rebindDataSources(JdbcWrapper.java:453) ~[javamelody.jar:na]
        at net.bull.javamelody.SessionListener.contextInitialized(SessionListener.java:305) [javamelody.jar:na]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5068) [tomcat-catalina-7.0.68.jar:7.0.68]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5584) [tomcat-catalina-7.0.68.jar:7.0.68]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [tomcat-catalina-7.0.68.jar:7.0.68]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1572) [tomcat-catalina-7.0.68.jar:7.0.68]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1562) [tomcat-catalina-7.0.68.jar:7.0.68]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_03-Ubuntu]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_03-Ubuntu]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_03-Ubuntu]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_03-Ubuntu]
15:48:47.759 [localhost-startStop-1] DEBUG net.bull.javamelody - JavaMelody listener init done in 122 ms

**Comment by nicolasrosado** [comment]
After activated my log4j I saw the exception below. We can see that the datasource is in read only mode. 

2016-04-28 11:48:25,357 DEBUG [net.bull.javamelody.debug()] rebinding datasources failed, skipping
javax.naming.OperationNotSupportedException: Le Contexte est en lecture seule
	at org.apache.naming.NamingContext.checkWritable(NamingContext.java:962)
	at org.apache.naming.NamingContext.bind(NamingContext.java:886)
	at org.apache.naming.NamingContext.rebind(NamingContext.java:226)
	at org.apache.naming.NamingContext.rebind(NamingContext.java:242)
	at org.apache.naming.SelectorContext.rebind(SelectorContext.java:234)
	at javax.naming.InitialContext.rebind(InitialContext.java:427)
	at net.bull.javamelody.JdbcWrapperHelper.rebindDataSource(JdbcWrapperHelper.java:119)
	at net.bull.javamelody.JdbcWrapper.rebindDataSources(JdbcWrapper.java:453)
	at net.bull.javamelody.FilterContext.<init>(FilterContext.java:83)
	at net.bull.javamelody.MonitoringFilter.init(MonitoringFilter.java:112)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:262)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:107)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4746)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5399)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:977)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:542)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1462)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:792)
	at com.googlecode.psiprobe.Tomcat70ContainerAdaptor.checkChanges(Tomcat70ContainerAdaptor.java:103)
	at com.googlecode.psiprobe.Tomcat70ContainerAdaptor.installWar(Tomcat70ContainerAdaptor.java:117)
	at com.googlecode.psiprobe.controllers.deploy.UploadWarController.handleRequestInternal(UploadWarController.java:121)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
	at com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:54)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:511)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:581)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)

**Comment by evernat** [comment]
I have not reproduced the issue using Tomcat 7.0.68 but without hibernate.
Can you give the source of a simple project (using Maven if possible) to reproduce the issue?

**Comment by okohll** [comment]
Mine just started working again! Not sure what fixed it, possibly upgrading some third party libraries like some Apache Commons jars and the Apache HTTP Client, removing old versions. That's the only change I can think of on the server apart from some OS package updates

**Comment by evernat** [comment]
No response from the reporter so closing as invalid/incomplete.
