### ISSUE TITLE
Tomcat shutdown Exception in destroy filter named monitoring

### ISSUE THREAD

**Issue by vhochstein** [javamelody/javamelody#554]
I ve got a spring 4.1.x application using java 8 and spring 4.1.x
I ve included java melody 1.59.
When tomcat is going done, i see the following exception in catalina log file:

at net.bull.javamelody.MonitoringFilter.destroy(MonitoringFilter.java:137)
tries to destroy itself. In the process it tries to open spring-orm-4.1.4.RELEASE.jar, which is existing, but code is failing to open that file.

We are using tomcat hot deploy feature, which means war files are labeled with a version eg.
apps2mce##16.2.2.9   

Complete Error including StackTrace:

01-Jun-2016 07:40:12.311 SEVERE [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.core.ApplicationFilterConfig.release Failed to destroy the filter named [monitoring] of type [net.bull.javamelody.MonitoringFilter]
 java.lang.IllegalStateException: java.io.FileNotFoundException: /opt/appserv/prod/tomcat_bs03_180/webapps/apps2mce##16.2.2.9/WEB-INF/lib/spring-orm-4.1.4.RELEASE.jar (No such file or directory)
        at org.apache.catalina.webresources.JarResourceSet.getArchiveEntry(JarResourceSet.java:123)
        at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:260)
        at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:281)
        at org.apache.catalina.webresources.Cache.getResource(Cache.java:63)
        at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:216)
        at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:225)
        at org.apache.catalina.loader.WebappClassLoaderBase.findResourceInternal(WebappClassLoaderBase.java:2569)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2406)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:831)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1274)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1139)
        at net.bull.javamelody.FilterContext.destroy(FilterContext.java:372)
        at net.bull.javamelody.MonitoringFilter.destroy(MonitoringFilter.java:137)
        at org.apache.catalina.core.ApplicationFilterConfig.release(ApplicationFilterConfig.java:313)
        at org.apache.catalina.core.StandardContext.filterStop(StandardContext.java:4693)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5486)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224)
        at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:821)
        amelody.MonitoringFilter]
 java.lang.IllegalStateException: java.io.FileNotFoundException: /opt/appserv/prod/tomcat_bs03_180/webapps/apps2mce##16.2.2.9/WEB-INF/lib/spring-orm-4.1.4.RELEASE.jar (N
o such file or directory)

**Comment by evernat** [comment]
That line 372 in FilterContext is:
deregisterLogs();

Can you give the source of a simple project (using Maven if possible) to reproduce the issue?

**Comment by vhochstein** [comment]
Interesting that deregisterLogs is not part of the stack trace...
I m using logback 1.1.2 in my application.

Not sure if I will be able to provide a simple project showing this issue.

**Comment by evernat** [comment]
any news ?

**Comment by vhochstein** [comment]
I ve upgraded logback however that did not change anything

**Comment by evernat** [comment]
any news to be able to reproduce the issue or can we close this?

**Comment by evernat** [comment]
No response from the reporter, so closing as incomplete.
