### ISSUE TITLE
javamelody in spring-boot app can not start

### ISSUE THREAD

**Issue by keqingyuan** [javamelody/javamelody#583]
error log follow as
23:22:12.415 > ERROR o.a.c.c.C.[Tomcat].[localhost].[/] - Failed to destroy the filter named [javamelody] of type [net.bull.javamelody.MonitoringFilter]
java.lang.NoSuchMethodError: org.apache.log4j.Logger.removeAppender(Lorg/apache/log4j/Appender;)V
	at net.bull.javamelody.Log4JAppender.deregister(Log4JAppender.java:55)
	at net.bull.javamelody.FilterContext.deregisterLogs(FilterContext.java:415)
	at net.bull.javamelody.FilterContext.destroy(FilterContext.java:365)
	at net.bull.javamelody.MonitoringFilter.destroy(MonitoringFilter.java:139)
	at org.apache.catalina.core.ApplicationFilterConfig.release(ApplicationFilterConfig.java:313)
	at org.apache.catalina.core.StandardContext.filterStop(StandardContext.java:4722)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5517)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1423)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

my project has added sfl4j dependency.
javamelody version:1.58.0

**Comment by evernat** [comment]
As said in the SLF4J documentation:
http://www.slf4j.org/legacy.html#log4j-over-slf4j
when adding the log4j-over-slf4j dependency, you need to remove the log4j dependency.

Quote:
> To use log4j-over-slf4j in your own application, the first step is to locate and then to replace log4j.jar with log4j-over-slf4j.jar.

**Comment by cfstyle** [comment]
I have only jar file log4j-over-slf4j-1.7.9.jar.  and not in spring boot app, but I got the same issue.
the reason is that  log4j-over-slf4j-1.7.9.jar missing some of the implement javamelody need to rely on。

you need to update the version to log4j-over-slf4j-1.7.12.jar,  issue solved.
