### ISSUE TITLE
java.io.IOException: Stream closed on IBM AIX

### ISSUE THREAD

**Issue by Jeka21rus** [javamelody/javamelody#586]
Hi! I got problem when processing web service call. All work fine when I use Linux workstation, but when use IBM AIX (AIX 7.1.0.0, WebLogic Server 10.3.6.0.160719, JRE 1.7.0 IBM J9) I'm getting an exception:

`java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:174)
	at java.io.BufferedInputStream.reset(BufferedInputStream.java:447)
	at net.bull.javamelody.PayloadNameRequestWrapper.resetBufferedInputStream(PayloadNameRequestWrapper.java:138)
	at net.bull.javamelody.PayloadNameRequestWrapper.initialize(PayloadNameRequestWrapper.java:117)
	at net.bull.javamelody.MonitoringFilter.createRequestWrapper(MonitoringFilter.java:276)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:187)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:180)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:60)`

Do You have any ideas for workaround? Thanks

**Comment by evernat** [comment]
I do not know why it works on Linux but it does not work on IBM AIX (AIX 7.1.0.0, WebLogic Server 10.3.6.0.160719, JRE 1.7.0 IBM J9).
But I am not IBM support, so it's quite normal that I don't know IBM AIX or IBM J9 well.
The IBM support exists for cases like that, or not ?

**Comment by Jeka21rus** [comment]
Thanks for paying your attention anyway
