### ISSUE TITLE
JRobin static timer being cancelled wen application is added to centralized Collector Server on Wildfly 10

### ISSUE THREAD

**Issue by brazilrules** [javamelody/javamelody#587]
I setup javamelody in various applications that run on the same container, and use the Collector Server just to have all the info of the applications on the same address. When i was running it on JBoss 4.0.5GA everything worked fine, but as i switched the environment to Wildfly 10 when i add an application to the Collector Server, the following error starts to sprung every few seconds:

>14:15:52,407 WARN  [net.bull.javamelody] (pool-5-thread-4) exception while collecting data: java.lang.IllegalStateException: Timer already cancelled.: java.lang.IllegalStateException: Timer already cancelled.
	at java.util.Timer.sched(Timer.java:397)
	at java.util.Timer.schedule(Timer.java:248)
	at net.bull.javamelody.RrdNioBackend.<init>(RrdNioBackend.java:66)
	at net.bull.javamelody.RrdNioBackendFactory.open(RrdNioBackendFactory.java:84)
	at org.jrobin.core.RrdDb.<init>(Unknown Source)
	at org.jrobin.core.RrdDb.<init>(Unknown Source)
	at org.jrobin.core.RrdDbPool.requestRrdDb(Unknown Source)
	at net.bull.javamelody.JRobin.init(JRobin.java:191)
	at net.bull.javamelody.JRobin.<init>(JRobin.java:114)
	at net.bull.javamelody.JRobin.createInstance(JRobin.java:148)
	at net.bull.javamelody.Collector.getCounterJRobin(Collector.java:839)
	at net.bull.javamelody.Collector.collectJRobinValues(Collector.java:511)
	at net.bull.javamelody.Collector.collectJavaInformations(Collector.java:381)
	at net.bull.javamelody.Collector.collect(Collector.java:319)
	at net.bull.javamelody.Collector.collectWithoutErrors(Collector.java:305)
	at net.bull.javamelody.CollectorServer.collectForApplication(CollectorServer.java:197)
	at net.bull.javamelody.CollectorServer.collectForApplication(CollectorServer.java:167)
	at net.bull.javamelody.CollectorServer.collectForApplicationWithoutErrors(CollectorServer.java:125)
	at net.bull.javamelody.CollectorServer$2.run(CollectorServer.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

It seems something out of JRobin and Javamelody is messing with the thread inside the timer, because its `cancel()` is not being called if i am not wrong.

**Comment by evernat** [comment]
@brazilrules 
I do not reproduce the issue using WildFly 10.1.0.Final.

Do you reproduce the issue using a fresh install? What are exact steps by steps to reproduce the issue?
What version of the javamelody-collector-server do you use?

**Comment by evernat** [comment]
Any news ?

**Comment by evernat** [comment]
@brazilrules 
No response so closing.

By the way, you may want to share experiences and translate some labels in Brazilian Portuguese with Sandro.
See https://groups.google.com/forum/#!topic/javamelody/rfYkNodFqa4
