### ISSUE TITLE
openFile handle exeeded

### ISSUE THREAD

**Issue by clauswit** [javamelody/javamelody#592]
**Environment**
- We have an tomcat 8.0.35 on our development SUSE 12SP0 running.
- We used Java OpenJDK 7b101 and we changed now to Java IBM 1.7.1
- Java Melody is current release 1.62 and deployed as JAR
- I have configured my tomcat to monitor all web services via **web.xml** - I do not have configured every single web service.
- We have a AS400 Database connected via JNDI configured in every single web service
- There are some web services deployed which are used occasionally - no heavy load - no cronjobs or any other stuff which would monitor my web services (which I should see inside my **open http sessions**).
- We do have some other instances running (different web services like JIRA) without any problem

**Problem**
Lately we have installed a Jenkins server where our services will be deployed every night automatically if there are some code changes (done via ANT). We do every time a **undeploy / deploy** to get a new Version running.

(I guess) since then we get some open files issues where thousands of open files won't release. Then it looks like this:
```
589 x socket:[numberXXX]
Apache-Tomcat/temp/javamelody/database1/webservice5_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database2/webservice6_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/host-manager_thishostname/usedMemory.rrd
283x Apache-Tomcat/temp/javamelody/docs_thishostname/usedMemory.rrd
277x Apache-Tomcat/temp/javamelody/manager_thishostname/usedMemory.rrd
277x Apache-Tomcat/temp/javamelody/database1/webservice7_thishostname/usedMemory.rrd
283x Apache-Tomcat/temp/javamelody/database2/webservice2_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database3/webservice3_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database4/webservice4_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database4/webservice5_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database3/webservice6_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database1/webservice5_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database2/webservice6_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/host-manager_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/docs_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/manager_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database1/webservice1_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database2/webservice2_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database3/webservice3_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database4/webservice4_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database4/webservice5_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database3/webservice6_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database1/webservice5_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/database2/webservice6_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/_thishostname/usedMemory.rrd
Apache-Tomcat/temp/javamelody/host-manager_thishostname/usedMemory.rrd
```
Our maximum Open Files Limit was increased to 4096:8192 (soft:hard) - but I do not see an end if I change this again as it is still increasing

Although every time it seems to be the same file I get **every minute** a new block of Open Files of all my deployed web services.

I'd like to think that our automatically deployment process may do something wrong? But this will only happen some times a day and not every minute. Does anyone have some hints for us?

Here some Input from our Logs:

The problem started yesterday 12/13/2016 at 15:54 (Open File Handles ls-list) and I found the following in catalina.out

```
java.lang.Thread.run(Thread.java:745)
13-Dec-2016 15:52:55.172 WARNING [http-nio2-8888-exec-284] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [databaseX#WebserviceX] appears to have started a thread named [AS400 Read Daemon [
system:hostname;job:101523/QUSER/QZDASOINIT]] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.net.SocketInputStream.socketRead0(Native Method)
 java.net.SocketInputStream.read(SocketInputStream.java:152)
 java.net.SocketInputStream.read(SocketInputStream.java:122)
 com.ibm.as400.access.DataStream.readFromStream(DataStream.java:52)
 com.ibm.as400.access.ClientAccessDataStream.construct(ClientAccessDataStream.java:58)
 com.ibm.as400.access.AS400ThreadedServer.run(AS400ThreadedServer.java:357)
 java.lang.Thread.run(Thread.java:745)
13-Dec-2016 15:52:55.681 INFO [http-nio2-8888-exec-284] org.apache.catalina.startup.HostConfig.undeploy Undeploying context [/databaseX/WebserviceX]
13-Dec-2016 15:52:57.582 WARNING [javamelody] net.bull.javamelody.JavaLogger.warn exception while collecting data: java.lang.IllegalStateException: Timer already cancelled.
 java.lang.IllegalStateException: Timer already cancelled.
        at java.util.Timer.sched(Timer.java:397)
        at java.util.Timer.schedule(Timer.java:248)
        at net.bull.javamelody.RrdNioBackend.<init>(RrdNioBackend.java:66)
        at net.bull.javamelody.RrdNioBackendFactory.open(RrdNioBackendFactory.java:84)
        at org.jrobin.core.RrdDb.<init>(Unknown Source)
        at org.jrobin.core.RrdDb.<init>(Unknown Source)
        at org.jrobin.core.RrdDb.<init>(Unknown Source)
        at org.jrobin.core.RrdDbPool.requestRrdDb(Unknown Source)
        at net.bull.javamelody.JRobin.addValue(JRobin.java:337)
        at net.bull.javamelody.Collector.collectJRobinValues(Collector.java:511)
        at net.bull.javamelody.Collector.collectJavaInformations(Collector.java:381)
        at net.bull.javamelody.Collector.collect(Collector.java:319)
        at net.bull.javamelody.Collector.collectWithoutErrors(Collector.java:305)
        at net.bull.javamelody.Collector.collectLocalContextWithoutErrors(Collector.java:294)
        at net.bull.javamelody.FilterContext$CollectTimerTask.run(FilterContext.java:56)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

**Comment by clauswit** [comment]
I should add: We do undeploy / deploy to get a new Version running.

**Comment by clauswit** [comment]
Currently I am checking our Logs.

The problem started yesterday 12/13/2016 at 15:54 (Open File Handles ls-list) and I found the following in **catalina.out**

```

 java.lang.Thread.run(Thread.java:745)
13-Dec-2016 15:52:55.172 WARNING [http-nio2-8888-exec-284] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [databaseX#WebserviceX] appears to have started a thread named [AS400 Read Daemon [
system:hostname;job:101523/QUSER/QZDASOINIT]] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.net.SocketInputStream.socketRead0(Native Method)
 java.net.SocketInputStream.read(SocketInputStream.java:152)
 java.net.SocketInputStream.read(SocketInputStream.java:122)
 com.ibm.as400.access.DataStream.readFromStream(DataStream.java:52)
 com.ibm.as400.access.ClientAccessDataStream.construct(ClientAccessDataStream.java:58)
 com.ibm.as400.access.AS400ThreadedServer.run(AS400ThreadedServer.java:357)
 java.lang.Thread.run(Thread.java:745)
13-Dec-2016 15:52:55.681 INFO [http-nio2-8888-exec-284] org.apache.catalina.startup.HostConfig.undeploy Undeploying context [/databaseX/WebserviceX]
13-Dec-2016 15:52:57.582 WARNING [javamelody] net.bull.javamelody.JavaLogger.warn exception while collecting data: java.lang.IllegalStateException: Timer already cancelled.
 java.lang.IllegalStateException: Timer already cancelled.
        at java.util.Timer.sched(Timer.java:397)
        at java.util.Timer.schedule(Timer.java:248)
        at net.bull.javamelody.RrdNioBackend.<init>(RrdNioBackend.java:66)
        at net.bull.javamelody.RrdNioBackendFactory.open(RrdNioBackendFactory.java:84)
        at org.jrobin.core.RrdDb.<init>(Unknown Source)
        at org.jrobin.core.RrdDb.<init>(Unknown Source)
        at org.jrobin.core.RrdDb.<init>(Unknown Source)
        at org.jrobin.core.RrdDbPool.requestRrdDb(Unknown Source)
        at net.bull.javamelody.JRobin.addValue(JRobin.java:337)
        at net.bull.javamelody.Collector.collectJRobinValues(Collector.java:511)
        at net.bull.javamelody.Collector.collectJavaInformations(Collector.java:381)
        at net.bull.javamelody.Collector.collect(Collector.java:319)
        at net.bull.javamelody.Collector.collectWithoutErrors(Collector.java:305)
        at net.bull.javamelody.Collector.collectLocalContextWithoutErrors(Collector.java:294)
        at net.bull.javamelody.FilterContext$CollectTimerTask.run(FilterContext.java:56)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

(We use JNDI and a AS400 System i database)

**Comment by clauswit** [comment]
We have updated to 8.0.39 still same error.

**Comment by evernat** [comment]
I have committed a change which may help in exceptional case when undeploying, given that you have a lot of monitored webapps and many undeploy / deploy.
Here is the commit: f4f7b62

You can download a new build including the fix at:
https://javamelody.ci.cloudbees.com/job/javamelody/ws/javamelody-core/javamelody.jar

Let us know if it works for you. Thanks.

**Comment by clauswit** [comment]
Since I installed your Fixed Jar - we seem to have no new open files (we do not have any open file with a name `usedMemory.rrd`). I will get a final result in mid January as we will not work for two weeks while Christmas.

**Comment by evernat** [comment]
Ok, good.
You can confirm the final result here in january.
Thanks Claus

**Comment by clauswit** [comment]
I checked our current Setup and I do **not have any open file** anymore. So I guess any open file before was a failure. **Thumbs up**. Problem solved.
