### ISSUE TITLE
Javamelody 1.62 on payara 4.1.1.164

### ISSUE THREAD

**Issue by tkernstock** [javamelody/javamelody#594]
2016-12-19 21:07:05,219 WARN  [http-thread-pool(2)] javax.enterprise.web - StandardWrapperValve[default]: Servlet.service() for servlet default threw exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -27
	at java.lang.String.substring(String.java:1967)
	at net.bull.javamelody.I18N.writeTo(I18N.java:181)
	at net.bull.javamelody.I18N.writelnTo(I18N.java:198)
	at net.bull.javamelody.HtmlAbstractReport.writeln(HtmlAbstractReport.java:110)
	at net.bull.javamelody.HtmlJavaInformationsReport.writeServerInfoAndContextPath(HtmlJavaInformationsReport.java:222)
	at net.bull.javamelody.HtmlJavaInformationsReport.writeDetails(HtmlJavaInformationsReport.java:173)
	at net.bull.javamelody.HtmlJavaInformationsReport.toHtml(HtmlJavaInformationsReport.java:82)
	at net.bull.javamelody.HtmlCoreReport.toHtml(HtmlCoreReport.java:215)
	at net.bull.javamelody.HtmlReport.toHtml(HtmlReport.java:76)
	at net.bull.javamelody.HtmlController.doHtml(HtmlController.java:100)
	at net.bull.javamelody.MonitoringController.doCompressedHtml(MonitoringController.java:279)
	at net.bull.javamelody.MonitoringController.doReportCore(MonitoringController.java:233)
	at net.bull.javamelody.MonitoringController.doReport(MonitoringController.java:208)
	at net.bull.javamelody.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:170)
	at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:351)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:169)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:745)

**Comment by evernat** [comment]
this is fixed by 7cd896907c325cedaedd1b44ea00ce07159733e9.
Thanks for the issue.
