### ISSUE TITLE
SQL Monitoring not working on Payara

### ISSUE THREAD

**Issue by tkernstock** [javamelody/javamelody#596]
Deploying melody on Payara server results in Errormessages and non functional SQL monitoring.

When starting the server I can find the following entries in the serverlog:

```
[2016-12-19T19:03:00.233+0100] [Payara 4.1] [INFO] [] [] [tid: _ThreadID=14 _ThreadName=RunLevelControllerThread-1482170549777] [timeMillis: 1482170580233] [levelValue: 800] [[
  19:03:00.232 [RunLevelControllerThread-1482170549777]  DEBUG net.bull.javamelody - datasources found in JNDI: [jdbc/TestDB_uncached, jdbc/TestDB, jdbc/TestDB_uncached__pm]

[Payara 4.1] [SEVERE] [AS-NAMING-00006] [org.glassfish.naming] [tid: _ThreadID=14 _ThreadName=RunLevelControllerThread-1482170549777] [timeMillis: 1482170580234] [levelValue: 1000] [[
  Exception in NamingManagerImpl copyMutableObject(): {0}
java.io.NotSerializableException: net.bull.javamelody.JdbcWrapper
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) .......

[2016-12-19T19:03:00.238+0100] [Payara 4.1] [INFO] [] [] [tid: _ThreadID=14 _ThreadName=RunLevelControllerThread-1482170549777] [timeMillis: 1482170580238] [levelValue: 800] [[
  19:03:00.238 [RunLevelControllerThread-1482170549777] DEBUG net.bull.javamelody - rebinding datasources failed, skipping
java.lang.RuntimeException: Cant copy Serializable object:
    at com.sun.enterprise.naming.util.NamingUtilsImpl.makeCopyOfObject(NamingUtilsImpl.java:131)
    at com.sun.enterprise.naming.impl.LocalSerialContextProviderImpl.rebind(LocalSerialContextProviderImpl.java:108) ........
```

**Comment by tkernstock** [comment]
Hi Evernat,
I hope the 2 changes in my pull request are usefull. I have deployed them as snaphot version on a production server and everything works fine. 

By the way, merci beaucoup for this really usefull piece of software. 

br
Thomas

**Comment by tkernstock** [comment]
Hi Evernat,
I hope the 2 changes in my pull request are usefull. I have deployed them as snaphot version on a production server and everything works fine.

By the way, merci beaucoup for this really usefull piece of software.

br
Thomas

**Comment by evernat** [comment]
PR merged, thanks.
