### ISSUE TITLE
RRD files - http://javascriptrrd.sourceforge.net/index.html

### ISSUE THREAD

**Issue by s-a-j42** [javamelody/javamelody#610]
Hi, I JavaMelody is great. Have you come across javascriptrrd? It is very good at creating interactive graphs from RRD files.

Are JavaMelody rrd files standard rrd? I've tried setting up javascriptrrd graphs but I am getting "wrong magic id". I've used javascriptrrd successfully with other rrd files a few times.

Thanks

**Comment by evernat** [comment]
I did not know javascriptrrd, thanks.
For reference, here is another one which can display graphs from RRD files: rrdgraph-js, https://github.com/terenn/rrdgraph-js which uses D3.js instead of Flot charts.
I suppose that the 2 JS tools expect RRD files format like with [RRDTool](http://www.rrdtool.org/).

And the cause of the error is probably because javamelody uses jrobin 1.5.9, which does not use the same rrd files format as the original RRDTool. In fact, the original RRDTool itself does not use a unique "standard" format: the RRD files format of RRDTool is not portable: http://oss.oetiker.ch/rrdtool-trac/wiki/PortableRrdFormat
For comparison, RRD files from javamelody / jrobin are portable between HW/OS.

But there exists a tool called jrrd which is supposed to convert jrobin rrd files to xml and then xml to rrdtool rrd files:
See https://wiki.opennms.org/wiki/Converting_JRobin_to_RRDtool_file_format
and source at https://github.com/OpenNMS/opennms/tree/develop/opennms-tools/jrb-to-rrd-converter
There is a similar jrobin rrd to xml tool inside the the jrobin-1.5.9.jar file:
http://grepcode.com/file/repo1.maven.org/maven2/org.jrobin/jrobin/1.5.9/org/jrobin/core/jrrd/Main.java

You may try the to convert your rrd files to see if it works better with javascript-rrd or rrdgraph-js.
Or better for us, you may try to patch javascript-rrd or rrdgraph-js to make them understand the jrobin rrd files format. That would be great.

**Comment by goldyliang** [comment]
Possibly the rrdgraph-js can be enhanced to support RRD files generated with JRobin then it can be integrated in javamelody easily?

I posted a new issue in rrdgraph project:
https://github.com/terenn/rrdgraph-js/issues/15

**Comment by ratherDashing** [comment]
I've tried every rrd tool on the planet including the ones listed by evernat but every single one is saying that the javamelody rrd files are not in a proper format.  what tool does every one use to read these files?  Every single rrd file is 34k which is suspicious as well.

**Comment by evernat** [comment]
@ratherDashing 
as written above, javamelody uses jrobin 1.5.9 to write rrd files

**Comment by ratherDashing** [comment]
Problem I'm experiencing is that jrobin 1.5.9 doesn't seem to be able to parse the .rrd files that are generated.

java -cp jrobin-1.5.9.jar org.jrobin.core.jrrd.Main systemCpuLoad.rrd
java.io.IOException: Invalid RRD file
        at org.jrobin.core.jrrd.RRDFile.initDataLayout(RRDFile.java:58)
        at org.jrobin.core.jrrd.RRDFile.<init>(RRDFile.java:40)
        at org.jrobin.core.jrrd.RRDatabase.<init>(RRDatabase.java:59)
        at org.jrobin.core.jrrd.RRDatabase.<init>(RRDatabase.java:47)
        at org.jrobin.core.jrrd.Main.<init>(Main.java:27)
        at org.jrobin.core.jrrd.Main.main(Main.java:56)

**Comment by BuildMonkey** [comment]
I agree with ratherDashing. I am getting the same error when I try to read one of the rrd files, usedMemor.rrd

 $ java -cp jrobin-1.5.9.jar org.jrobin.core.jrrd.Main usedMemory.rrd 
java.io.IOException: Invalid RRD file
	at org.jrobin.core.jrrd.RRDFile.initDataLayout(RRDFile.java:58)
	at org.jrobin.core.jrrd.RRDFile.<init>(RRDFile.java:40)
	at org.jrobin.core.jrrd.RRDatabase.<init>(RRDatabase.java:59)
	at org.jrobin.core.jrrd.RRDatabase.<init>(RRDatabase.java:47)
	at org.jrobin.core.jrrd.Main.<init>(Main.java:27)
	at org.jrobin.core.jrrd.Main.main(Main.java:56)

**Comment by evernat** [comment]
@BuildMonkey @ratherDashing 
[JRobin 1.5.9](https://repo1.maven.org/maven2/org/jrobin/jrobin/1.5.9/jrobin-1.5.9.jar) works when used as intended (but not compatible that way with Java 9 or later). You can use commands in the included jrobin console: `java -jar jrobin-1.5.9.jar`, with [RRDTool](https://oss.oetiker.ch/rrdtool/doc/index.en.html) 1.0.x like syntax. Some commands, for example:
```
last usedMemory.rrd
info usedMemory.rrd
fetch usedMemory.rrd AVERAGE
dump usedMemory.rrd
etc
```
or in your own java program:
```java
double lastValue = new org.jrobin.core.RrdDb(new File("usedMemory.rrd")).getLastDatasourceValue("usedMemory");
```
Attached is a zip with a sample usedMemory.rrd file: 
[usedMemory.rrd.zip](https://github.com/javamelody/javamelody/files/1684694/usedMemory.rrd.zip)

**Comment by evernat** [comment]
I have also added dump as xml or txt from the browser for the next release (1.83), see [doc](https://github.com/javamelody/javamelody/wiki/ExternalAPI#dump-graph-as-xml-or-txt). A snapshot build is at http://javamelody.org/downloads/javamelody-core-1.83.0-SNAPSHOT.jar
