### ISSUE TITLE
JPA Monitoring not possible with Hibernate Multitenancy 

### ISSUE THREAD

**Issue by b0m0x** [javamelody/javamelody#624]
When using JavaMelody with JPA:

`<provider>net.bull.javamelody.JpaPersistence</provider>`

Hibernate can not load the connection provider:

```
Caused by: org.hibernate.service.spi.ServiceException: Unable to locate specified multi-tenant connection provider [org.example.multitenancy.ConnectionProvider]
	at org.hibernate.engine.jdbc.connections.internal.MultiTenantConnectionProviderInitiator.initiateService(MultiTenantConnectionProviderInitiator.java:78)
	at org.hibernate.engine.jdbc.connections.internal.MultiTenantConnectionProviderInitiator.initiateService(MultiTenantConnectionProviderInitiator.java:28)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:88)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:234)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:208)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:149)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:66)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:88)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:234)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:208)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:217)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:352)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:111)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:847)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:874)
	at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:135)
	at net.bull.javamelody.JpaPersistence.createContainerEntityManagerFactory(JpaPersistence.java:131)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.createContainerEntityManagerFactory(PersistenceUnitServiceImpl.java:318)
	at org.jboss.as.jpa.service.PersistenceUnitSe
```

Tested on WildFly 10. Adding the explicit original provider hint does not help:
`<property name="hibernate.jdbc.factory_class" value="net.bull.javamelody.HibernateBatcherFactory" />`

**Comment by evernat** [comment]
First, you don't need:
```xml
<property name="hibernate.jdbc.factory_class" 
	value="net.bull.javamelody.HibernateBatcherFactory" />
```
Then, have you tried the following?
```xml
<provider>net.bull.javamelody.JpaPersistence</provider>
<properties>
	<property name="net.bull.javamelody.jpa.provider"
		value="org.example.multitenancy.ConnectionProvider" />
	...
</properties>
```

**Comment by evernat** [comment]
any news?

**Comment by evernat** [comment]
No response from the reporter, so closing as invalid / incomplete.
