### ISSUE TITLE
Exception causes log noise in Jira

### ISSUE THREAD

**Issue by josmers** [javamelody/javamelody#636]
Switching to Jira 7.3.0 and Melody jira-confluence-javamelody-1.65.0.jar brings up exceptions in the log file atlassian-jira.log. This occur up to 100 times a day.

Actions planned: We will try out jira-confluence-javamelody-1.67.0.jar in test environment to check if the exception is still there.

2017-06-02 14:48:37,242 ajp-nio-8010-exec-101 ERROR [o.a.c.c.C.[.[localhost].[/].[default]] Servlet.service() for servlet [default] in context with path [] threw exception
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:456)
at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120)
at com.atlassian.jira.web.filters.steps.senderror.CaptureSendErrorMessageResponseWrapper.sendError(CaptureSendErrorMessageResponseWrapper.java:26)
at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120)
at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120)
at net.bull.javamelody.FilterServletResponseWrapper.sendError(FilterServletResponseWrapper.java:90)
at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120)
at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120)
at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120)
... 1 filtered
at com.atlassian.seraph.auth.DefaultAuthenticator.getUserFromBasicAuthentication(DefaultAuthenticator.java:555)
at com.atlassian.crowd.integration.seraph.CrowdAuthenticator.checkAuthenticated(CrowdAuthenticator.java:309)
at com.atlassian.crowd.integration.seraph.CrowdAuthenticator.getUser(CrowdAuthenticator.java:429)
at com.atlassian.jira.security.login.SSOSeraphAuthenticator.getUser(SSOSeraphAuthenticator.java:63)
... 1 filtered
at com.atlassian.jira.security.JiraSecurityFilter.doFilter(JiraSecurityFilter.java:117)
... 16 filtered
at com.atlassian.plugins.rest.module.servlet.RestSeraphFilter.doFilter(RestSeraphFilter.java:37)
... 20 filtered
at com.atlassian.jira.servermetrics.CorrelationIdPopulatorFilter.doFilter(CorrelationIdPopulatorFilter.java:30)
... 10 filtered
at com.atlassian.web.servlet.plugin.request.RedirectInterceptingFilter.doFilter(RedirectInterceptingFilter.java:21)
... 4 filtered
at com.atlassian.web.servlet.plugin.LocationCleanerFilter.doFilter(LocationCleanerFilter.java:36)
... 7 filtered
at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:220)
at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:197)
at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:85)
at net.bull.javamelody.JiraMonitoringFilter.doFilter(JiraMonitoringFilter.java:128)
... 25 filtered
at com.atlassian.jira.servermetrics.MetricsCollectorFilter.doFilter(MetricsCollectorFilter.java:25)
... 28 filtered
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)

**Comment by evernat** [comment]
I am not sure that the issue is related to the javamelody monitoring plugin.
Does it still occur after disabling the plugin?
Does it still occur on a fresh install of JIRA 7.3.0 with this only one plugin?

**Comment by josmers** [comment]
The errors occur in a productive environment where I cannot disable the melody plugin. I don't know how to reproduce this errors in our test or dev environment. Any idea how to track down this issue is greatly appreciated.

**Comment by josmers** [comment]
I'm in contact with Atlassian as well to investigate further. We need suggestions for logging or other methods from the experts to trace the cause of this exception.

**Comment by evernat** [comment]
You can get the URL(s) called and causing the exceptions. It could help finding the root cause.

For that, open the javamelody monitoring report and go down to the "Statistics http system errors" (`http://.../monitoring#error`) then click on "Last errors" and find the exceptions you want in the list.
On the left of the list, it will display the Date/times of the exceptions and the URL(s) causing the exceptions.

You can also look at the "Statistics system error logs" (`http://.../monitoring#log`) then click on "Last errors" and see if there are other exceptions logged as warnings related to the problem at the same date/times.

**Comment by josmers** [comment]
Hello evernat,
unfortunately the error is not within the last 100 errors. I cannot see the request URL. I will try later.

Cheers,
Jan
![image](https://user-images.githubusercontent.com/6507641/27178570-083b1a7e-51cb-11e7-9f55-54a1c0dbc37a.png)

**Comment by josmers** [comment]
I cannot find the exception along the last 100 errors. Is there the possibility to see more than 100 entries? 1000 would probably be enough.
Our next update is scheduled for 12.07. we plan some changes that might help in solving this issue.

**Comment by evernat** [comment]
Sorry, it's not possible to have more than 100 entries in the last errors.
But, at the top of the monitoring reports, you may choose a "Custom period" and display the report day by day. So, you may have a chance (or not) to find your exception in the statistics for one of the days.

**Comment by josmers** [comment]
Thanks for your advise. I was able to find the exception together with the called URL. "Custom period" is a very helpful feature. We will investigate further. I'll update this issue when new information is available.

6/14/17 5:15:23 PM	/rest/projects/1.0/project/BSDRNA/lastVisited ajax PUT	
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed

**Comment by josmers** [comment]
In the meantime we Updated to Jira 7.3.6. Tomcat work directory was cleaned up. We try to get more information about this issue by installing the Thready plugin. Still investigating...

**Comment by evernat** [comment]
Any news?

**Comment by josmers** [comment]
Evernat, thanks for your follow up. We were still not able to reproduce this issue in a non productive Jira instance. No user impact is known at the moment. Further investigation means modifying the system and impacting users. We decided to leave things as they are for the moment. However new facts may put this issue on the agenda again.
I believe as well as you already stated this issue is most likely not related to java melody. Java melody moreover was helpful to get hints about the issue. Please close this ticket and thank you very much for your support. Have a nice day & rgds Jan

**Comment by evernat** [comment]
ok, thanks for the info
