### ISSUE TITLE
Deployment Problems in Weblogic

### ISSUE THREAD

**Issue by mdobrovnik** [javamelody/javamelody#639]
Hi,

let me first thank you for javamelody at large, a nice and helpful tool.

we are using javamelody embedded in  a war under WEB-INF/lib. 
After upgrading from javamelody 1.59 to 1.67, we have a problem to deploy it under weblogic 12.1.2, getting _errors_/exceptions like

`
<Error> <Deployer> <dev-ead> <wfm> <[ACTIVE] ExecuteThread: '18' for queue: 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <> <1497281882993> <BEA-149205> <Failed to initialize the app
lication "wfm" due to error weblogic.application.ModuleException: java.lang.ClassNotFoundException: org.hibernate.jdbc.NonBatchingBatcher
weblogic.application.ModuleException: java.lang.ClassNotFoundException: org.hibernate.jdbc.NonBatchingBatcher
        at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:114)
        at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
        at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:172)
        at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:167)
        at weblogic.application.utils.StateMachineDriver$ParallelChange.run(StateMachineDriver.java:80)
        at weblogic.work.ContextWrap.run(ContextWrap.java:40)
        at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:550)
`
thanks to the hints  mentioned in issue #634, we were able to deploy it by **removing** beans.xml 
from META-INF (introducting the beans-discovery-mode="annotated" attribute did not work; 
weblogic 12.1.2 is cdi 1.0, which does not allow this attribute).

Also the 1.68-SNAPSHOT of javamelody did not work.

**Changing from weblogic 12.1.2 to 12.2.1.2.0** (which may not be possible for the target platform), we got the following results:

deployment with 1.67 gets the following _warning_:
`> <Warning> <Deployer> <BEA-149078> <Stack trace for message 149004
weblogic.management.DeploymentException: CDI deployment failure:org/hibernate/jdbc/NonBatchingBatcher
        at com.oracle.injection.integration.CDIAppDeploymentExtension.initCdi(CDIAppDeploymentExtension.java:95)
        at com.oracle.injection.integration.CDIAppDeploymentExtension.activate(CDIAppDeploymentExtension.java:43)
        at weblogic.application.internal.flow.AppDeploymentExtensionFlow.activate(AppDeploymentExtensionFlow.java:39)
        at weblogic.application.internal.BaseDeployment$2.next(BaseDeployment.java:750)
        at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
        Truncated. see log file for complete stacktrace
Caused By: java.lang.ClassNotFoundException: org.hibernate.jdbc.NonBatchingBatcher
        at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:1026)
        at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:987)
        at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:83)
        at weblogic.utils.classloaders.GenericClassLoader.doFindClass(GenericClassLoader.java:608)
        at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:540)
`

which later prevents the startup of the webapp.

Using 1.68-snapshot seems to be fine (app starts up), but still gets warnings:

`<Warning> <org.jboss.weld.Bootstrap> <BEA-000000> <WELD-001208: Error when validating zip:C:/Oracle/Middleware/Oracle_Home/user_projects/domains/wl_server/servers/AdminServer/tmp/_WL_user/ep90168/hqkbe8/war/WEB-INF/lib/javamelody-core-1.68.0-SNAPSHOT.jar!/META-INF/beans.xml@4 against xsd. cvc-complex-type.3.2.2: Attribut 'bean-discovery-mode' darf nicht in Element 'beans' vorkommen.>`

Looking into this, i became aware that the namespaces have changed for cdi1.1/j2ee 7
(c.f. [https://dzone.com/articles/java-ee-7-deployment](url))

incorporating the new namespace in beans.xml leads to

`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
	bean-discovery-mode="annotated">
	<interceptors>
		<class>net.bull.javamelody.MonitoringCdiInterceptor</class>
		<class>net.bull.javamelody.MonitoringAsynchronousCdiInterceptor</class>
	</interceptors>
</beans>`

then the app deploys and starts under weblogic 12.2.1.2.0 without any glitch, so maybe this is
a proper change for the javamelody master, too.

For the earlier weblogic version (12.1.2), we are still bound to remove beans.xml at all?
Any other suggestions?

kind regards,

**Comment by evernat** [comment]
I have committed the new headers in beans.xml (9b91471). Thanks.
For weblogic 12.1.2, I think that you need to remove beans.xml indeed, or you can step back to javamelody-core version 1.65.0.

**Comment by softashu** [comment]
Almost similar problem is with TomEE
--------------------------------------------

Server version: Apache Tomcat/7.0.37
Server built:   Feb 12 2013 10:44:14
Server number:  7.0.37.0
OS Name:        Windows 7
OS Version:     6.1
Architecture:   amd64
JVM Version:    1.8.0_72-b15
JVM Vendor:     Oracle Corporation
-------------------------------------------------
Exception we are getting is 

ALLVARLIG: CDI Beans module deployment failed
org.apache.webbeans.exception.WebBeansConfigurationException: Interceptor class : net.bull.javamelody.MonitoringAsynchronousCdiInterceptor must have at least one @InterceptorBindingType
	at org.apache.openejb.cdi.CdiScanner.init(CdiScanner.java:127)
	at org.apache.openejb.cdi.OpenEJBLifecycle.startApplication(OpenEJBLifecycle.java:200)
	at org.apache.openejb.cdi.ThreadSingletonServiceImpl.initialize(ThreadSingletonServiceImpl.java:167)
	at org.apache.openejb.cdi.CdiBuilder.build(CdiBuilder.java:43)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:723)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:546)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1128)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1033)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:124)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5179)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:977)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1655)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


Please suggest resolving 

Thanks
Ashutosh
