### ISSUE TITLE
Not generating any bean definitions from net.bull.javamelody.*

### ISSUE THREAD

**Issue by GururajMunnalli** [javamelody/javamelody#640]
HI,

I tried javamelody with jboss 7.1.1

In web.xml I added the MonitoringFilter and SessionListener as given User Guide
net.bull.javamelody.MonitoringFilter
net.bull.javamelody.SessionListener

Then I added jars javamelody.jar and jrobin-1.5.9.jar
I am able to display output, but SQL monitoring is not working.

[org.jboss.weld.deployer] (MSC service thread 1-5) JBAS016008: Starting weld service for deployment 
[org.jboss.weld.ClassLoading] (MSC service thread 1-5) WELD-000119 Not generating any bean definitions from net.bull.javamelody.PdfDatabaseInformationsReport because of underlying class loading error
[org.jboss.weld.ClassLoading] (MSC service thread 1-5) catching: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.PdfDatabaseInformationsReport
	at org.jboss.weld.resources.ClassTransformer.loadClass(ClassTransformer.java:152) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:86) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.bootstrap.BeanDeployer.addClasses(BeanDeployer.java:115) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.bootstrap.BeanDeployment.createBeans(BeanDeployment.java:171) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:336) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.as.weld.WeldContainer.start(WeldContainer.java:82) [jboss-as-weld-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.as.weld.services.WeldService.start(WeldService.java:76) [jboss-as-weld-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_71]
Caused by: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.PdfAbstractTableReport
	at org.jboss.weld.resources.ClassTransformer.loadClass(ClassTransformer.java:152) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.introspector.jlr.WeldClassImpl.<init>(WeldClassImpl.java:139) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.introspector.jlr.WeldClassImpl.of(WeldClassImpl.java:118) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.resources.ClassTransformer$TransformTypeToWeldClass.apply(ClassTransformer.java:49) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.resources.ClassTransformer$TransformTypeToWeldClass.apply(ClassTransformer.java:40) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:355)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:184)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:153)
	at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:69)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingMapAdapter.get(ComputingConcurrentHashMap.java:393)
	at org.jboss.weld.resources.ClassTransformer.loadClass(ClassTransformer.java:149) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	... 11 more
Caused by: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.PdfAbstractReport
	at org.jboss.weld.resources.ClassTransformer.loadClass(ClassTransformer.java:152) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.introspector.jlr.WeldClassImpl.<init>(WeldClassImpl.java:139) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.introspector.jlr.WeldClassImpl.of(WeldClassImpl.java:118) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.resources.ClassTransformer$TransformTypeToWeldClass.apply(ClassTransformer.java:49) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.resources.ClassTransformer$TransformTypeToWeldClass.apply(ClassTransformer.java:40) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:355)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:184)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:153)
	at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:69)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingMapAdapter.get(ComputingConcurrentHashMap.java:393)
	at org.jboss.weld.resources.ClassTransformer.loadClass(ClassTransformer.java:149) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	... 21 more
Caused by: java.lang.NoClassDefFoundError: Lcom/lowagie/text/Document;
	at java.lang.Class.getDeclaredFields0(Native Method) [rt.jar:1.7.0_71]
	at java.lang.Class.privateGetDeclaredFields(Class.java:2499) [rt.jar:1.7.0_71]
	at java.lang.Class.getDeclaredFields(Class.java:1811) [rt.jar:1.7.0_71]
	at org.jboss.weld.util.reflection.SecureReflections$4.work(SecureReflections.java:102) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.util.reflection.SecureReflections$4.work(SecureReflections.java:99) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:52) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.util.reflection.SecureReflectionAccess.runAndWrap(SecureReflectionAccess.java:63) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.util.reflection.SecureReflections.getDeclaredFields(SecureReflections.java:99) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.introspector.jlr.WeldClassImpl.<init>(WeldClassImpl.java:153) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.introspector.jlr.WeldClassImpl.of(WeldClassImpl.java:118) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.resources.ClassTransformer$TransformTypeToWeldClass.apply(ClassTransformer.java:49) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at org.jboss.weld.resources.ClassTransformer$TransformTypeToWeldClass.apply(ClassTransformer.java:40) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:355)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:184)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:153)
	at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:69)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingMapAdapter.get(ComputingConcurrentHashMap.java:393)
	at org.jboss.weld.resources.ClassTransformer.loadClass(ClassTransformer.java:149) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
	... 31 more
Caused by: java.lang.ClassNotFoundException: com.lowagie.text.Document from [Module "deployment.war:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
	... 49 more

Too many Errors :
Failed to define class net.bull.javamelody.HibernateBatcherFactory$HibernateBatchingBatcher in Module "deployment.war:main" from Service Module Loader: java.lang.LinkageError: Failed to link net/bull/javamelody/HibernateBatcherFactory$HibernateBatchingBatcher (Module "deployment.war:main" from Service Module Loader)
Caused by: java.lang.NoClassDefFoundError: org/hibernate/jdbc/BatchingBatcher
Caused by: java.lang.ClassNotFoundException: org.hibernate.jdbc.BatchingBatcher from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.HibernateBatcherFactory$HibernateBatchingBatcher because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: java.lang.ClassNotFoundException: net.bull.javamelody.HibernateBatcherFactory$HibernateBatchingBatcher from [Module "deployment.war:main" from Service Module Loader]
Caused by: java.lang.ClassNotFoundException: net.bull.javamelody.HibernateBatcherFactory$HibernateBatchingBatcher from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.CounterResponseStream because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.CounterResponseStream
Caused by: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.FilterServletOutputStream
Caused by: java.lang.NoClassDefFoundError: javax/servlet/WriteListener
Caused by: java.lang.ClassNotFoundException: javax.servlet.WriteListener from [Module "deployment..war:main" from Service Module Loader]
Failed to define class net.bull.javamelody.LogbackAppender in Module "deployment.war:main" from Service Module Loader: java.lang.LinkageError: Failed to link net/bull/javamelody/LogbackAppender (Module "deployment..war:main" from Service Module Loader)
Caused by: java.lang.NoClassDefFoundError: ch/qos/logback/core/UnsynchronizedAppenderBase
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.UnsynchronizedAppenderBase from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.LogbackAppender because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: java.lang.ClassNotFoundException: net.bull.javamelody.LogbackAppender from [Module "deployment.war:main" from Service Module Loader]
Caused by: java.lang.ClassNotFoundException: net.bull.javamelody.LogbackAppender from [Module "deployment.war:main" from Service Module Loader]
Failed to define class net.bull.javamelody.Log4J2Appender in Module "deployment.war:main" from Service Module Loader: java.lang.LinkageError: Failed to link net/bull/javamelody/Log4J2Appender (Module "deployment.war:main" from Service Module Loader)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/appender/AbstractAppender
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.appender.AbstractAppender from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.Log4J2Appender because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: java.lang.ClassNotFoundException: net.bull.javamelody.Log4J2Appender from [Module "deployment.war:main" from Service Module Loader]
Caused by: java.lang.ClassNotFoundException: net.bull.javamelody.Log4J2Appender from [Module "deployment.war:main" from Service Module Loader]
Failed to define class net.bull.javamelody.HibernateBatcherFactory in Module "deployment.war:main" from Service Module Loader: java.lang.LinkageError: Failed to link net/bull/javamelody/HibernateBatcherFactory (Module "deployment.war:main" from Service Module Loader)
Caused by: java.lang.NoClassDefFoundError: org/hibernate/jdbc/BatcherFactory
Caused by: java.lang.ClassNotFoundException: org.hibernate.jdbc.BatcherFactory from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.HibernateBatcherFactory because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: java.lang.ClassNotFoundException: net.bull.javamelody.HibernateBatcherFactory from [Module "deployment.war:main" from Service Module Loader]
Caused by: java.lang.ClassNotFoundException: net.bull.javamelody.HibernateBatcherFactory from [Module "deployment.war:main" from Service Module Loader]
Failed to define class net.bull.javamelody.MonitoringGuiceModule in Module "deployment.war:main" from Service Module Loader: java.lang.LinkageError: Failed to link net/bull/javamelody/MonitoringGuiceModule (Module "deployment.war:main" from Service Module Loader)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/AbstractModule
Caused by: java.lang.ClassNotFoundException: com.google.inject.AbstractModule from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.MonitoringGuiceModule because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: java.lang.ClassNotFoundException: net.bull.javamelody.MonitoringGuiceModule from [Module "deployment.war:main" from Service Module Loader]
Caused by: java.lang.ClassNotFoundException: net.bull.javamelody.MonitoringGuiceModule from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.CompressionResponseStream because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.CompressionResponseStream
Caused by: java.lang.NoClassDefFoundError: javax/servlet/WriteListener
Caused by: java.lang.ClassNotFoundException: javax.servlet.WriteListener from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.PayloadNameRequestWrapper$1 because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.PayloadNameRequestWrapper$1
Caused by: java.lang.NoClassDefFoundError: javax/servlet/ReadListener
Caused by: java.lang.ClassNotFoundException: javax.servlet.ReadListener from [Module "deployment.war:main" from Service Module Loader]
Failed to define class net.bull.javamelody.HibernateBatcherFactory$HibernateNonBatchingBatcher in Module "deployment.war:main" from Service Module Loader: java.lang.LinkageError: Failed to link net/bull/javamelody/HibernateBatcherFactory$HibernateNonBatchingBatcher (Module "deployment.war:main" from Service Module Loader)
Caused by: java.lang.NoClassDefFoundError: org/hibernate/jdbc/NonBatchingBatcher
Caused by: java.lang.ClassNotFoundException: org.hibernate.jdbc.NonBatchingBatcher from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.HibernateBatcherFactory$HibernateNonBatchingBatcher because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: java.lang.ClassNotFoundException: net.bull.javamelody.HibernateBatcherFactory$HibernateNonBatchingBatcher from [Module "deployment.war:main" from Service Module Loader]
Caused by: java.lang.ClassNotFoundException: net.bull.javamelody.HibernateBatcherFactory$HibernateNonBatchingBatcher from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.HtmlInjectorResponseStream because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.HtmlInjectorResponseStream
Caused by: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.FilterServletOutputStream
Caused by: java.lang.NoClassDefFoundError: javax/servlet/WriteListener
Caused by: java.lang.ClassNotFoundException: javax.servlet.WriteListener from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.MongoWrapper because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.MongoWrapper
Caused by: java.lang.NoClassDefFoundError: com/mongodb/client/MongoDatabase
Caused by: java.lang.ClassNotFoundException: com.mongodb.client.MongoDatabase from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.Log4J2Logger because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.Log4J2Logger
Caused by: java.lang.NoClassDefFoundError: Lorg/apache/logging/log4j/Logger;
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Logger from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.MongoWrapper$MongoCollectionHandler because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.MongoWrapper$MongoCollectionHandler
Caused by: java.lang.NoClassDefFoundError: Lcom/mongodb/client/MongoCollection;
Caused by: java.lang.ClassNotFoundException: com.mongodb.client.MongoCollection from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.FilterServletOutputStream because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.FilterServletOutputStream
Caused by: java.lang.NoClassDefFoundError: javax/servlet/WriteListener
Caused by: java.lang.ClassNotFoundException: javax.servlet.WriteListener from [Module "deployment.war:main" from Service Module Loader]
Failed to define class net.bull.javamelody.StrutsInterceptor in Module "deployment.war:main" from Service Module Loader: java.lang.LinkageError: Failed to link net/bull/javamelody/StrutsInterceptor (Module "deployment.war:main" from Service Module Loader)
Caused by: java.lang.NoClassDefFoundError: com/opensymphony/xwork2/interceptor/AbstractInterceptor
Caused by: java.lang.ClassNotFoundException: com.opensymphony.xwork2.interceptor.AbstractInterceptor from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.StrutsInterceptor because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: java.lang.ClassNotFoundException: net.bull.javamelody.StrutsInterceptor from [Module "deployment.war:main" from Service Module Loader]
Caused by: java.lang.ClassNotFoundException: net.bull.javamelody.StrutsInterceptor from [Module "deployment.war:main" from Service Module Loader]
WELD-000119 Not generating any bean definitions from net.bull.javamelody.MongoWrapper$MongoDatabaseHandler because of underlying class loading error
catching: org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class net.bull.javamelody.MongoWrapper$MongoDatabaseHandler
Caused by: java.lang.NoClassDefFoundError: Lcom/mongodb/client/MongoDatabase;
Caused by: java.lang.ClassNotFoundException: com.mongodb.client.MongoDatabase from [Module "deployment.war:main" from Service Module Loader]

**Comment by evernat** [comment]
There is an issue #634 which is fixed in master.
You can download a new build including the fix at:
https://javamelody.ci.cloudbees.com/job/javamelody/net.bull.javamelody$javamelody-core/
