### ISSUE TITLE
WELD-001602: Cannot create qualifier instance model for @net.bull.javamelody.Monitored(name=)

### ISSUE THREAD

**Issue by rengar-zz** [javamelody/javamelody#655]
Javamelody 1.68.1 
Error deploying in Wildfly 10.1

**Comment by evernat** [comment]
I don't understand the issue.
Do you have a stack-trace to share?
Can you give the source of a simple project to reproduce the issue?

**Comment by rengar-zz** [comment]
Stacktrace:

08:18:23,433 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-4) MSC000001: Failed to start service jboss.deployment.unit."neodoo-ear-1.0-SNAPSHOT.ear".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."neodoo-ear-1.0-SNAPSHOT.ear".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.weld.exceptions.WeldException: WELD-001602: Cannot create qualifier instance model for @net.bull.javamelody.Monitored(name=)
	at net.bull.javamelody.Monitored.name(Monitored.java:0)
  StackTrace:
	at org.jboss.weld.resolution.QualifierInstance.createValues(QualifierInstance.java:139)
	at org.jboss.weld.resolution.QualifierInstance.of(QualifierInstance.java:96)
	at org.jboss.weld.resolution.QualifierInstance.of(QualifierInstance.java:69)
	at org.jboss.weld.util.Beans.containsAllInterceptionBindings(Beans.java:213)
	at org.jboss.weld.resolution.TypeSafeInterceptorResolver.matches(TypeSafeInterceptorResolver.java:47)
	at org.jboss.weld.resolution.TypeSafeInterceptorResolver.matches(TypeSafeInterceptorResolver.java:34)
	at org.jboss.weld.resolution.TypeSafeResolver.findMatching(TypeSafeResolver.java:105)
	at org.jboss.weld.resolution.TypeSafeResolver.access$000(TypeSafeResolver.java:42)
	at org.jboss.weld.resolution.TypeSafeResolver$ResolvableToBeanCollection.load(TypeSafeResolver.java:53)
	at org.jboss.weld.resolution.TypeSafeResolver$ResolvableToBeanCollection.load(TypeSafeResolver.java:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:49)
	at org.jboss.weld.resolution.TypeSafeResolver.resolve(TypeSafeResolver.java:90)
	at org.jboss.weld.manager.BeanManagerImpl.resolveInterceptors(BeanManagerImpl.java:937)
	at org.jboss.weld.injection.producer.InterceptionModelInitializer.initInterceptor(InterceptionModelInitializer.java:189)
	at org.jboss.weld.injection.producer.InterceptionModelInitializer.initCdiBusinessMethodInterceptor(InterceptionModelInitializer.java:184)
	at org.jboss.weld.injection.producer.InterceptionModelInitializer.initCdiBusinessMethodInterceptors(InterceptionModelInitializer.java:176)
	at org.jboss.weld.injection.producer.InterceptionModelInitializer.initCdiInterceptors(InterceptionModelInitializer.java:141)
	at org.jboss.weld.injection.producer.InterceptionModelInitializer.init(InterceptionModelInitializer.java:108)
	at org.jboss.weld.injection.producer.BeanInjectionTarget.buildInterceptionModel(BeanInjectionTarget.java:94)
	at org.jboss.weld.injection.producer.BeanInjectionTarget.initializeInterceptionModel(BeanInjectionTarget.java:89)
	at org.jboss.weld.injection.producer.BeanInjectionTarget.initializeAfterBeanDiscovery(BeanInjectionTarget.java:99)
	at org.jboss.weld.injection.producer.InjectionTargetInitializationContext.initialize(InjectionTargetInitializationContext.java:42)
	at org.jboss.weld.injection.producer.InjectionTargetService.initialize(InjectionTargetService.java:63)
	at org.jboss.weld.bootstrap.WeldStartup.deployBeans(WeldStartup.java:433)
	at org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:83)
	at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:95)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	... 3 more
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.resolution.QualifierInstance.createValues(QualifierInstance.java:137)
	... 37 more

**Comment by evernat** [comment]
I think that it is an issue with WELD when using an EAR.
For example, see https://issues.jboss.org/browse/WELD-2250
and https://stackoverflow.com/questions/44478712/inject-a-bean-into-ejb-which-has-been-implemented-in-a-different-module-war

Can you confirm that?

**Comment by rengar-zz** [comment]
I have a EAR with 2 WAR monitored with javamelody.

It works if only put Javamelody at 1 WAR.

**Comment by evernat** [comment]
I suggest to put javamelody in each one of the 2 WAR, or in only 1 WAR otherwise (that is not in the EAR itself).
The rest if certainly a WELD issue, see https://issues.jboss.org/browse/WELD-2250 or https://stackoverflow.com/questions/44478712/inject-a-bean-into-ejb-which-has-been-implemented-in-a-different-module-war
