### ISSUE TITLE
Errors upgrading from JavaMelody 1.63 to JavaMelody 1.67 on JBossEAP 6.2

### ISSUE THREAD

**Issue by Zidedine** [javamelody/javamelody#673]
I had an Java application deployed in JBossEAP 6.2 with JavaMelody 1.63. Everything was running fine.

**We upgraded from JavaMelody 1.63 to JavaMelody 1.67**. Now we got errors:

- Servlet API 3.1 (java.lang.NoClassDefFoundError javax/servlet/WriteListener)

And with optional dependencies too:

- Quartz 1.5.2 (java.lang.NoClassDefFoundError: org/quartz/JobDetail)
- MongoDB 3.3.0

**Comment by evernat** [comment]
This is certainly an issue related to CDI.
I suggest to try to upgrade to JavaMelody 1.68 or 1.69 (instead of 1.67), because it will fix the issue #634.

**Comment by Zidedine** [comment]
With JavaMelody 1.69 we got this error:

09:43:39,781 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-9) MSC000001: Failed to start service jboss.deployment.unit."miapp-ear.ear".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."estandarapp-ear.ear".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1767) [jboss-msc-1.0.4.GA-redhat-1.jar:1.0.4.GA-redhat-1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_55]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_55]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_55]
Caused by: org.jboss.weld.exceptions.WeldException: WELD-000830 Unable to load the cache value for the key class net.bull.javamelody.internal.model.Quartz2Adapter
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:73)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:112)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:93)
	at org.jboss.weld.resources.ClassTransformer.loadClass(ClassTransformer.java:164)
	at org.jboss.weld.bootstrap.BeanDeployer.loadWeldClass(BeanDeployer.java:116)
	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:79)
	at org.jboss.weld.bootstrap.BeanDeployer.addClasses(BeanDeployer.java:135)
	at org.jboss.weld.bootstrap.BeanDeployment.createBeans(BeanDeployment.java:184)
	at org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:349)
	at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:63)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.4.GA-redhat-1.jar:1.0.4.GA-redhat-1]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.4.GA-redhat-1.jar:1.0.4.GA-redhat-1]
	... 3 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: org.jboss.weld.resources.spi.ResourceLoadingException: Error while loading class net.bull.javamelody.internal.model.QuartzAdapter
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2258)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3990)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3994)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4878)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:71)
	... 14 more
Caused by: org.jboss.weld.resources.spi.ResourceLoadingException: Error while loading class net.bull.javamelody.internal.model.QuartzAdapter
	at org.jboss.weld.resources.ClassTransformer.loadClass(ClassTransformer.java:176)
	at org.jboss.weld.introspector.jlr.WeldClassImpl.<init>(WeldClassImpl.java:146)
	at org.jboss.weld.introspector.jlr.WeldClassImpl.of(WeldClassImpl.java:126)
	at org.jboss.weld.resources.ClassTransformer$TransformTypeToWeldClass.load(ClassTransformer.java:60)
	at org.jboss.weld.resources.ClassTransformer$TransformTypeToWeldClass.load(ClassTransformer.java:51)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3589)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2374)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2337)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2252)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: org/quartz/Scheduler
	at java.lang.Class.getDeclaredMethods0(Native Method) [rt.jar:1.7.0_55]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2531) [rt.jar:1.7.0_55]
	at java.lang.Class.getDeclaredMethods(Class.java:1855) [rt.jar:1.7.0_55]
	at org.jboss.weld.util.reflection.SecureReflections$8.work(SecureReflections.java:175)
	at org.jboss.weld.util.reflection.SecureReflections$8.work(SecureReflections.java:172)
	at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:52)
	at org.jboss.weld.util.reflection.SecureReflectionAccess.runAndWrap(SecureReflectionAccess.java:63)
	at org.jboss.weld.util.reflection.SecureReflections.getDeclaredMethods(SecureReflections.java:172)
	at org.jboss.weld.introspector.jlr.WeldClassImpl.<init>(WeldClassImpl.java:240)
	at org.jboss.weld.introspector.jlr.WeldClassImpl.of(WeldClassImpl.java:126)
	at org.jboss.weld.resources.ClassTransformer$TransformTypeToWeldClass.load(ClassTransformer.java:60)
	at org.jboss.weld.resources.ClassTransformer$TransformTypeToWeldClass.load(ClassTransformer.java:51)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3589)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2374)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2337)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2252)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3990)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3994)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4878)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:71)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:112)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:93)
	at org.jboss.weld.resources.ClassTransformer.loadClass(ClassTransformer.java:164)
	... 26 more
Caused by: java.lang.ClassNotFoundException: org.quartz.Scheduler from [Module "deployment.estandarapp-ear.ear.estandarapp-web.war:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.3.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.3.Final-redhat-1]
	... 49 more

**Comment by evernat** [comment]
follow-up in #674
