### ISSUE TITLE
After embedding javamelody-spring-boot-starter in war, websocket is not work on weblogic 12c

### ISSUE THREAD

**Issue by aoe2xm** [javamelody/javamelody#676]
I face a problem that the connection cannot upgrade to websocket while javamelody is embedded in spring boot application on weblogic 12c, it works perfectly on emebbed tomcat.

Did anyone know is there any configuration can make both javamelody and spring-websocket work together on weblogic?

Thanks a lot!

![failed_to_upgrade](https://user-images.githubusercontent.com/32252520/30791216-8f189b1c-a1e3-11e7-8cfd-c3b91360ea8f.png)

javamelody-spring-boot-starter version: 1.69.0
Spring Boot version: 1.5.7.RELEASE

**Comment by evernat** [comment]
Does it work at least on weblogic 12c, without javamelody-spring-boot-starter version ?
And have you logs on the server?

**Comment by evernat** [comment]
It seems that this subject about spring-boot, websocket in weblogic does not inspire many people here. It may not be a good combination to have.

Anyway, no response from the reporter to the question above, so closing as incomplete.

**Comment by yangjiebeijing** [comment]
i am sure ,i have the same problem .
javamelody-spring-boot-starter version: 1.67.0
Spring Boot version: 1.4.0.RELEASE
javamelody both jetty 9.1+ and tomcat 8+worked well.
but it not worked in weblogic 12.1.3.
when i remove the javamelody filter,websocket worked well in  in weblogic 12.1.3.
with the javamelody filter, websockt handshark can not be success. http upgrade status 101 could not reached web browser.
i think the filter must dosth ,that the response cann't reached web browser. so web browser wait timeout!

**Comment by yangjiebeijing** [comment]
maybe,the log is useful.
java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.7.0_80]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51) ~[na:1.7.0_80]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.7.0_80]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.7.0_80]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:492) ~[na:1.7.0_80]
	at weblogic.socket.NIOSocketMuxer$NIOOutputStream.writeInternal(NIOSocketMuxer.java:1064) ~[weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.socket.NIOSocketMuxer$NIOOutputStream.write(NIOSocketMuxer.java:983) ~[weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.ChunkOutput.writeChunkTransfer(ChunkOutput.java:622) ~[weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.ChunkOutput.writeChunks(ChunkOutput.java:587) ~[weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.ChunkOutput.flush(ChunkOutput.java:472) ~[weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.CharsetChunkOutput.flush(CharsetChunkOutput.java:301) ~[weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.ChunkOutputWrapper.flush(ChunkOutputWrapper.java:193) ~[weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.ServletOutputStreamImpl.flush(ServletOutputStreamImpl.java:135) ~[weblogic.server.merged.jar:12.1.3.0.0]
	at net.bull.javamelody.FilterServletOutputStream.flush(FilterServletOutputStream.java:69) ~[javamelody-core-1.67.0.jar:1.67.0]
	at net.bull.javamelody.FilterServletResponseWrapper.flushBuffer(FilterServletResponseWrapper.java:158) ~[javamelody-core-1.67.0.jar:1.67.0]
	at org.springframework.http.server.ServletServerHttpResponse.flush(ServletServerHttpResponse.java:96) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.socket.sockjs.transport.session.AbstractHttpSockJsSession.writeFrameInternal(AbstractHttpSockJsSession.java:365) ~[spring-websocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.close(AbstractSockJsSession.java:207) ~[spring-websocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.socket.handler.WebSocketSessionDecorator.close(WebSocketSessionDecorator.java:158) [spring-websocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.close(ConcurrentWebSocketSessionDecorator.java:192) [spring-websocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.sendToClient(StompSubProtocolHandler.java:452) [spring-websocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.handleMessageToClient(StompSubProtocolHandler.java:422) [spring-websocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.socket.messaging.SubProtocolWebSocketHandler.handleMessage(SubProtocolWebSocketHandler.java:338) [spring-websocket-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:135) [spring-messaging-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]

**Comment by evernat** [comment]
@yangjiebeijing 
As said before, spring-boot, websocket and weblogic is in my opinion very uncommon and a combination asking trouble without anyone to help for free. And as you said, it works in Jetty 9.1+ and in Tomcat 8+, so it may well be a bug in weblogic 12.

For these 2 reasons, I suggest to contact your weblogic support to fix the weblogic bug.
