### ISSUE TITLE
Can't show graph in springboot with alpine-jdk

### ISSUE THREAD

**Issue by liyuankui** [javamelody/javamelody#691]
Java: 
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (IcedTea 3.4.0) (Alpine 8.131.11-r2)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
Stack:
```
java.lang.NullPointerException: null
      at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
      at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
      at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
      at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
      at sun.font.SunFontManager$2.run(SunFontManager.java:431)
      at java.security.AccessController.doPrivileged(Native Method)
      at sun.font.SunFontManager.<init>(SunFontManager.java:376)
      at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
      at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
      at sun.reflect.GeneratedConstructorAccessor238.newInstance(Unknown Source)
      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
      at java.lang.Class.newInstance(Class.java:442)
      at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
      at java.security.AccessController.doPrivileged(Native Method)
      at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
      at java.awt.Font.getFont2D(Font.java:491)
      at java.awt.Font.access$000(Font.java:224)
      at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)
      at sun.font.FontUtilities.getFont2D(FontUtilities.java:180)
      at sun.font.StandardGlyphVector.initFontData(StandardGlyphVector.java:1126)
      at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1115)
      at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:172)
      at java.awt.Font.getStringBounds(Font.java:2421)
      at java.awt.Font.getStringBounds(Font.java:2331)
      at java.awt.Font.getStringBounds(Font.java:2365)
      at org.jrobin.graph.ImageWorker.getStringWidth(ImageWorker.java:166)
      at org.jrobin.graph.RrdGraph.getSmallFontCharWidth(RrdGraph.java:594)
      at org.jrobin.graph.RrdGraph.initializeLimits(RrdGraph.java:319)
      at org.jrobin.graph.RrdGraph.createGraph(RrdGraph.java:88)
      at org.jrobin.graph.RrdGraph.<init>(RrdGraph.java:59)
      at net.bull.javamelody.internal.model.JRobin.graph(JRobin.java:260)
      at net.bull.javamelody.internal.web.MonitoringController.doGraph(MonitoringController.java:385)
      at net.bull.javamelody.internal.web.MonitoringController.doReport(MonitoringController.java:189)
      at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:160)
      at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:396)
      at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:200)
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
      at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105)
      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
```

**Comment by liyuankui** [comment]
Possibly caused by  https://github.com/docker-library/openjdk/issues/73

**Comment by evernat** [comment]
In some case ([strange characters in graphs](https://stackoverflow.com/questions/46699967/jenkins-load-statistics-graph-weird-encoding/46924944#46924944)), it has helped to install DejaVu fonts like this: `yum install dejavu-sans-fonts.noarch dejavu-sans-mono-fonts.noarch`.

That said, the docker-library issue is closer to your problem.

**Comment by liyuankui** [comment]
For developers who used docker & alpine

Please resolve this issue by adding (usually in your Dockerfile): 

```
apk --update add \
    font-config \
    ttf-dejavu 
```

**Comment by skarpushin** [comment]
This didn't work for me. I've opened issue here https://github.com/gliderlabs/docker-alpine/issues/360

**Comment by liyuankui** [comment]
Sorry, my bad, it should be 

apk --update add \
    fontconfig \
    ttf-dejavu

**Comment by skarpushin** [comment]
@liyuankui , thank you, that worked!
