### ISSUE TITLE
Java Melody on jenkins does not displaying a charts as its only showing a chart links

### ISSUE THREAD

**Issue by ahmadh71** [javamelody/javamelody#699]

**Comment by evernat** [comment]
Can you look in the server output? You may see exceptions when displaying the monitoring page and you can copy them here.

**Comment by SergeVer** [comment]
have same issue 
![image](https://user-images.githubusercontent.com/10994431/33884811-deb44650-df49-11e7-81c4-172f5cd1b3f2.png)

> 2017-12-12 12:33:41.758 ERROR 1 --- [nio-8888-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.NullPointerException: null
        at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264) ~[na:1.8.0_151]
        at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219) ~[na:1.8.0_151]
        at sun.awt.FontConfiguration.init(FontConfiguration.java:107) ~[na:1.8.0_151]
        at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774) ~[na:1.8.0_151]
        at sun.font.SunFontManager$2.run(SunFontManager.java:431) ~[na:1.8.0_151]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_151]
        at sun.font.SunFontManager.<init>(SunFontManager.java:376) ~[na:1.8.0_151]
        at sun.awt.FcFontManager.<init>(FcFontManager.java:35) ~[na:1.8.0_151]
        at sun.awt.X11FontManager.<init>(X11FontManager.java:57) ~[na:1.8.0_151]
        at sun.reflect.GeneratedConstructorAccessor27.newInstance(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_151]
        at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_151]
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83) ~[na:1.8.0_151]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_151]
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74) ~[na:1.8.0_151]
        at java.awt.Font.getFont2D(Font.java:491) ~[na:1.8.0_151]
        at java.awt.Font.access$000(Font.java:224) ~[na:1.8.0_151]
        at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228) ~[na:1.8.0_151]
        at sun.font.FontUtilities.getFont2D(FontUtilities.java:180) ~[na:1.8.0_151]
        at sun.font.StandardGlyphVector.initFontData(StandardGlyphVector.java:1126) ~[na:1.8.0_151]
        at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1115) ~[na:1.8.0_151]
        at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:172) ~[na:1.8.0_151]
        at java.awt.Font.getStringBounds(Font.java:2421) ~[na:1.8.0_151]
        at java.awt.Font.getStringBounds(Font.java:2331) ~[na:1.8.0_151]
        at java.awt.Font.getStringBounds(Font.java:2365) ~[na:1.8.0_151]
        at org.jrobin.graph.ImageWorker.getStringWidth(ImageWorker.java:166) ~[jrobin-1.5.9.jar!/:1.5.9]
        at org.jrobin.graph.RrdGraph.getSmallFontCharWidth(RrdGraph.java:594) ~[jrobin-1.5.9.jar!/:1.5.9]
        at org.jrobin.graph.RrdGraph.initializeLimits(RrdGraph.java:319) ~[jrobin-1.5.9.jar!/:1.5.9]
        at org.jrobin.graph.RrdGraph.createGraph(RrdGraph.java:88) ~[jrobin-1.5.9.jar!/:1.5.9]
        at org.jrobin.graph.RrdGraph.<init>(RrdGraph.java:59) ~[jrobin-1.5.9.jar!/:1.5.9]
        at net.bull.javamelody.internal.model.JRobin.graph(JRobin.java:260) ~[javamelody-core-1.70.0.jar!/:1.70.0]
        at net.bull.javamelody.internal.web.MonitoringController.doGraph(MonitoringController.java:390) ~[javamelody-core-1.70.0.jar!/:1.70.0]
        at net.bull.javamelody.internal.web.MonitoringController.doReport(MonitoringController.java:189) ~[javamelody-core-1.70.0.jar!/:1.70.0]
        at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:160) ~[javamelody-core-1.70.0.jar!/:1.70.0]
        at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:396) ~[javamelody-core-1.70.0.jar!/:1.70.0]
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:200) ~[javamelody-core-1.70.0.jar!/:1.70.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.0.0.RC2.jar!/:5.0.0.RC2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.0.RC2.jar!/:5.0.0.RC2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) ~[spring-web-5.0.0.RC2.jar!/:5.0.0.RC2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.0.RC2.jar!/:5.0.0.RC2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-5.0.0.RC2.jar!/:5.0.0.RC2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.0.RC2.jar!/:5.0.0.RC2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:199) ~[spring-web-5.0.0.RC2.jar!/:5.0.0.RC2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.0.RC2.jar!/:5.0.0.RC2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

**Comment by evernat** [comment]
This is a common issue with fonts which are not installed on some reduced Linux environments.
Searching the web for "NullPointerException: null at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)" will confirm that.
It was seen for example, with Docker / alpine-jdk (see issue #691) or with Debian / openjdk headless.

With Docker, it was said to add (usually in your Dockerfile): 
```
apk --update add \
    fontconfig \
    ttf-dejavu 
```

In some similar case (strange characters with CentOS), [it was said](https://stackoverflow.com/questions/46699967/jenkins-load-statistics-graph-weird-encoding/46924944#46924944) to check the installed fonts:
```
fc-list
```
and to install the DejaVu fonts:
```
yum install dejavu-sans-fonts.noarch dejavu-sans-mono-fonts.noarch
```

**Comment by evernat** [comment]
@sharpedavid 
After calling the reports, do not look in your log4j/logback logs, look in the standard and in the error console output of the process.

**Comment by sharpedavid** [comment]
Thank you @evernat. I found the error in `/app/tomcat/tomee/logs/localhost.2019-01-04.log`

> 04-Jan-2019 14:14:06.672 SEVERE [https-jsse-nio-5443-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [default] in context with path [/BestAdapter]  threw exception [Filter execution threw an exception] with root cause                                                                                                                           java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment                                                                                                             at java.lang.Class.forName0(Native Method)                                                                                                                                                     at java.lang.Class.forName(Class.java:264)                                                                                                                                                     at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)                                                                                                                         at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)                                                                                                       at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)                                                                                                                        at org.jrobin.graph.ImageWorker.resize(ImageWorker.java:57)                                                                                                                                    at org.jrobin.graph.ImageWorker.(ImageWorker.java:47)                                                                                                                                    at org.jrobin.graph.RrdGraph.(RrdGraph.java:57)                                                                                                                                          at net.bull.javamelody.internal.model.JRobin.graph(JRobin.java:262)                                                                                                                            at net.bull.javamelody.internal.web.MonitoringController.doGraph(MonitoringController.java:394)                                                                                                at net.bull.javamelody.internal.web.MonitoringController.doReport(MonitoringController.java:192)                                                                                               at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:163)                                                                              at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:408)                                                                                                                at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206)                                                                                                                    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)                                                                                           at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)                                                                                                   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)                                                                                                         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)                                                                                                         at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)                                                                                                                         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)                                                                                                      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)                                                                                                               at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)                                                                                                                at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)                                                                                   at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)                                                                                                   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)                                                                                                            at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)                                                                                                                 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)                                                                                                                  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)                                                                                                            at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)                                                                                                     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)                                                                                                         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)                                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                             at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)                                                                                                          at java.lang.Thread.run(Thread.java:748)

I may try [this answer](https://stackoverflow.com/questions/21131855/could-not-initialize-class-sun-awt-x11graphicsenvironment-on-solaris) to fix it, but we'll see as I have limited influence over the operational environment.
