### ISSUE TITLE
TomEE + Melody-1.70.0+ Deployment failing  

### ISSUE THREAD

**Issue by softashu** [javamelody/javamelody#707]
Hi 

Using TomEE
-------------------
Server version: Apache Tomcat/7.0.37
Server built: Feb 12 2013 10:44:14
Server number: 7.0.37.0
OS Name: Windows 7
OS Version: 6.1
Architecture: amd64
JVM Version: 1.8.0_72-b15
JVM Vendor: Oracle Corporation
Exception we are getting is

ALLVARLIG: CDI Beans module deployment failed
org.apache.webbeans.exception.WebBeansConfigurationException: Interceptor class : net.bull.javamelody.MonitoringAsynchronousCdiInterceptor must have at least one @interceptorbindingtype
at org.apache.openejb.cdi.CdiScanner.init(CdiScanner.java:127)
at org.apache.openejb.cdi.OpenEJBLifecycle.startApplication(OpenEJBLifecycle.java:200)
at org.apache.openejb.cdi.ThreadSingletonServiceImpl.initialize(ThreadSingletonServiceImpl.java:167)
at org.apache.openejb.cdi.CdiBuilder.build(CdiBuilder.java:43)
at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:723)
at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:546)
at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1128)
at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1033)
at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:124)
at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5179)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:977)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1655)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

Please suggest resolving

Thanks
Ashutosh

**Comment by evernat** [comment]
This issue is clearly invalid: you give version of everything except of CDI api/impl and of javamelody. That's sad.
I suggest to unplug your keyboard.

**Comment by evernat** [comment]
Ah sorry, there was a bit in the title, but not enough.

**Comment by softashu** [comment]
Sorry, i did not get you?

**Comment by sharpedavid** [comment]
I think I encountered the same error when deploying javamelody-core-1.74.0 to TomEE Plume 7.0.2. I tried two things to fix it, and *both* worked. You can:

* Remove the beans.xml file from the javamelody-core JAR, or
* Add an "exclusions.list" file containing "javamelody-core-1.74.0.jar" to your project.

I found the second solution preferable. I added "C:\Dev\MyApplication\src\main\webapp\WEB-INF\exclusions.list".

I'm not sure what the consequences of doing this are though. I think TomEE will no longer manage CDI beans in javamelody, but this doesn't seem to interfere with javamelody working.

FYI, @evernat, according to [this page](https://tomee.apache.org/comparison.html), TomEE Plume 7.0.2 implements "CDI 1.2, DI, Interceptors 1.2, Common Annotations JSR 346 + JSR 330 + JSR 318 + JSR 250".

**Comment by softashu** [comment]
thanks sharpedavidi will try again

**Comment by evernat** [comment]
see #802 for fix
