### ISSUE TITLE
from version 1.66 dosn't deploy on wildfly(8-10)

### ISSUE THREAD

**Issue by ScoobyMax** [javamelody/javamelody#715]
```
2017-12-22 11:48:57,976 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 2) JBAS014613: Operation ("deploy") failed - address: ([("deployment" => "vis-web.war")]) - failure description: {"JBAS014671: Failed services" => {"jboss.deployment.unit.\"vis-web.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"vis-web.war\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001417: Enabled interceptor class <class>net.bull.javamelody.MonitoringCdiInterceptor</class> in vfs:/D:/work/repo/vis/vis-web/vis-web/target/vis-web.war/WEB-INF/lib/javamelody-core-1.70.0.jar/META-INF/beans.xml@6 does not match an interceptor bean: the class is not found, or not annotated with @Interceptor and still not registered through a portable extension, or not annotated with @Dependent inside an implicit bean archive"}}
2017-12-22 11:48:57,980 ERROR [org.jboss.as.server] (management-handler-thread - 2) JBAS015870: Deploy of deployment "vis-web.war" was rolled back with the following failure message: 
{"JBAS014671: Failed services" => {"jboss.deployment.unit.\"vis-web.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"vis-web.war\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001417: Enabled interceptor class <class>net.bull.javamelody.MonitoringCdiInterceptor</class> in vfs:/D:/work/repo/vis/vis-web/vis-web/target/vis-web.war/WEB-INF/lib/javamelody-core-1.70.0.jar/META-INF/beans.xml@6 does not match an interceptor bean: the class is not found, or not annotated with @Interceptor and still not registered through a portable extension, or not annotated with @Dependent inside an implicit bean archive"}}
2017-12-22 11:50:10,132 ERROR [org.jboss.remoting.resource] (Remoting "atc9088:MANAGEMENT" task-14) Close action for Channel ID 7e144838 (inbound) of Remoting connection 29250886 to /127.0.0.1:52745 failed to execute (resource may be left in an indeterminate state): java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating
	at org.xnio.nio.WorkerThread.executeAfter(WorkerThread.java:595)
	at org.jboss.remoting3.remote.RemoteConnection$RemoteWriteListener.send(RemoteConnection.java:331) [jboss-remoting-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.remoting3.remote.RemoteConnection.send(RemoteConnection.java:122) [jboss-remoting-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.remoting3.remote.RemoteConnectionChannel.closeReadsAndWrites(RemoteConnectionChannel.java:257) [jboss-remoting-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.remoting3.remote.RemoteConnectionChannel.closeAction(RemoteConnectionChannel.java:530) [jboss-remoting-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.remoting3.spi.AbstractHandleableCloseable.close(AbstractHandleableCloseable.java:153) [jboss-remoting-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.as.protocol.mgmt.ManagementChannelReceiver.handleEnd(ManagementChannelReceiver.java:127) [wildfly-protocol-8.1.0.Final.jar:8.1.0.Final]
	at org.jboss.remoting3.remote.RemoteConnectionChannel$2.run(RemoteConnectionChannel.java:282) [jboss-remoting-4.0.3.Final.jar:4.0.3.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_152]
```

**Comment by evernat** [comment]
There are several issues here which are WELD (and WildFly) issues.
First, the message displayed is incorrect. The message will be fixed by WELD-1540 in WELD 2.1.1.Final:
https://issues.jboss.org/browse/WELD-1540

Second, it seems to me that CDI & WELD are wrong here and should not throw an exception.
And if I am right it will be fixed in CDI 1.2.Final:
https://issues.jboss.org/browse/CDI-404
So closing this issue as invalid.

So what can you do in the meantime?
You may simplify your deployed modules (according to some web search, using a single classloader may help).
Or you may downgrade to javamelody 1.65 which does not have the CDI beans.xml file.
Or ... I don't know what else.
(Note that javamelody can be used in general with WildFly 9 or WildFly 10. See for example #665 which is a simple hot-deployment issue)
