### ISSUE TITLE
java melody didn't work in the FreeBSD environment

### ISSUE THREAD

**Issue by Madhupriyaks** [javamelody/javamelody#726]
Initially I had written a local application and added jar files to WEB-INF/lib and made changes to my web.xml file and in the browser I got the graphs.
 I made the same to the my application in the server and the application is in the root.
I added jar files and configured web.xml but when I gave http://<host>/monitoring it showed "Error something has gone wrong while attempting to display this page"

Is there anything additional to be configured to monitor the Application to running on FreeBSD environment?

This was displayed in my log file:

SEVERE: Servlet.service() for servlet [default] in context with path [] threw exception [Filter execution threw an exception] with root cause
java.lang.UnsatisfiedLinkError: sun.management.OperatingSystemImpl.getSystemCpuLoad()D
	at sun.management.OperatingSystemImpl.getSystemCpuLoad(Native Method)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.bull.javamelody.internal.model.MemoryInformations.getFromOperatingSystem(MemoryInformations.java:214)
	at net.bull.javamelody.internal.model.MemoryInformations.getDoubleFromOperatingSystem(MemoryInformations.java:206)
	at net.bull.javamelody.internal.model.JavaInformations.buildSystemCpuLoad(JavaInformations.java:283)
	at net.bull.javamelody.internal.model.JavaInformations.<init>(JavaInformations.java:152)
	at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:155)
	at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:396)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

**Comment by evernat** [comment]
It seems that there is a problem with the JDK/JRE on your FreeBSD server. Is it Open JDK or Oracle JDK and what version exactly? Where did you get it from? Can you use another JDK/JRE?

**Comment by Madhupriyaks** [comment]
Hello
The jdk version is 1.8 and it is openJDK.

**Comment by evernat** [comment]
The fact that "the jdk works with all applications" as you said does not mean that there isn't any issue with the jdk in this particular case (java.lang.UnsatisfiedLinkError: sun.management.OperatingSystemImpl.getSystemCpuLoad() in FreeBSD).

This issue is tracked there in FreeBSD:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=205229
I leave it up to you to find if the error is fixed, disabled or not in your particular openjdk version.

**Comment by Madhupriyaks** [comment]
I want the values available from the graph to be stored in an excel or some text file . Is this possible?

**Comment by evernat** [comment]
No, it's not possible
