### ISSUE TITLE
graphs not seen

### ISSUE THREAD

**Issue by eggpulusu** [javamelody/javamelody#734]
[root@ip-172-31-57-134 lib]# ls -l
total 2456
-rw-r--r--. 1 tomcat tomcat 1328492 Feb 28 14:31 javamelody-core-1.71.0.jar
-rw-r--r--. 1 tomcat tomcat  788143 Feb 28 14:31 jrobin-1.5.9.jar
-rw-r--r--. 1 tomcat tomcat  391834 May 21  2016 log4j-1.2.15.jar

/monitoring shows the page with content.

Graphs are not seen. Any pointers would be helpful.

Wed Feb 28 14:42:14 EST 2018     DEBUG     JavaMelody listener init started
Wed Feb 28 14:42:14 EST 2018     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/CaptorMySQLDB]
Wed Feb 28 14:42:14 EST 2018     DEBUG     datasource rebinded: java:comp/env/jdbc/CaptorMySQLDB from class org.apache.tomcat.jdbc.pool.DataSource to class com.sun.proxy.$Proxy5
Wed Feb 28 14:42:14 EST 2018     DEBUG     JavaMelody listener init done in 337 ms
Wed Feb 28 14:42:14 EST 2018     DEBUG     JavaMelody filter init started
Wed Feb 28 14:42:14 EST 2018     DEBUG     OS: Linux unknown, amd64/64
Wed Feb 28 14:42:14 EST 2018     DEBUG     Java: OpenJDK Runtime Environment, 1.8.0_144-b01
Wed Feb 28 14:42:14 EST 2018     DEBUG     Server: Apache Tomcat/7.0.76
Wed Feb 28 14:42:14 EST 2018     DEBUG     Webapp context: /Captor
Wed Feb 28 14:42:14 EST 2018     DEBUG     JavaMelody version: 1.71.0
Wed Feb 28 14:42:14 EST 2018     DEBUG     JavaMelody classes loaded from: file:/var/lib/tomcat/webapps/Captor/WEB-INF/lib/javamelody-core-1.71.0.jar
Wed Feb 28 14:42:14 EST 2018     DEBUG     Application type: Classic
Wed Feb 28 14:42:14 EST 2018     DEBUG     Application version: null
Wed Feb 28 14:42:14 EST 2018     DEBUG     Host: ip-172-31-57-134@172.31.57.134
Wed Feb 28 14:42:14 EST 2018     DEBUG     log listeners initialized
Wed Feb 28 14:42:14 EST 2018     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/CaptorMySQLDB]
Wed Feb 28 14:42:14 EST 2018     DEBUG     counters initialized
Wed Feb 28 14:42:14 EST 2018     DEBUG     counters data read from files in /var/cache/tomcat/temp/javamelody/Captor_ip-172-31-57-134
Wed Feb 28 14:42:15 EST 2018     DEBUG     collect task scheduled every 60s
Wed Feb 28 14:42:15 EST 2018     DEBUG     first collect of data done
Wed Feb 28 14:42:15 EST 2018     DEBUG     JavaMelody filter init done in 436 ms
Wed Feb 28 14:44:50 EST 2018     WARN     heaphisto report failed

**Comment by eggpulusu** [comment]
Also PDF not working.

![image](https://user-images.githubusercontent.com/10599320/36812708-0aca79ce-1ca0-11e8-8657-4b7cc5f8991f.png)

[root@ip-172-31-57-134 lib]# pwd
/usr/share/tomcat/webapps/Captor/WEB-INF/lib
[root@ip-172-31-57-134 lib]# ls -l
total 3560
-rw-r--r--. 1 tomcat tomcat 1130070 Feb 28 15:45 itext-2.1.7.jar
-rw-r--r--. 1 tomcat tomcat 1328492 Feb 28 14:31 javamelody-core-1.71.0.jar
-rw-r--r--. 1 tomcat tomcat  788143 Feb 28 14:31 jrobin-1.5.9.jar
-rw-r--r--. 1 tomcat tomcat  391834 May 21  2016 log4j-1.2.15.jar


Wed Feb 28 15:45:57 EST 2018     DEBUG     JavaMelody listener init started
Wed Feb 28 15:45:57 EST 2018     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/CaptorMySQLDB]
Wed Feb 28 15:45:57 EST 2018     DEBUG     datasource rebinded: java:comp/env/jdbc/CaptorMySQLDB from class org.apache.tomcat.jdbc.pool.DataSource to class com.sun.proxy.$Proxy5
Wed Feb 28 15:45:57 EST 2018     DEBUG     JavaMelody listener init done in 333 ms
Wed Feb 28 15:45:57 EST 2018     DEBUG     JavaMelody filter init started
Wed Feb 28 15:45:57 EST 2018     DEBUG     OS: Linux unknown, amd64/64
Wed Feb 28 15:45:57 EST 2018     DEBUG     Java: OpenJDK Runtime Environment, 1.8.0_144-b01
Wed Feb 28 15:45:57 EST 2018     DEBUG     Server: Apache Tomcat/7.0.76
Wed Feb 28 15:45:57 EST 2018     DEBUG     Webapp context: /Captor
Wed Feb 28 15:45:57 EST 2018     DEBUG     JavaMelody version: 1.71.0
Wed Feb 28 15:45:57 EST 2018     DEBUG     JavaMelody classes loaded from: file:/var/lib/tomcat/webapps/Captor/WEB-INF/lib/javamelody-core-1.71.0.jar
Wed Feb 28 15:45:57 EST 2018     DEBUG     Application type: Classic
Wed Feb 28 15:45:57 EST 2018     DEBUG     Application version: null
Wed Feb 28 15:45:57 EST 2018     DEBUG     Host: ip-172-31-57-134@172.31.57.134
Wed Feb 28 15:45:57 EST 2018     DEBUG     log listeners initialized
Wed Feb 28 15:45:57 EST 2018     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/CaptorMySQLDB]
Wed Feb 28 15:45:57 EST 2018     DEBUG     counters initialized
Wed Feb 28 15:45:57 EST 2018     DEBUG     counters data read from files in /var/cache/tomcat/temp/javamelody/Captor_ip-172-31-57-134
Wed Feb 28 15:45:58 EST 2018     DEBUG     collect task scheduled every 60s
Wed Feb 28 15:45:58 EST 2018     DEBUG     first collect of data done
Wed Feb 28 15:45:58 EST 2018     DEBUG     JavaMelody filter init done in 334 ms

**Comment by eggpulusu** [comment]
Stack-trace
java.lang.ArrayIndexOutOfBoundsException: 0
      at sun.font.CompositeFont.getSlotFont(CompositeFont.java:351)
      at sun.font.CompositeGlyphMapper.initMapper(CompositeGlyphMapper.java:81)
      at sun.font.CompositeGlyphMapper.<init>(CompositeGlyphMapper.java:62)
      at sun.font.CompositeFont.getMapper(CompositeFont.java:409)
      at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1122)
      at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:172)
      at java.awt.Font.getStringBounds(Font.java:2421)
      at java.awt.Font.getStringBounds(Font.java:2331)
      at java.awt.Font.getStringBounds(Font.java:2365)
      at org.jrobin.graph.ImageWorker.getStringWidth(ImageWorker.java:166)
      at org.jrobin.graph.RrdGraph.getSmallFontCharWidth(RrdGraph.java:594)
      at org.jrobin.graph.RrdGraph.initializeLimits(RrdGraph.java:319)
      at org.jrobin.graph.RrdGraph.createGraph(RrdGraph.java:88)
      at org.jrobin.graph.RrdGraph.<init>(RrdGraph.java:59)
      at net.bull.javamelody.internal.model.JRobin.graph(JRobin.java:260)
      at net.bull.javamelody.internal.web.MonitoringController.doGraph(MonitoringController.java:390)
      at net.bull.javamelody.internal.web.MonitoringController.doReport(MonitoringController.java:189)
      at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:160)
      at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:401)
      at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:205)
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
      at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
      at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
      at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
      at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
      at java.lang.Thread.run(Thread.java:748)

**Comment by eggpulusu** [comment]
I installed dejavu-sans-fonts and all well now.

Issues are resolved.
