### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org/postgresql/Driver

### ISSUE THREAD

**Issue by sta-szek** [javamelody/javamelody#749]
Hi guys, I have strange issue with javamelody. This is the only what I have:
```
com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@63c099aa -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
java.sql.SQLException: org/postgresql/Driver
	at net.bull.javamelody.JdbcDriver.connect(JdbcDriver.java:99)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:200)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1127)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1114)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1855)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
Caused by: java.lang.ClassNotFoundException: org/postgresql/Driver
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.bull.javamelody.JdbcDriver.connect(JdbcDriver.java:96)
	... 9 common frames omitted
```

Looks like it happens randomly, not always.
Of course I have postgresql dependency with scope compile in maven.
Double checked and it is also present in war.

I googled a lot and couldn't find any solution. Have it occurred in the past?

Thanks

**Comment by evernat** [comment]
Is javamelody jar file in the war?
If yes, can you give the source of a simple project to reproduce the issue?

**Comment by sta-szek** [comment]
Hi, unfortunately I cannot provide you our project. It is private company one.
We used maven dependency, so `jar` file.
I deleted javamelody from our project and the error does not appear anymore.
With other smaller project it works, so I suppose there must be some dependency -- we have really big projct, it uses `c3p0` as DB connection pool, that's all what I can provide.

**Comment by evernat** [comment]
Ok. In that case, I probably can't do anything. So closing, sorry.
