### ISSUE TITLE
Javamelody is throwing error when we configure mail notification 

### ISSUE THREAD

**Issue by chinnapureddy** [javamelody/javamelody#753]
Javamelody is throwing an error when we configure mail notification in Jira and confluence. 
Also getting mail.x.jar conflict. Please change the code to use Atlassian mail.jar

Please find the log:
Technical details
Log's referral number: dd4bbf39-bf6b-42f2-9ddb-2a3ab1f894f9

Cause
Referer URL: Unknown

java.lang.RuntimeException: javax.mail.NoSuchProviderException: smtp
java.lang.RuntimeException: javax.mail.NoSuchProviderException: smtp
	at net.bull.javamelody.internal.model.Action.mailTest(Action.java:328) [jira-confluence-javamelody-1.72.0.jar:1.72.0]
	at net.bull.javamelody.internal.model.Action.execute(Action.java:193) [jira-confluence-javamelody-1.72.0.jar:1.72.0]
	at net.bull.javamelody.internal.web.MonitoringController.executeActionIfNeeded(MonitoringController.java:118) [jira-confluence-javamelody-1.72.0.jar:1.72.0]
	at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:149) [jira-confluence-javamelody-1.72.0.jar:1.72.0]
	at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:401) [jira-confluence-javamelody-1.72.0.jar:1.72.0]
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:205) [jira-confluence-javamelody-1.72.0.jar:1.72.0]
	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:88) [jira-confluence-javamelody-1.72.0.jar:1.72.0]
	at net.bull.javamelody.JiraMonitoringFilter.doFilter(JiraMonitoringFilter.java:134) [jira-confluence-javamelody-1.72.0.jar:1.72.0]
	at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:64) [atlassian-plugins-servlet-4.5.0.jar:?]
	at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:37) [atlassian-plugins-servlet-4.5.0.jar:?]
	at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:70) [atlassian-plugins-servlet-4.5.0.jar:?]
	at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:58) [atlassian-plugins-servlet-4.5.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.6]
	at com.atlassian.jira.web.filters.steps.ChainedFilterStepRunner.doFilter(ChainedFilterStepRunner.java:74) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.6]
	at com.atlassian.core.filters.cache.AbstractCachingFilter.doFilter(AbstractCachingFilter.java:31) [atlassian-core-5.0.8.jar:?]
	at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [atlassian-core-5.0.8.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.6]
	at com.atlassian.core.filters.encoding.AbstractEncodingFilter.doFilter(AbstractEncodingFilter.java:39) [atlassian-core-5.0.8.jar:?]
	at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [atlassian-core-5.0.8.jar:?]
	at com.atlassian.jira.web.filters.PathMatchingEncodingFilter.doFilter(PathMatchingEncodingFilter.java:41) [classes/:?]
	at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [atlassian-core-5.0.8.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.6]
	at com.atlassian.jira.web.filters.MultipartBoundaryCheckFilter.doFilter(MultipartBoundaryCheckFilter.java:36) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.6]
	at com.atlassian.jira.servermetrics.MetricsCollectorFilter.doFilter(MetricsCollectorFilter.java:25) [classes/:?]
	at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [atlassian-core-5.0.8.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.6]
	at com.atlassian.jira.web.filters.steps.ChainedFilterStepRunner.doFilter(ChainedFilterStepRunner.java:74) [classes/:?]
	at com.atlassian.jira.web.filters.JiraFirstFilter.doFilter(JiraFirstFilter.java:57) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.6]
	at com.atlassian.gzipfilter.GzipFilter.doFilterInternal(GzipFilter.java:115) [atlassian-gzipfilter-3.0.0.jar:?]
	at com.atlassian.gzipfilter.GzipFilter.doFilter(GzipFilter.java:92) [atlassian-gzipfilter-3.0.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.6]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.6]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [catalina.jar:8.5.6]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.6]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.5.6]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.6]
	at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:206) [catalina.jar:8.5.6]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) [catalina.jar:8.5.6]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [catalina.jar:8.5.6]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) [tomcat-coyote.jar:8.5.6]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.6]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) [tomcat-coyote.jar:8.5.6]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) [tomcat-coyote.jar:8.5.6]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.6]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: javax.mail.NoSuchProviderException: smtp
	at javax.mail.Session.getService(Session.java:794) [mail-1.4.1.jar:1.4.1]
	at javax.mail.Session.getTransport(Session.java:718) [mail-1.4.1.jar:1.4.1]
	at javax.mail.Session.getTransport(Session.java:661) [mail-1.4.1.jar:1.4.1]
	at javax.mail.Session.getTransport(Session.java:641) [mail-1.4.1.jar:1.4.1]
	at javax.mail.Session.getTransport(Session.java:696) [mail-1.4.1.jar:1.4.1]
	at javax.mail.Transport.send0(Transport.java:186) [mail-1.4.1.jar:1.4.1]
	at javax.mail.Transport.send(Transport.java:118) [mail-1.4.1.jar:1.4.1]
	at net.bull.javamelody.internal.common.Mailer.send(Mailer.java:184) [jira-confluence-javamelody-1.72.0.jar:1.72.0]
	at net.bull.javamelody.internal.web.MailReport.sendReportMail(MailReport.java:171) [jira-confluence-javamelody-1.72.0.jar:1.72.0]
	at net.bull.javamelody.internal.web.MailReport.sendReportMailForLocalServer(MailReport.java:141) [jira-confluence-javamelody-1.72.0.jar:1.72.0]
	at net.bull.javamelody.internal.model.Action.mailTest(Action.java:321) [jira-confluence-javamelody-1.72.0.jar:1.72.0]
	... 58 more

**Comment by evernat** [comment]
The mail feature for JIRA and Confluence is documented here:
https://github.com/javamelody/javamelody/wiki/AtlassianPlugin

What JIRA and Confluence versions are you using?
What steps have you done exactly to get into this issue?

**Comment by evernat** [comment]
Any news?
Note that in recent JIRA versions, the files to copy from the "JIRA/atlassian-jira/WEB-INF/lib/" directory to the "JIRA/lib/" directory are "javax.mail-1.5.6.jar", "javax.mail-api-1.5.6.jar" and "activation-1.1.1.jar".

**Comment by evernat** [comment]
No response from the reporter, so closing as invalid/incomplete.
