### ISSUE TITLE
Javamelody and Weblogic 12.1.3.0.0 startup issues

### ISSUE THREAD

**Issue by dg-grow-virgiliu-ratoi** [javamelody/javamelody#774]
Hi,

I have a Spring Boot (1.5.8) application which cannot be deployed on a Weblogic 12.1.3.0.0 server running on a JDK jdk1.8.0_172. There are some Hibernate errors at start-up and the application is not initialized at all. Please note that we do not use Hibernate at all, only Spring Jdbc Template.

I tried with two different Java melody versions and I get the following errors:

With 1.68.1 I receive:

> error weblogic.application.ModuleException: java.lang.ClassNotFoundException: org.hibernate.jdbc.BatchingBatcher
weblogic.application.ModuleException: java.lang.ClassNotFoundException: org.hibernate.jdbc.BatchingBatcher
        at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:114)
        at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
        at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:175)
        at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:170)
        at weblogic.application.utils.StateMachineDriver$ParallelChange.run(StateMachineDriver.java:80)
        Truncated. see log file for complete stacktrace
Caused By: java.lang.ClassNotFoundException: org.hibernate.jdbc.BatchingBatcher
        at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:387)
        at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:348)
        at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        Truncated. see log file for complete stacktrace

With Melody 1.74.0 I get:

> error weblogic.application.ModuleException: java.lang.ClassNotFoundException: com.thoughtworks.xstream.converters.collections.MapConverter
weblogic.application.ModuleException: java.lang.ClassNotFoundException: com.thoughtworks.xstream.converters.collections.MapConverter
        at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:114)
        at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
        at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:175)
        at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:170)
        at weblogic.application.utils.StateMachineDriver$ParallelChange.run(StateMachineDriver.java:80)
        Truncated. see log file for complete stacktrace
Caused By: java.lang.ClassNotFoundException: com.thoughtworks.xstream.converters.collections.MapConverter
        at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:387)
        at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:348)
        at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        Truncated. see log file for complete stacktrace

It seems to be similar to this issue: #639 . The application deploys fine on Tomcat 8.

Thank you.

**Comment by evernat** [comment]
As said in #639, you should remove META-INF/beans.xml from the javamelody jar file when using weblogic 12.1, because the CDI component is too old in weblogic 12.1.
Or you should upgrade weblogic to 12.2.x at least.
