### ISSUE TITLE
authorized-users error when activate the params, spring security and oauth2

### ISSUE THREAD

**Issue by ainulyaqin** [javamelody/javamelody#778]
Hi All, 

 I have facing some problem for configure javamelody-spring-boot-starter, 

this issue is come from 
`javamelody.init-parameters.authorized-users=admin:admin`
when i comment this param, the URL can access successfully..
but when I uncomment param the issue is come.

Im using spring boot 2.0.4 Release as parent 
and java melody 1.74.0 

is any miss configuration in my app ? 
thank you 

		``` <groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.4.RELEASE</version>```
```
	
		<dependency>
			<groupId>net.bull.javamelody</groupId>
			<artifactId>javamelody-spring-boot-starter</artifactId>
			<version>1.74.0</version>
		</dependency>
```

```
<2018-09-20 18:14:55,390>,[http-nio-8080-exec-14]>>[ERROR] [org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/].[dispatcherServlet]:183] Servlet.service() for servlet dispatcherServlet threw exception javax.servlet.ServletException: Circular view path [error]: would dispatch back to the current handler URL [/error] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)
	at org.springframework.web.servlet.view.InternalResourceView.prepareForRendering(InternalResourceView.java:209)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:147)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:314)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1325)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1069)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1008)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:716)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.forwardToErrorPage(ErrorPageFilter.java:197)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.handleException(ErrorPageFilter.java:180)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:145)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at id.com.tri.bonstri.filter.CorsConfig.logChainProcessing(CorsConfig.java:116)
	at id.com.tri.bonstri.filter.CorsConfig.doFilter(CorsConfig.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1156)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by evernat** [comment]
Any news?

**Comment by ainulyaqin** [comment]
[test.zip.zip](https://github.com/javamelody/javamelody/files/2514547/test.zip.zip)
Hi, 

i am tried to remove any particular the maven dependency was not used, then only basic maven to build app test.
and error still occurred. 

when run using `mvn spring-boot:run`, the screen showing normally. but build the war file and deploy to tomcat 8, error has come.
and also try to run using eclipse tomcat server run-on-server . still error.

thank you very much.

**Comment by evernat** [comment]
Ah! You are using Spring security with oauth and you are deploying in Tomcat. You may have said that before.
What is sure is that I do not reproduce the issue with your test project using spring-boot 2.0.5, javamelody spring-boot-starter 1.74.0 and Tomcat 9.
That's certainly because in Tomcat with servlet api 3.1+ in web.xml, the javamelody filter registers itself in the webapp and the filter bean defined the javamelody spring-boot-start disables itself (you can see order of filters and the disabled javamelody filter bean in the logs).
And so the javamelody filter is before the springSecurityFilterChain filter and oauth does not break the basic-auth you have configured for the /admin11/monitoring which you use.
(It does not register itself in spring-boot:run, because spring-boot:run does not implement all the servlet api spec.)

That said, if for some reason it does not happen like that for you, then in order that oauth does not break basic-auth of javamelody when using Tomcat, you should configure your app so that the springSecurityFilterChain filter is after the javamelody filter. But I don't know how to do that and for example filterRegistrationBean.setOrder(int) did not work for me in Spring-boot 2.0.5.
And I don't know exactly why according to you, oauth/springSecurityFilterChain breaks basic-auth of javamelody when using Tomcat but not when using mvn spring-boot:run
So if there is an issue, that's an issue with how to configure order of filters in Spring-boot and it's not an issue with javamelody.

Do you agree?

**Comment by evernat** [comment]
Note that it works for me in Tomcat, on your /admin11/monitoring url, without ever trying to login using oauth.

**Comment by evernat** [comment]
Any news?

**Comment by ainulyaqin** [comment]
Hi, 

Yes, it was miss configuration in my spring security config, 

thank you very much.

**Comment by bnd001** [comment]
Hi,
I have having same problem with my Spring Security and java melody.
Can you please share the solution what fixed this issue ?

Thanks in Advance
