### ISSUE TITLE
Logback fails to log when collecting estimated Memory Size

### ISSUE THREAD

**Issue by MatthiasSchmidtYatta** [javamelody/javamelody#781]
Hey together,

we are running java melody 1.73.1 on a tomcat server. it seems like the logging framework of our java melody instance crashes at some time, so the application throws an exception everytime it tries to log something.

according to the stacktrace, java melody is collecting some information from the java information list. during this process, there is some exception happening. because of the crashed logging framework, we cannot see what kind of exception this is.

see stacktrace:

java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
        at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:420)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:384)
        at ch.qos.logback.classic.Logger.warn(Logger.java:693)
        at net.bull.javamelody.LogbackLogger.warn(LogbackLogger.java:58)
        at net.bull.javamelody.LOG.warn(LOG.java:102)
        at net.bull.javamelody.Collector.collectWithoutErrors(Collector.java:308)
        at net.bull.javamelody.Collector.collectLocalContextWithoutErrors(Collector.java:294)
        at net.bull.javamelody.FilterContext$CollectTimerTask.run(FilterContext.java:56)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

obviously, the logback library is accessible, because a part of the logback code is executed successfully. the process is crashing when the logback library tries to access the ThrowableProxy. according to some research, this may happen when the logback process is shut down at some time, but the application is still running or restarted at some point.

is there any idea or experience how or when this situation could occur? 

thanks

**Comment by evernat** [comment]
It seems more an issue with Logback than with javamelody, so I suggest to create an issue at Logback: https://logback.qos.ch/bugreport.html
So closing this issue as invalid.

And in this issue you could ask if forcing the load of the class ch.qos.logback.classic.spi.ThrowableProxy before the app is shutting down would help.
