### ISSUE TITLE
Switch PDF dependency from iText to OpenPDF

### ISSUE THREAD

**Issue by andreasrosdal** [javamelody/javamelody#788]
Switch PDF dependency from iText to OpenPDF.   (Reopening #780.)

https://github.com/librepdf/openpdf

**Comment by mpe85** [comment]
Are there any plans to migrate to OpenPDF?
JavaMelody isn't compatible with the latest OpenPDF version 1.3.x:

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class com.lowagie.text.Element (java.lang.String is in module java.base of loader 'bootstrap'; com.lowagie.text.Element is in unnamed module of loader 'app')
	at com.lowagie.text.Phrase.add(Phrase.java:86)
	at net.bull.javamelody.internal.web.pdf.PdfJavaInformationsReport.writeDetails(PdfJavaInformationsReport.java:164)
```

The cause in this particular case is that the method `Phrase::add(Object)` was refactored into two overloaded methods `Phrase::add(String)` and `Phrase::add(Element)`.

**Comment by andreasrosdal** [comment]
@mpe85 There is an API change in the new OpenPDF. However, maybe upgrading isn't so much work, it could be just to change a few variable definitions from Object to the new and more logical object type.

**Comment by mpe85** [comment]
I just saw that javamelody also uses itext-rtf which is not present anymore in openpdf 1.3. So the upgrade is not trivial I guess.

**Comment by andreasrosdal** [comment]
> I just saw that javamelody also uses itext-rtf which is not present anymore in openpdf 1.3. So the upgrade is not trivial I guess.

I propose that Javamelody removes support for RTF, since it is an ancient format.

Then Javamelody can upgrade to OpenPDF, and get a maintained library to export PDF files with.

**Comment by mpe85** [comment]
@andreasrosdal I second that emotion
@evernat What's your opinion about this?

**Comment by evernat** [comment]
itext-rtf is used only in an almost obsolete part of javamelody (in the javamelody-swing module for the "Desktop" link in the monitoring report, to launch a Swing UI using JavaWebStart for those who have not forgotten about it). You can forgot about that javamelody-swing module.

**Comment by mpe85** [comment]
Well then, I started off a PR to replace the itext dependency with openpdf. All unit tests seem to be OK.  Feel free to complement/edit it.
https://github.com/javamelody/javamelody/pull/864

**Comment by evernat** [comment]
Given that:
- compatibility of javamelody with openpdf is broken with openpdf 1.3.11 (https://github.com/LibrePDF/OpenPDF/issues/274) and it does not seem easy to fix,
- if api compatibility between itext 2.1.7 and openpdf is restored soon, it may still break the same way in a later major version of openpdf,
- but many applications have itext 2.1.7 and not openpdf currently,

then I have changed the javamelody code (6532b4a), so that it is compatible with openpdf 1.3.11, while it still compiles and is fully compatible with itext 2.1.7. This change was done by never using `Phrase::add(Object)` with a String and only with an Element such as a Chunk.
This javamelody change is indenpendent of openpdf issue to restore or not api compatibility with itext 2.1.7 for all applications and previous versions of javamelody. This is independent of replacing or not compilation and usage in javamelody from itext 2.1.7 to openpdf (#864) and still keeping compatibility with itext 2.1.7 if api is kept the same in openpdf.

**Comment by andreasrosdal** [comment]
Any news on this?

**Comment by evernat** [comment]
@andreasrosdal 
No news more than said above. itext 2.1.7 is an optional (not transitive) dependency of javamelody-core. The plan in javamelody is to keep compatibility with itext 2.1.7 since applications often have currently an itext 2.1.7 dependency for whatever reason. javamelody is compatible with openpdf 1.3.11 and perhaps later. Issue 274 in openpdf is not fixed.

**Comment by lucas-prestes** [comment]
just leaving feedback, I guess this can be closed, I'm using OpenPDF in  my project and the leatest version works and exports just fine

**Comment by andreasrosdal** [comment]
OpenPDF is generally replacing iText 2.1.7 in other applications, and there are known security vulnerability in iText 2.1.7:
https://www.cvedetails.com/vulnerability-list/vendor_id-17242/Itextpdf.html

I would therefore strongly recommend upgrading to the latest OpenPDF version:
https://github.com/LibrePDF/OpenPDF/releases/tag/1.3.27

**Comment by andreasrosdal** [comment]
https://github.com/LibrePDF/OpenPDF/wiki/iText-is-insecure,-use-OpenPDF!

**Comment by evernat** [comment]
For reference, the small change https://github.com/LibrePDF/OpenPDF/commit/de7a7f855f7c1388558e7e5b26bc91c5562c5228 in OpenPDF breaks compatibility with iText 2.1.7 and with the PDF reports in javamelody, for OpenPDF 1.4 and all later versions. Note that OpenPDF 1.3.43 is still compatible with PDF reports in javamelody (compatibility restored by https://github.com/LibrePDF/OpenPDF/commit/4e9da4efc177d43dd19758edf05aa8e3ba859485). Note that iText 2.1.7 is an optional dependency of javamelody (a dependency not included by default).

There is still no plan at the moment.to switch dependency from iText to OpenPDF in javamelody. This could be reviewed again in the future, with some impacts on the users if they still have iText 2.1.7 or OpenPDF 1.3.
