### ISSUE TITLE
JDK11 - Unable to display graphs

### ISSUE THREAD

**Issue by kasinskim** [javamelody/javamelody#819]
## Problem description
When `javamelody` is run on the `JDK11` we're not able to see any charts, just links, see below.

<img width="1021" alt="javamelody_jdk11" src="https://user-images.githubusercontent.com/7738501/53686648-30e8e180-3d2a-11e9-8a03-d0104fc0b004.png">

JDK version info
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

Javamelody version info
```
Sat Mar 02 18:28:34 GMT 2019     DEBUG     JavaMelody version: 1.76.0
Sat Mar 02 18:28:34 GMT 2019     DEBUG     JavaMelody classes loaded from: file:/opt/app/lib/javamelody-core-1.76.0.jar
```

On the server side, we can find following error:
```
java.lang.NoClassDefFoundError: Could not initialize class sun.font.SunFontManager
      at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:265)
      at java.desktop/java.awt.Font.getStringBounds(Font.java:2607)
      at java.desktop/java.awt.Font.getStringBounds(Font.java:2517)
      at java.desktop/java.awt.Font.getStringBounds(Font.java:2551)
      at org.jrobin.graph.ImageWorker.getStringWidth(ImageWorker.java:166)
      at org.jrobin.graph.RrdGraph.getSmallFontCharWidth(RrdGraph.java:594)
      at org.jrobin.graph.RrdGraph.initializeLimits(RrdGraph.java:319)
      at org.jrobin.graph.RrdGraph.createGraph(RrdGraph.java:88)
      at org.jrobin.graph.RrdGraph.<init>(RrdGraph.java:59)
      at net.bull.javamelody.internal.model.JRobin.graph(JRobin.java:262)
      at net.bull.javamelody.internal.web.MonitoringController.doGraph(MonitoringController.java:394)
      at net.bull.javamelody.internal.web.MonitoringController.doReport(MonitoringController.java:192)
      at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:163)
      at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:408)
      at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206)
      at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
      at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
```

## Workaround
Adding following argument forces JVM to export necessary classes ( `sun.font.*`) coming from `java.desktop` module.

```--add-exports java.desktop/sun.font=ALL-UNNAMED```

**Comment by evernat** [comment]
Using openjdk 11.0.2 build 11.0.2+9 from adoptopenjdk, on linux centos 7, I do not reproduce the issue.
And I do not need to add exports.
Do you have an idea on your case causing this issue?
Do you have logs and stack-traces for sun.font.SunFontManager before this NoClassDefFoundError?

**Comment by kasinskim** [comment]
Well, I am able to reproduce this `NoClassDefFoundError` in an isolated environment (ubuntu 18.04 & JDK11 - see dockerfile below).

I digged deeper in the logs, as you suggested & eventually found this error:
```
java.lang.UnsatisfiedLinkError: /usr/lib/jvm/jdk-11.0.2/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method) ~[na:na]
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) ~[na:na]
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) ~[na:na]
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) ~[na:na]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638) ~[na:na]
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829) ~[na:na]
        at java.base/java.lang.System.loadLibrary(System.java:1867) ~[na:na]
        at java.desktop/sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:57) ~[na:na]
        at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
        at java.desktop/sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32) ~[na:na]
        at java.desktop/sun.font.SunFontManager$1.run(SunFontManager.java:270) ~[na:na]
        at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
        at java.desktop/sun.font.SunFontManager.<clinit>(SunFontManager.java:266) ~[na:na]
        at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:265) ~[na:na]
        at java.desktop/java.awt.Font.getStringBounds(Font.java:2607) ~[na:na]
        at java.desktop/java.awt.Font.getStringBounds(Font.java:2517) ~[na:na]
        at java.desktop/java.awt.Font.getStringBounds(Font.java:2551) ~[na:na]
        at org.jrobin.graph.ImageWorker.getStringWidth(ImageWorker.java:166) ~[jrobin-1.5.9.jar!/:1.5.9]
        at org.jrobin.graph.RrdGraph.getSmallFontCharWidth(RrdGraph.java:594) ~[jrobin-1.5.9.jar!/:1.5.9]
        at org.jrobin.graph.RrdGraph.initializeLimits(RrdGraph.java:319) ~[jrobin-1.5.9.jar!/:1.5.9]
        at org.jrobin.graph.RrdGraph.createGraph(RrdGraph.java:88) ~[jrobin-1.5.9.jar!/:1.5.9]
        at org.jrobin.graph.RrdGraph.<init>(RrdGraph.java:59) ~[jrobin-1.5.9.jar!/:1.5.9]
        at net.bull.javamelody.internal.model.JRobin.graph(JRobin.java:262) ~[javamelody-core-1.76.0.jar!/:1.76.0]
        at net.bull.javamelody.internal.web.MonitoringController.doGraph(MonitoringController.java:394) ~[javamelody-core-1.76.0.jar!/:1.76.0]
        at net.bull.javamelody.internal.web.MonitoringController.doReport(MonitoringController.java:192) ~[javamelody-core-1.76.0.jar!/:1.76.0]
        at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:163) ~[javamelody-core-1.76.0.jar!/:1.76.0]
        at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:408) ~[javamelody-core-1.76.0.jar!/:1.76.0]
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206) ~[javamelody-core-1.76.0.jar!/:1.76.0]

``` 

I've already found solution for this problem in openjdk official dockerfile:
https://github.com/caodianlong/openjdk/blob/master/11/jdk/oracle/Dockerfile#L10

So, in my case `apt-get install fontconfig` solved the problem permanently.



NOTES:
1. The Dockerfile definition I used at the very beginning:
```
FROM ubuntu:18.04
USER root
RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y --no-install-recommends wget  ca-certificates && \
	apt-get autoremove && \
	apt-get autoclean
ENV LANG C.UTF-8
ARG JDK_DIR="jdk-11.0.2"
ARG JDK_BINARY="openjdk-11.0.2_linux-x64_bin.tar.gz"
ARG JDK_BINARY_DOWNLOAD_LINK="https://download.java.net/java/GA/jdk11/9/GPL/${JDK_BINARY}"
ARG JDK_TMP_PATH="/tmp/${JDK_BINARY}"
RUN wget "${JDK_BINARY_DOWNLOAD_LINK}" -O "${JDK_TMP_PATH}" \
    && mkdir -p /usr/lib/jvm \
    && tar xfvz "${JDK_TMP_PATH}" --directory /usr/lib/jvm \
    && rm -f "${JDK_TMP_PATH}"
ENV JAVA_HOME="/usr/lib/jvm/${JDK_DIR}" \
    PATH="/usr/lib/jvm/${JDK_DIR}/bin:${PATH}"
```
2. After re-building the image I can say that initial workaround (extra exports) is not necessary

**Comment by evernat** [comment]
Ok, thank you for the information.
