### ISSUE TITLE
IllegalStateException: getOutputStream() has already been called for this response

### ISSUE THREAD

**Issue by tmysik** [javamelody/javamelody#845]
This could be perhaps a problem in our application (`MyFilter.groovy` below) but I am not really sure since I cannot find any problem with it. Could it be a bug in JavaMelody? If not, would you have any advice on where to look, please? Thank you.

```
java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at net.bull.javamelody.internal.web.FilterServletResponseWrapper.getWriter(FilterServletResponseWrapper.java:125)
	at net.bull.javamelody.internal.web.CounterServletResponseWrapper.getWriter(CounterServletResponseWrapper.java:30)
	at java.io.FilterWriter.flush(FilterWriter.java:100)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
	at com.company.MyFilter.doFilterInternal(MyFilter.groovy:xyz)
	at org.grails.jaxrs.web.JaxrsFilter.doFilterInternal(JaxrsFilter.java:46)
	at de.javakaffee.web.msm.RequestTrackingContextValve.invoke(RequestTrackingContextValve.java:99)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:125)
	at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:157)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tmysik** [comment]
The stacktrace is filtered so a bit useless (thank you Grails). Will reopen once I get the full one. Thanks.
