### ISSUE TITLE
NPE after SpringBoot hot restart

### ISSUE THREAD

**Issue by bluegaspode** [javamelody/javamelody#848]
I'm getting an NPE from JavaMelody, when Spring Boot is attempting to restart the App automatically (after a code change)

> Caused by: java.lang.NullPointerException: null
	at io.undertow.servlet.spec.ServletContextImpl.getInitParameter(ServletContextImpl.java:421)
	at net.bull.javamelody.internal.common.Parameters.getParameterValueByName(Parameters.java:466)
	at net.bull.javamelody.internal.common.Parameters.getParameterValue(Parameters.java:455)
	at net.bull.javamelody.Parameter.getValue(Parameter.java:409)
	at net.bull.javamelody.Parameter.getValueAsBoolean(Parameter.java:416)
	at net.bull.javamelody.internal.common.Parameters.isNoDatabase(Parameters.java:323)
	at net.bull.javamelody.SpringDataSourceBeanPostProcessor.postProcessAfterInitialization(SpringDataSourceBeanPostProcessor.java:95)

This is caused, because upon restart the Parameters class still has a reference to an old ServletContext (the one from the initial App Start), which is not valid anymore.

I simple fix resolves the issue: 
in 
`net.bull.javamelody.SessionListener.contextDestroyed(...)`
you should add
`Parameters.initialize((ServletContext)` null);
right after stopping the JDBCWrapper. 

Parameters does check the servletContext for null, so if called when there is no ServletContext works fine. Once the SessionListener gets a new ServletContext after the Application restart, Parameters is initialized again with a working ServletContext.

**Comment by evernat** [comment]
I do not reproduce the same issue.
What do you mean by hot restart? spring-boot-devtools?
What is your spring-boot version and javamelody version?
Can you give the full stack-trace of the NPE?
Can you give the source of a simple project to reproduce the issue?

**Comment by evernat** [comment]
sorry, I reproduce the issue using spring-boot-devtools.

**Comment by evernat** [comment]
fixed by 3fc04da and ready for the next release (1.80)

**Comment by bluegaspode** [comment]
Hi @evernat 
cool this was fast. I was just creating a sample project but seems this is not needed anymore.

Yes - spring-boot-devtools is involved, I used javamelody in a jhipster.tech based project.

Cheers
Stefan
