### ISSUE TITLE
External API query throwing exceptions

### ISSUE THREAD

**Issue by mrPsycho** [javamelody/javamelody#855]
hello, 
i'm trying to get JMX metrix over http, and trying this:
`http://jiraserver:81/jira/monitoring?jmxValue=Catalina:type=GlobalRequestProcessor,name=http-8080.bytesSent`

but in logs i see this:
```
java.lang.IllegalArgumentException: Catalina:type=GlobalRequestProcessor,name=http-8080.bytesSent
java.lang.IllegalArgumentException: Catalina:type=GlobalRequestProcessor,name=http-8080.bytesSent
	at net.bull.javamelody.internal.model.MBeans.getConvertedAttributes(MBeans.java:365) [jira-confluence-javamelody-1.74.0.jar:1.74.0]
	at net.bull.javamelody.internal.model.MBeans.getConvertedAttributes(MBeans.java:375) [jira-confluence-javamelody-1.74.0.jar:1.74.0]
	at net.bull.javamelody.internal.web.MonitoringController.doJmxValue(MonitoringController.java:434) [jira-confluence-javamelody-1.74.0.jar:1.74.0]
	at net.bull.javamelody.internal.web.MonitoringController.doReportCore(MonitoringController.java:227) [jira-confluence-javamelody-1.74.0.jar:1.74.0]
	at net.bull.javamelody.internal.web.MonitoringController.doReport(MonitoringController.java:209) [jira-confluence-javamelody-1.74.0.jar:1.74.0]
	at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:163) [jira-confluence-javamelody-1.74.0.jar:1.74.0]
	at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:408) [jira-confluence-javamelody-1.74.0.jar:1.74.0]
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206) [jira-confluence-javamelody-1.74.0.jar:1.74.0]
	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:88) [jira-confluence-javamelody-1.74.0.jar:1.74.0]
	at net.bull.javamelody.JiraMonitoringFilter.doFilter(JiraMonitoringFilter.java:134) [jira-confluence-javamelody-1.74.0.jar:1.74.0]
	at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:64) [atlassian-plugins-servlet-4.5.1.jar:?]
	at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:37) [atlassian-plugins-servlet-4.5.1.jar:?]
	at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:70) [atlassian-plugins-servlet-4.5.1.jar:?]
	at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:58) [atlassian-plugins-servlet-4.5.1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.35]
	at com.atlassian.jira.web.filters.steps.ChainedFilterStepRunner.doFilter(ChainedFilterStepRunner.java:74) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.35]
	at com.atlassian.core.filters.cache.AbstractCachingFilter.doFilter(AbstractCachingFilter.java:31) [atlassian-core-5.0.9.jar:?]
	at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [atlassian-core-5.0.9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.35]
	at com.atlassian.core.filters.encoding.AbstractEncodingFilter.doFilter(AbstractEncodingFilter.java:39) [atlassian-core-5.0.9.jar:?]
	at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [atlassian-core-5.0.9.jar:?]
	at com.atlassian.jira.web.filters.PathMatchingEncodingFilter.doFilter(PathMatchingEncodingFilter.java:41) [classes/:?]
	at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [atlassian-core-5.0.9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.35]
	at com.atlassian.jira.web.filters.MultipartBoundaryCheckFilter.doFilter(MultipartBoundaryCheckFilter.java:36) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.35]
	at com.atlassian.jira.servermetrics.MetricsCollectorFilter.doFilter(MetricsCollectorFilter.java:25) [classes/:?]
	at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [atlassian-core-5.0.9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.35]
	at com.atlassian.jira.web.filters.steps.ChainedFilterStepRunner.doFilter(ChainedFilterStepRunner.java:74) [classes/:?]
	at com.atlassian.jira.web.filters.JiraFirstFilter.doFilter(JiraFirstFilter.java:57) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.35]
	at com.atlassian.gzipfilter.GzipFilter.doFilterInternal(GzipFilter.java:121) [atlassian-gzipfilter-3.0.0.jar:?]
	at com.atlassian.gzipfilter.GzipFilter.doFilter(GzipFilter.java:92) [atlassian-gzipfilter-3.0.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.35]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.35]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.35]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [catalina.jar:8.5.35]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.35]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.35]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.35]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) [catalina.jar:8.5.35]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.35]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-coyote.jar:8.5.35]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.35]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-coyote.jar:8.5.35]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.35]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.35]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.35]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: javax.management.InstanceNotFoundException: Catalina:type=GlobalRequestProcessor,name=http-8080
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095) [?:1.8.0_181]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643) [?:1.8.0_181]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678) [?:1.8.0_181]
	at net.bull.javamelody.internal.model.MBeans.getAttribute(MBeans.java:81) [jira-confluence-javamelody-1.74.0.jar:1.74.0]
	at net.bull.javamelody.internal.model.MBeans.getConvertedAttributes(MBeans.java:349) [jira-confluence-javamelody-1.74.0.jar:1.74.0]
	... 60 more
```

I checked it in web ui - and it works:
![image](https://user-images.githubusercontent.com/883964/63430986-87f08900-c426-11e9-8e41-b8604494864f.png)

why it can be so? 

jira 7.13.4
JavaMelody 1.74.0

**Comment by mrPsycho** [comment]
is it possible that it is related to https://github.com/javamelody/javamelody/issues/843?

**Comment by evernat** [comment]
It's not related to #843.
If you click on the "-" link on the left of "byteSent", you will see that it works with http://jiraserver:81/jira/monitoring?jmxValue=Catalina:type=GlobalRequestProcessor,name=%22http-nio-8080%22.bytesSent
(with double-quotes around http-nio-8080).

**Comment by mrPsycho** [comment]
oh, cool.
didn't noticed, that tiny link) 

thanks!
