### ISSUE TITLE
NullPointerException in Quartz2Adapter

### ISSUE THREAD

**Issue by jpralle** [javamelody/javamelody#857]
Just after starting out tomcat, javamelody always raises a NullPointerException:

```
[INFO] [talledLocalContainer] 04.09.2019 14:47:42 WARN  javamelody cms [Log4J2Logger.warn:70] java.lang.NullPointerException
[INFO] [talledLocalContainer] java.lang.NullPointerException: null
[INFO] [talledLocalContainer] 	at net.bull.javamelody.internal.model.Quartz2Adapter.getAllJobsOfScheduler(Quartz2Adapter.java:149) ~[javamelody-core-1.78.0.jar:1.78.0]
[INFO] [talledLocalContainer] 	at net.bull.javamelody.internal.model.JobInformations.buildJobInformationsList(JobInformations.java:163) [javamelody-core-1.78.0.jar:1.78.0]
[INFO] [talledLocalContainer] 	at net.bull.javamelody.internal.model.JavaInformations.<init>(JavaInformations.java:203) [javamelody-core-1.78.0.jar:1.78.0]
[INFO] [talledLocalContainer] 	at net.bull.javamelody.internal.model.UpdateChecker.getAnonymousData(UpdateChecker.java:136) [javamelody-core-1.78.0.jar:1.78.0]
[INFO] [talledLocalContainer] 	at net.bull.javamelody.internal.model.UpdateChecker.checkForUpdate(UpdateChecker.java:109) [javamelody-core-1.78.0.jar:1.78.0]
[INFO] [talledLocalContainer] 	at net.bull.javamelody.internal.model.UpdateChecker$1.run(UpdateChecker.java:83) [javamelody-core-1.78.0.jar:1.78.0]
[INFO] [talledLocalContainer] 	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_212-3-redhat]
[INFO] [talledLocalContainer] 	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_212-3-redhat]
```

This exception is thrown after every single start of our tomcat without any user interaction. I guess that's all the information we have so far, but maybe I can provide more insight if you pose me some question about what's helpfull.

We use javamelody 1.78.0, tomcat 9.0.20 and OpenJDK 1.8.0_212.

**Comment by evernat** [comment]
In your webapp, for one scheduler from org.quartz.impl.SchedulerRepository.getInstance().lookupAll(), the method scheduler.getJobGroupNames() returns null. This is not supposed to happen in quartz scheduler. 

I suggest that you debug with a break point in org.quartz.impl.StdScheduler.getJobGroupNames() to see why it returns null in this case.

**Comment by jpralle** [comment]
Hi,

this is strange, because it has to happen. I debugged it.
- Quartz2Adapter.getAllJobsOfScheduler() calls scheduler.getJobGroupNames().iterator(), but scheduler.getJobGroupNames() returns null. This the NPE we're talking about.
- scheduler is an org.quartz.impl.StdScheduler. StdScheduler.getJobGroupNames() only returns sched.getJobGroupNames().
- sched is an org.quartz.core.QuartzScheduler. QuartzScheduler.getJobGroupNames() returns resources.getJobStore().getJobGroupNames().
- resources.getJobStore() returns a non-null org.hippoecm.repository.quartz.JCRJobStore. JCRJobStore.getJobGroupNames() consists of the single line "return null;".

So there's not much it can but return null. But I guess that is not your code, but coming from Hippo/Bloomreach (which is the CMS we're running the webapp) and I need to ask then what's wrong? And I'm assuming correctly the API spec of javamelody or quartz does say JobStore.getJobGroupNames() may not return null?
