### ISSUE TITLE
NullPointerException in JdbcWrapper if statement is `executeBatch`

### ISSUE THREAD

**Issue by lbar** [javamelody/javamelody#863]
When a `executeBatch` statement is invoked, there is a `NullPointerException` in `JdbcWrapper` that expects `requestName` representing the SQL query is non-null.
However `null` is a possible value.

```
java.lang.NullPointerException: null
	at org.jooq_3.12.1.MYSQL.debug(Unknown Source) ~[na:na]
	at net.bull.javamelody.JdbcWrapper$StatementInvocationHandler.invoke(JdbcWrapper.java:129) ~[javamelody-core-1.79.0.jar:1.79.0]
	at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:295) ~[javamelody-core-1.79.0.jar:1.79.0]
	at com.sun.proxy.$Proxy114.executeBatch(Unknown Source) ~[na:na]
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:112) ~[jooq-3.12.1.jar:na]
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:112) ~[jooq-3.12.1.jar:na]
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:104) ~[jooq-3.12.1.jar:na]
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:75) ~[jooq-3.12.1.jar:na]
```
JdbcWrapper:129: `&& !requestName.startsWith("/* BATCH */ ")) {`

**Comment by evernat** [comment]
Fixed by b2c399a and ready for the next release. It happened if the queries to execute in a JOOQ batch are empty.
Thanks for the issue.
