### ISSUE TITLE
StandardWrapperValve.invoke Servlet.service() for servlet [HTMLManager] in context with path [/manager] threw exception - NullPointerException

### ISSUE THREAD

**Issue by WIPService** [javamelody/javamelody#878]
Hi,

since latest release I get a problem if i Start/Stop/Deploy/Undeploy some Webapps via Catalina Manager. 
After this Error Tomcat is in a unaccessible state error 500 and must be restarted. Unless I Start/Stop/Undeploy/Deploy any Webapp it seems to work without issues. 

**Environment:**
- Tomcat 8.5.34.
- Linux SuSe 12.3 or Solaris 10.x

```
17-Dec-2019 11:09:00.403 SCHWERWIEGEND [http-nio-8080-exec-12] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [HTMLManager] in context with path [/manager] threw exception
 java.lang.NullPointerException
        at net.bull.javamelody.JspWrapper.createHttpRequestWrapper(JspWrapper.java:117)
        at net.bull.javamelody.MonitoringFilter.createRequestWrapper(MonitoringFilter.java:331)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:225)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by evernat** [comment]
I was not able to reproduce the issue yet.
1. After producing the error, can you display the /monitoring page and can you give here the Debugging logs available at the bottom of the /monitoring page?
2. You said Start/Stop/Deploy/Undeploy then Start/Stop/Undeploy/Deploy. I am not sure to understand that and also I am not sure if Start/Stop is for the webapp in the manager or for Tomcat. So can you give a use case starting from an empty and not started tomcat, with tomcat-users.xml already configured, to reproduce the issue?
3. Is it reproduced with any webapp?

**Comment by WIPService** [comment]
Hi,

i tested it again using current 1.81 - same error.
But I got a better description: As soon as I STOP a Application - /manager/html (whole Server) is not accessible anymore:

Stopping Application:
```
07-Jan-2020 11:02:16.967 INFORMATION [http-nio-8080-exec-3] org.apache.catalina.core.ApplicationContext.log HTMLManager: stop: Stopping web application '/MuBWeb'
07-Jan-2020 11:02:17.674 INFORMATION [http-nio-8080-exec-3] org.apache.catalina.core.ApplicationContext.log HTMLManager: list: Listing contexts for virtual host 'localhost'

==> localhost_access.log <==
2020-01-07 11:02:11.549 | 200 | 10.33.65.140 | - | manager | 3DCBA7ECB8DC283051AF98041184E511 | 23557 | 101 | "GET /manager/html/ HTTP/1.1"
2020-01-07 11:02:11.602 | 200 | 10.33.65.140 | - | manager | 3DCBA7ECB8DC283051AF98041184E511 | 20486 | 3 | "GET /manager/images/asf-logo.svg HTTP/1.1"
2020-01-07 11:02:17.683 | 200 | 10.33.65.140 | - | manager | 3DCBA7ECB8DC283051AF98041184E511 | 23036 | 719 | "POST /manager/html/stop?path=/MuBWeb&org.apache.catalina.filters.CSRF_NONCE=AC5B43EF86227B02C45E612C4F570ACA HTTP/1.1"
```




Next Click:
```
==> localhost.2020-01-07.log <==
07-Jan-2020 11:02:30.848 SCHWERWIEGEND [http-nio-8080-exec-10] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [] threw exception
 java.lang.NullPointerException
        at net.bull.javamelody.JspWrapper.createHttpRequestWrapper(JspWrapper.java:117)
        at net.bull.javamelody.MonitoringFilter.createRequestWrapper(MonitoringFilter.java:331)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:225)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)


==> localhost_access.log <==
2020-01-07 11:02:30.854 | 500 | 10.33.65.140 | - | - | - | 820 | 7 | "GET / HTTP/1.1"

==> localhost.2020-01-07.log <==
07-Jan-2020 11:02:39.475 SCHWERWIEGEND [http-nio-8080-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [default] in context with path [] threw exception
 java.lang.NullPointerException
        at net.bull.javamelody.JspWrapper.createHttpRequestWrapper(JspWrapper.java:117)
        at net.bull.javamelody.MonitoringFilter.createRequestWrapper(MonitoringFilter.java:331)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:225)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)


==> localhost_access.log <==
2020-01-07 11:02:39.170 | 401 | 10.33.65.140 | - | - | - | 602 | 632 | "GET /manager/html HTTP/1.1"
2020-01-07 11:02:39.476 | 500 | 10.33.65.140 | - | - | - | 820 | 2 | "GET /favicon.ico HTTP/1.1"
```

Your Questions:
Debugging Logs:
```
Only the last 50 messages are displayed
Tue Jan 07 11:05:22 CET 2020     DEBUG     first collect of data done
Tue Jan 07 11:05:22 CET 2020     DEBUG     JavaMelody filter init done in 25 ms
Tue Jan 07 11:05:25 CET 2020     DEBUG     JavaMelody listener init started
Tue Jan 07 11:05:25 CET 2020     DEBUG     datasources found in JNDI: []
Tue Jan 07 11:05:25 CET 2020     DEBUG     JavaMelody listener init done in 1 ms
Tue Jan 07 11:05:25 CET 2020     DEBUG     JavaMelody filter init started
Tue Jan 07 11:05:25 CET 2020     DEBUG     OS: SunOS unknown, sparcv9/64
Tue Jan 07 11:05:25 CET 2020     DEBUG     Java: Java(TM) SE Runtime Environment, 1.8.0_181-b12
Tue Jan 07 11:05:25 CET 2020     DEBUG     Server: Apache Tomcat/8.5.34
Tue Jan 07 11:05:25 CET 2020     DEBUG     Webapp context: /RuLWebCinnamon
Tue Jan 07 11:05:25 CET 2020     DEBUG     JavaMelody version: 1.81.0
Tue Jan 07 11:05:25 CET 2020     DEBUG     JavaMelody classes loaded from: file:/service/home/bginfo/Apache-Tomcat/lib/javamelody-core-1.81.0.jar
Tue Jan 07 11:05:25 CET 2020     DEBUG     Application type: Classic
Tue Jan 07 11:05:25 CET 2020     DEBUG     Application version: null
Tue Jan 07 11:05:25 CET 2020     DEBUG     Host: m10-ora-mig@127.0.0.1
Tue Jan 07 11:05:25 CET 2020     DEBUG     parameter defined: obsolete-graphs-days=90
Tue Jan 07 11:05:25 CET 2020     DEBUG     parameter defined: obsolete-stats-days=90
Tue Jan 07 11:05:25 CET 2020     DEBUG     log listeners initialized
Tue Jan 07 11:05:25 CET 2020     DEBUG     datasources found in JNDI: []
Tue Jan 07 11:05:25 CET 2020     DEBUG     counters initialized
Tue Jan 07 11:05:25 CET 2020     DEBUG     counters data read from files in /service/home/bginfo/Apache-Tomcat/temp/javamelody/RuLWebCinnamon_m10-ora-mig
Tue Jan 07 11:05:25 CET 2020     DEBUG     collect task scheduled every 60s
Tue Jan 07 11:05:25 CET 2020     DEBUG     first collect of data done
Tue Jan 07 11:05:25 CET 2020     DEBUG     JavaMelody filter init done in 25 ms
Tue Jan 07 11:05:26 CET 2020     DEBUG     JavaMelody listener init started
Tue Jan 07 11:05:26 CET 2020     DEBUG     datasources found in JNDI: []
Tue Jan 07 11:05:26 CET 2020     DEBUG     JavaMelody listener init done in 1 ms
Tue Jan 07 11:05:26 CET 2020     DEBUG     JavaMelody filter init started
Tue Jan 07 11:05:26 CET 2020     DEBUG     OS: SunOS unknown, sparcv9/64
Tue Jan 07 11:05:26 CET 2020     DEBUG     Java: Java(TM) SE Runtime Environment, 1.8.0_181-b12
Tue Jan 07 11:05:26 CET 2020     DEBUG     Server: Apache Tomcat/8.5.34
Tue Jan 07 11:05:26 CET 2020     DEBUG     Webapp context:
Tue Jan 07 11:05:26 CET 2020     DEBUG     JavaMelody version: 1.81.0
Tue Jan 07 11:05:26 CET 2020     DEBUG     JavaMelody classes loaded from: file:/service/home/bginfo/Apache-Tomcat/lib/javamelody-core-1.81.0.jar
Tue Jan 07 11:05:26 CET 2020     DEBUG     Application type: Classic
Tue Jan 07 11:05:26 CET 2020     DEBUG     Application version: null
Tue Jan 07 11:05:26 CET 2020     DEBUG     Host: m10-ora-mig@127.0.0.1
Tue Jan 07 11:05:26 CET 2020     DEBUG     parameter defined: obsolete-graphs-days=90
Tue Jan 07 11:05:26 CET 2020     DEBUG     parameter defined: obsolete-stats-days=90
Tue Jan 07 11:05:26 CET 2020     DEBUG     log listeners initialized
Tue Jan 07 11:05:26 CET 2020     DEBUG     datasources found in JNDI: []
Tue Jan 07 11:05:26 CET 2020     DEBUG     counters initialized
Tue Jan 07 11:05:26 CET 2020     DEBUG     counters data read from files in /service/home/bginfo/Apache-Tomcat/temp/javamelody/_m10-ora-mig
Tue Jan 07 11:05:26 CET 2020     DEBUG     collect task scheduled every 60s
Tue Jan 07 11:05:26 CET 2020     DEBUG     first collect of data done
Tue Jan 07 11:05:26 CET 2020     DEBUG     JavaMelody filter init done in 33 ms
Tue Jan 07 11:05:56 CET 2020     DEBUG     JavaMelody filter destroy done in 95 ms
Tue Jan 07 11:05:56 CET 2020     DEBUG     JavaMelody listener destroy done
Tue Jan 07 11:05:58 CET 2020     WARN     exception while collecting data: java.lang.IllegalStateException: Timer already cancelled.
Tue Jan 07 11:06:05 CET 2020     WARN     exception while collecting data: java.lang.IllegalStateException: Timer already cancelled.
```
WARN-Messages are know for DB-Connections


2./3. It is enough to STOP any Webapp which is deployed.
Even if you STOP "./" (which makes no sense)



Here our JVM arguments:
```
-Djava.util.logging.config.file=/service/home/bginfo/Apache-Tomcat/conf/logging.properties
-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
-Dcom.sun.management.jmxremote
-Dcom.sun.management.jmxremote.port=8089
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.authenticate=false
-Djava.rmi.server.hostname=m10-ora-mig
-Djavamelody.obsolete-graphs-days=90
-Djavamelody.obsolete-stats-days=90
-Djava.awt.headless=true
-Duser.language=de
-Duser.region=DE
-Djdk.tls.ephemeralDHKeySize=2048
-Djava.protocol.handler.pkgs=org.apache.catalina.webresources
-Dorg.apache.catalina.security.SecurityListener.UMASK=0027
-Xms64M
-Xmx2G
-XX:+UseParallelGC
-Djava.endorsed.dirs=/service/home/bginfo/Apache-Tomcat/endorsed
-Dcatalina.base=/service/home/bginfo/Apache-Tomcat
-Dcatalina.home=/service/home/bginfo/Apache-Tomcat
-Djava.io.tmpdir=/service/home/bginfo/Apache-Tomcat/temp
-- | --
```

**Comment by evernat** [comment]
Ok, I understand now.
It is caused by 3fc04da for #848 since v1.80.0.
And it happens when you put javamelody-core jar file is in tomcat/lib (instead of WEB-INF/lib) which installs javamelody in each webapp of Tomcat and when you stop or undeploy any webapp after that without redploying.
Note that javamelody-core is supposed to be in WEB-INF/lib and that putting javamelody-core in tomcat/lib is not officially supported.
I have added 4b0b270 which should fix this issue anyway. A new build is available at http://javamelody.org/downloads/javamelody-core-1.82.0-SNAPSHOT.jar
