### ISSUE TITLE
CircularReferenceException in External API with JSON for current requests

### ISSUE THREAD

**Issue by evernat** [javamelody/javamelody#884]
When there are JSP or SQL or Service currently executing for an http request, calling the following URL http://<host>:<port>/<context>/monitoring?part=currentRequests&format=json gives a truncated json response ending by `"parentContext":` and exception is printed in the output of the server:
```java
com.thoughtworks.xstream.core.TreeMarshaller$CircularReferenceException: Recursive reference to parent object
---- Debugging information ----
message             : Recursive reference to parent object
item-type           : net.bull.javamelody.internal.model.CounterRequestContext
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
-------------------------------
    at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:63)
    at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
    at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:70)
    at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
    at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:70)
    at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
    at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
    at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
    at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
    at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
    at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
    at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:70)
    at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
    at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
    at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
    at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
    at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
    at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:79)
    at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:70)
    at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
    at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
    at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
    at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
    at com.thoughtworks.xstream.XStream.marshal(XStream.java:1320)
    at com.thoughtworks.xstream.XStream.marshal(XStream.java:1309)
    at com.thoughtworks.xstream.XStream.toXML(XStream.java:1297)
    at net.bull.javamelody.internal.model.TransportFormat$XmlIO.writeToJson(TransportFormat.java:131)
    at net.bull.javamelody.internal.model.TransportFormat.writeSerializableTo(TransportFormat.java:313)
    at net.bull.javamelody.internal.web.SerializableController.doSerializable(SerializableController.java:108)
    at net.bull.javamelody.internal.web.MonitoringController.doCompressedSerializable(MonitoringController.java:346)
    at net.bull.javamelody.internal.web.MonitoringController.doCompressedSerializable(MonitoringController.java:326)
    at net.bull.javamelody.internal.web.MonitoringController.doReportCore(MonitoringController.java:239)
    at net.bull.javamelody.internal.web.MonitoringController.doReport(MonitoringController.java:209)
    at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:163)
    at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:408)
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```

The default JSON view in Firefox displays for example `SyntaxError: JSON.parse: unexpected end of data at line 1250 column 28 of the JSON data`.

It is expected that Firefox JSON view displays the full JSON content and that there is no exception in the server output.

**Comment by evernat** [comment]
It is caused by references between objects in the net.bull.javamelody.internal.model.CounterRequestContext class, which are not a typical tree of data to be printed as JSON and it is related to `xstream.setMode(XStream.NO_REFERENCES);` at https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/internal/model/TransportFormat.java#L142

`xstream.setMode(XStream.NO_REFERENCES);` is not used when using the `format=xml` instead of `format=json`, so there is no issue in this case.

Removing that line of code would fix the issue, but it will give references between data in the JSON result which may be hard to read. Another fix would be to break some references between objects, by using clones or nulls before printing to JSON.

At the moment, I would question the use of `NO_REFERENCES` for the json case in particular,
- because it is not used in the xml case,
- and because that line was written long ago, perhaps to work around an issue in the json case for a version of XStream which can be considered as no longer in use by anyone,
- and because that mode proves today to be a problem for the references in the current requests.

**Comment by evernat** [comment]
When there are JSP or SQL or Service currently executing for an http request, an instance of CounterRequestContext has another instance of CounterRequestContext in its currentChildContext attribute. That last instance of CounterRequestContext has the first instance of CounterRequestContext in its parentContext attribute. And http and other counters are referenced everywhere.
And so XStream in NO_REFERENCES mode throws CircularReferenceException.
Will fix this issue by removing `xstream.setMode(XStream.NO_REFERENCES);` which is there for no good reason as said above.
