### ISSUE TITLE
GSON output is depended on XStream

### ISSUE THREAD

**Issue by alpha4021** [javamelody/javamelody#889]
Library version:
```
javamelody-1.81.0.jar
jrobin-1.5.9.jar
gson-2.3.1.jar
```

I am working on a project with GSON dependency only. When I invoked the api `/monitoring?part=usedMemory&format=gson` the following stacktrace is shown:
```
java.lang.ClassNotFoundException: com.thoughtworks.xstream.io.HierarchicalStreamWriter
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1275)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1104)
	at net.bull.javamelody.internal.model.TransportFormat.writeSerializableTo(TransportFormat.java:316)
	at net.bull.javamelody.internal.web.SerializableController.doSerializable(SerializableController.java:108)
	at net.bull.javamelody.internal.web.MonitoringController.doCompressedSerializable(MonitoringController.java:351)
	at net.bull.javamelody.internal.web.MonitoringController.doCompressedSerializable(MonitoringController.java:326)
	at net.bull.javamelody.internal.web.MonitoringController.doReportCore(MonitoringController.java:239)
	at net.bull.javamelody.internal.web.MonitoringController.doReport(MonitoringController.java:209)
	at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:163)
	at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:408)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206)
```

Quoting from `wiki/ExternalAPI#gson`:

> Since 1.81, as an alternative to JSON with the XStream dependency, the monitoring data is also available as JSON over http with the Google Gson dependency instead of XStream, if the Gson dependency is available in the webapp.

This stacktrace indicated the XStream dependency is required for GSON output, which is not the same as described in wiki.

**Comment by evernat** [comment]
Thanks for the issue.
It is fixed by 93c0450 and ready for the next release (1.82).
A snapshot build is available at:
http://javamelody.org/downloads/javamelody-core-1.82.0-SNAPSHOT.jar
