### ISSUE TITLE
Tomcat 9.0.30 Javamelody 1.81.0 setting org.apache.catalina.STRICT_SERVLET_COMPLIANCE=true generates many SAX Severe Errors on javamelody-prometheus.tld

### ISSUE THREAD

**Issue by pKrav75** [javamelody/javamelody#890]
Facing a client requirement I have to activate the STRICT_SERVLET_COMPLIANCE flag for a tomcat with javamelody core jar deployed.
In this case i've got many errors like this one :
```java
Feb 05, 2020 7:07:32 PM org.apache.tomcat.util.digester.Digester error
SEVERE: Parse error at line [35] column [10]
org.xml.sax.SAXParseException; systemId: jar:file:/C:/Applications/tomcat/tomcat-9-DIA-71/apache-tomcat/diapason/diapason/WEB-INF/lib/javamelody.jar!/META-INF/javamelody-prometheus.tld; lineNumber: 35; columnNumber: 10; cvc-complex-type.2.4.a: Invalid content was found starting with element 'type'. One of '{"http://java.sun.com/xml/ns/javaee":rtexprvalue, "http://java.sun.com/xml/ns/javaee":deferred-value, "http://java.sun.com/xml/ns/javaee":deferred-method, "http://java.sun.com/xml/ns/javaee":fragment}' is expected.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
```

At the end, tomcat is started and javamelody 'seems' to be functional
Any way / hints to remove this severe errors and explain this behavior ?
Many thx by advance

**Comment by evernat** [comment]
OK, the order of the xml tags in tld is important for Tomcat's strict servlet compliance.
Fixed by 70fae89 and ready for the next release (1.82).
A snapshot build is available at:
http://javamelody.org/downloads/javamelody-core-1.82.0-SNAPSHOT.jar

**Comment by pKrav75** [comment]
Thx a lot, will have a look asap

**Comment by pKrav75** [comment]
Tested ok on 1.82.
