### ISSUE TITLE
Prometheus metrics from collector server

### ISSUE THREAD

**Issue by Barbiero** [javamelody/javamelody#894]
Hi,

I'm looking into javamelody's collector server and I'd like to know if there's a way to obtain prometheus metrics from the collector server, similar to how we can query `http://host/monitoring?format=prometheus`. When I try to call `http://collector-host/javamelody?format=prometheus`, I get a 500 error `java.lang.IllegalStateException: WRITER`, (javamelody server 1.81).

The collector server is very useful when you use intermitent applications, and prometheus is a good time-series database to persist the centralized data from the collector server; if this isn't possible, is there an alternative I could use to expose the javamelody collector server data to grafana?

Thank you for the good work!

**Comment by evernat** [comment]
Hi,

Prometheus is supposed to work on the collector server like on the monitored webapp. And I do not reproduce the issue at the moment.
Do you have a stack-trace in the standard or server output of the collector server?
Do you run the collector server with the embedded server using `java -jar ...` or with another server? And if another server, which one?

By the way, if you have several applications in the collector server, you should add an `application` parameter to say for which application you want Prometheus data. For example, `http://collector-host/javamelody?format=prometheus&application=yourapp1`

**Comment by Barbiero** [comment]
my testing environment:

* JavaMelody collect server WAR 1.81.0

Run as: 
```java -server -jar -Djavamelody.storage-directory=/home/path/to/javamelody/storage javamelody-collector-server-1.81.0.war --httpPort=8090```

Two instances of Spring Boot v1.5.22 with javamelody 1.72.0(latest for spring boot 1.5), which are [registering](https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#7-automatic-registration-of-applications) themselves under the application name "backend"

URL for javamelody is being accessed as `http://localhost:8090/javamelody?format=prometheus&application=backend` 

Exception thrown:

```
fev 14, 2020 8:12:36 AM org.eclipse.jetty.util.log.JavaUtilLog warn
ADVERTÊNCIA: /javamelody
java.lang.IllegalStateException: WRITER
	at org.eclipse.jetty.server.Response.getOutputStream(Response.java:691)
	at net.bull.javamelody.internal.web.HtmlController.getWriter(HtmlController.java:131)
	at net.bull.javamelody.internal.web.MonitoringController.getWriter(MonitoringController.java:304)
	at net.bull.javamelody.internal.web.CollectorController.createWriterFromOutputStream(CollectorController.java:512)
	at net.bull.javamelody.internal.web.CollectorController.writeMessage(CollectorController.java:492)
	at net.bull.javamelody.internal.web.CollectorController.doMonitoring(CollectorController.java:178)
	at net.bull.javamelody.CollectorServlet.doGet(CollectorServlet.java:102)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

In order to register my spring-boot applications with the collector server, I use the following component, which waits until the server is up and running to try to register itself(apologies for pt-BR comments):

```java
@Component
@ConditionalOnProperty(JavaMelodyCollectServerRegistrar.PROPERTY_JAVAMELODY_SERVER_URL)
public class JavaMelodyCollectServerRegistrar implements ApplicationListener<ApplicationReadyEvent> {
	private static final Logger LOGGER = LoggerFactory.getLogger(JavaMelodyCollectServerRegistrar.class);

	static final String PROPERTY_JAVAMELODY_SERVER_URL = "accountfy.javamelody.url";
	private static final String PROPERTY_JAVAMELODY_APPLICATION_NAME = "accountfy.javamelody.applicationName";

	@Value("${" + PROPERTY_JAVAMELODY_SERVER_URL + "}")
	private String javaMelodyUrl;

	@Value("${" + PROPERTY_JAVAMELODY_APPLICATION_NAME + "}")
	private String javaMelodyAppName;

	@Value("${server.port}")
	private String serverPort;

	@Override
	public void onApplicationEvent(ApplicationReadyEvent event) {
		String selfUrl = "";
		try {
			// Para registrar a aplicação no javamelody, precisamos de um ip para
			// comunicação.
			// O que é problemático quando consideramos que no k8s, pods têm IPs
			// intermitentes e variáveis.
			// Por isso vamos perguntar direto para o Java qual o nosso IP.
			String hostAddr = InetAddress.getLocalHost().getHostAddress();
			selfUrl = MessageFormat.format("http://{0}:{1}", hostAddr, serverPort);

			URL collectServerUrl = new URL(javaMelodyUrl);
			URL applicationNodeUrl = new URL(selfUrl);

			LOGGER.info("Registrando servidor \"{}\" de monitoramento com JavaMelody, URL: {} ; URL local: {}",
					javaMelodyAppName, collectServerUrl.toExternalForm(), applicationNodeUrl.toExternalForm());

			net.bull.javamelody.MonitoringFilter.registerApplicationNodeInCollectServer(javaMelodyAppName,
					collectServerUrl, applicationNodeUrl);
		} catch (UnknownHostException e) {
			LOGGER.error("Erro registrando monitoramento: Host desconhecido", e);
		} catch (MalformedURLException ex) {
			LOGGER.error("Erro registrando monitoramento: URL(s) malformada(s). Servidor: {} ; App: {}", javaMelodyUrl,
					selfUrl);
		}
	}

	@PreDestroy
	public void onDestroy() {
		LOGGER.info("Desregistrando do servidor do javamelody");
		try {
			net.bull.javamelody.MonitoringFilter.unregisterApplicationNodeInCollectServer();
		} catch (IOException e) {
			LOGGER.error("Erro ao desregistrar a aplicação do javamelody", e);
		}
	}
}
```

(in this instance, javaMelodyUrl = "http://localhost:8090" and javaMelodyAppName = "backend")

Do note that I can access other information just fine. Also, this error occurs when the javamelody collector server is of the same version as the spring-boot counterparts (ie. 1.72.0). Using Chrome v80

Is it possible that the old versions from my servers are having trouble?

**Comment by Barbiero** [comment]
Update:

`format=prometheus` works fine if, and only if, I have only a single instance of my backend online. Do note that I've been testing with two instances at the same computer, with different ports each.

The behavior is consistent between using tomcat 9(via docker) & java, as well as jdk 8 and 11.

**Comment by evernat** [comment]
Ah, I see now that you register several nodes in a single application named "backend" in the collector server. And I forgot to say that Prometheus scraping is not supported in this case of several nodes in a single application in the collector server.
So I suggest to register each node, under different application names in the collector server, for example "backend1" and "backend2". And then you can scrape Prometheus data for "backend1" (http://localhost:8090/javamelody?format=prometheus&application=backend1) and "backend2" (http://localhost:8090/javamelody?format=prometheus&application=backend2)
Otherwise you may scrape Prometheus data directly from each node without using a collector server.

And I have now fixed the exception so that the message explaining that is correctly printed without `IllegalStateException: WRITER`.

Is it ok for you?

**Comment by Barbiero** [comment]
Thank you for your response

I will try to figure out a way to use this, however the use case of
combining multiple nodes of the same name would be awesome. That's because
in our system, we have backends coming online and shutting down
intermittently and there's no easy way to tell if an instance is the
"backend-a" or "backend-b". Of course this might not be possible or be
prohibitive; we have other angles to explore in the monitoring area.

Again, thank you for clarifying. Feel free to close or mark this as a
feature request for the above use case.

**Comment by evernat** [comment]
Enhancement registered in the issue above.
Closing this one.
