### ISSUE TITLE
WELD-ENV-000015: Unable to load annotation: javax.ejb.Asynchronous

### ISSUE THREAD

**Issue by evernat** [javamelody/javamelody#912]
In a [message in the user's group](https://groups.google.com/forum/#!topic/javamelody/nO65LeUJBmQ), a webapp fails to start, which is caused by `WELD-ENV-000015: Unable to load annotation: javax.ejb.Asynchronous`.

Environment: Tomcat 8, CDI WELD, JSF 2, javamelody 1.76.0 or 1.82.0, jdk 8 from Open J9.

Stack-trace:
```java
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/eServices-1.5]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:941)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:819)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/eServices-1.5]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	... 6 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: WELD-ENV-000015: Unable to load annotation: javax.ejb.Asynchronous
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.jboss.weld.environment.deployment.discovery.jandex.JandexClassFileInfo.containsAnnotation(JandexClassFileInfo.java:253)
	at org.jboss.weld.environment.deployment.discovery.jandex.JandexClassFileInfo.containsAnnotation(JandexClassFileInfo.java:81)
	at org.jboss.weld.bootstrap.FastProcessAnnotatedTypeResolver.containsRequiredAnnotation(FastProcessAnnotatedTypeResolver.java:228)
	at org.jboss.weld.bootstrap.FastProcessAnnotatedTypeResolver.resolveProcessAnnotatedTypeObservers(FastProcessAnnotatedTypeResolver.java:216)
	at org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadAnnotatedType(FastAnnotatedTypeLoader.java:78)
	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:97)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:65)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:56)
	... 4 more
Caused by: java.lang.IllegalStateException: WELD-ENV-000015: Unable to load annotation: javax.ejb.Asynchronous
	at org.jboss.weld.environment.deployment.discovery.jandex.JandexClassFileServices$AnnotationClassAnnotationLoader.load(JandexClassFileServices.java:64)
	at org.jboss.weld.environment.deployment.discovery.jandex.JandexClassFileServices$AnnotationClassAnnotationLoader.load(JandexClassFileServices.java:47)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 17 more
```

A workaround is to have the following dependency:
```xml
<dependency>
 <groupId>javax.ejb</groupId>
 <artifactId>javax.ejb-api</artifactId>
 <version>3.2.2</version>
</dependency>
```

In the messages of the user's group, the issue is said to be fixed by adding the following in META-INF/beans.xml of javamelody:
```xml
    <scan>
        <exclude name="net.bull.javamelody.MonitoringAsynchronousCdiInterceptor" />
    </scan>
```

**Comment by evernat** [comment]
It's fixed by a07e3b8 and ready for the next release (1.83)
