### ISSUE TITLE
JavaMelody ,java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed

### ISSUE THREAD

**Issue by soulpresidente** [javamelody/javamelody#914]
I add java melody to my Spring boot 2 project via gradle : compile group: 'net.bull.javamelody', name: 'javamelody-spring-boot-starter', version: '1.82.0'

When I start my application, it was stopped after few seconds with this stacktrace : 

2020-05-08 19:18:39.078 ERROR 18484 --- [           main] jdbc.sqlonly                             : null. DataSource.getConnection()
java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[HikariCP-3.2.0.jar!/:na]
        at net.sf.log4jdbc.sql.jdbcapi.DataSourceSpy.getConnection(DataSourceSpy.java:149) ~[log4jdbc-log4j2-jdbc4.1-1.16.jar!/:na]
        at net.bull.javamelody.internal.model.JavaInformations.buildDataBaseVersion(JavaInformations.java:422) [javamelody-core-1.80.0.jar!/:1.80.0]
        at net.bull.javamelody.internal.model.JavaInformations.<init>(JavaInformations.java:198) [javamelody-core-1.80.0.jar!/:1.80.0]
        at net.bull.javamelody.internal.web.HtmlController.writeHtmlToLastShutdownFile(HtmlController.java:365) [javamelody-core-1.80.0.jar!/:1.80.0]
        at net.bull.javamelody.internal.web.MonitoringController.writeHtmlToLastShutdownFile(MonitoringController.java:300) [javamelody-core-1.80.0.ja
r!/:1.80.0]
        at net.bull.javamelody.FilterContext.destroy(FilterContext.java:443) [javamelody-core-1.80.0.jar!/:1.80.0]
        at net.bull.javamelody.MonitoringFilter.destroy(MonitoringFilter.java:176) [javamelody-core-1.80.0.jar!/:1.80.0]
        at org.apache.catalina.core.ApplicationFilterConfig.release(ApplicationFilterConfig.java:301) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.StandardContext.filterStop(StandardContext.java:4543) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5345) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1398) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1387) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_171]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at java.util.concurrent.AbstractExecutorService.submit(Unknown Source) [na:1.8.0_171]
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:974) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1398) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1387) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_171]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at java.util.concurrent.AbstractExecutorService.submit(Unknown Source) [na:1.8.0_171]
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:974) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:475) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:995) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.startup.Tomcat.stop(Tomcat.java:408) [tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.stopTomcat(TomcatWebServer.java:250) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RE
LEASE]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.stop(TomcatWebServer.java:306) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.stopAndReleaseWebServer(ServletWebServerApplicationContext.
java:320) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onClose(ServletWebServerApplicationContext.java:173) [sprin
g-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1017) [spring-context-5.1.4.RELEASE.
jar!/:5.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961) [spring-context-5.1.4.RELEASE.jar
!/:5.1.4.RELEASE]
        at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:834) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at com.adias.mytowereasy.MyTowerEasyApplication.main(MyTowerEasyApplication.java:72) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_171]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [mtg-backend-1.6.0-SNAPSHOT-dev.war:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [mtg-backend-1.6.0-SNAPSHOT-dev.war:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [mtg-backend-1.6.0-SNAPSHOT-dev.war:na]
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58) [mtg-backend-1.6.0-SNAPSHOT-dev.war:na]

**Comment by evernat** [comment]
Can you give the source of a simple project to reproduce the issue?

**Comment by soulpresidente** [comment]
compile group: 'com.zaxxer', name: 'HikariCP', version: '3.2.0'
compile group: 'net.bull.javamelody', name: 'javamelody-spring-boot-starter', version: '1.82.0'
this is my build.gradle file

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=12
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.auto-commit=true

my application.properties file

**Comment by evernat** [comment]
I was not clear. Can you give the complete source in a zip file of a simple project and a scenario to reproduce the issue. Please.

**Comment by evernat** [comment]
any news?

**Comment by evernat** [comment]
no response from the reporter, so closing as invalid.
