### ISSUE TITLE
Tomcat 7 errors in logs after undeploy/deploy

### ISSUE THREAD

**Issue by Ezor** [javamelody/javamelody#915]
Hello,

I found the following logs in the catalina.out of our Tomcat 7 server. It seems to happen when we undeploy/deploy a new version of our WAR but we don't have this issue on each deploy, it's quite random. This log repeats every 10 seconds until we shutdown/restart Tomcat.
Any idea of what we are doing wrong ?

Melody Version : `1.79.0`

```
mai 11, 2020 12:00:02 AM org.apache.catalina.loader.WebappClassLoader loadClass
INFOS: Illegal access: this web application instance has been stopped already.  Could not load org.sqlite.JDBC.  The eventual follow
ing stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the i
llegal access, and has no functional impact.
java.lang.IllegalStateException
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1370)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1329)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at java.sql.DriverManager.isDriverAllowed(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at net.bull.javamelody.JdbcDriver.connect(JdbcDriver.java:110)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:112)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:118)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:428)
        at com.zaxxer.hikari.pool.HikariPool.access$300(HikariPool.java:70)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:612)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:598)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by evernat** [comment]
It seems that you are using Tomcat 7, HikariCP and `org.sqlite.JDBC` as jdbc driver.
I think that this is issue is not related to javamelody and that it would happen when undeploy/deploy (in development / QA I suppose) even without javamelody.
For example: https://github.com/brettwooldridge/HikariCP/issues/633

When the webapp is undeployed, the WebappClassLoader instance stops and throws an exception if it is still used to load classes.
To work around the issue you may:
- stop by yourself, when the webapp undeploys the thread(s) created by HikariCP.
- or use another connection pool and datasource which does not leave threads behind, instead of HikariCP (Tomcat uses DBCP by default). Is it worth using HikariCP in your case?
- or always load the needed classes when starting the webapp, for example by opening & closing a jdbc connection, in order to not have issues to load them when or after undeploy.
- or do nothing and live with this exception when undeploy/deploy, since this thread left behind from an already undeployed webapp is not supposed to be still running and calling methods anyway.

Is it ok for you?

**Comment by Ezor** [comment]
It’s ok for me, thanks for your help
