### ISSUE TITLE
JdbcWrapper can't rewrap a weblogic datasource in WLS 12.2.1.4.0

### ISSUE THREAD

**Issue by matmouche** [javamelody/javamelody#916]
It seems that the class **weblogic.jdbc.common.internal.RmiDataSource** implemented in the last version of WebLogic Server doesn't provide the field **jdbcCtx** anymore.

A NullPointerException is thrown by https://github.com/javamelody/javamelody/blob/0ec8f858b40a4fadf80d8cc67e0e07aa6eb0bb5f/javamelody-core/src/main/java/net/bull/javamelody/JdbcWrapper.java#L576

        java.lang.NullPointerException: null
        at net.bull.javamelody.JdbcWrapperHelper$1.run(JdbcWrapperHelper.java:539) ~[javamelody-core-1.82.0.jar:1.82.0]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_241]
        at net.bull.javamelody.JdbcWrapperHelper.setFieldAccessible(JdbcWrapperHelper.java:535) ~[javamelody-core-1.82.0.jar:1.82.0]
        at net.bull.javamelody.JdbcWrapperHelper.getAccessibleField(JdbcWrapperHelper.java:530) ~[javamelody-core-1.82.0.jar:1.82.0]
        at net.bull.javamelody.JdbcWrapperHelper.getFieldValue(JdbcWrapperHelper.java:507) ~[javamelody-core-1.82.0.jar:1.82.0]
        at net.bull.javamelody.JdbcWrapper.rewrapWebLogicDataSource(JdbcWrapper.java:577) ~[javamelody-core-1.82.0.jar:1.82.0]
        at net.bull.javamelody.JdbcWrapper.rewrapDataSource(JdbcWrapper.java:526) ~[javamelody-core-1.82.0.jar:1.82.0]
        at net.bull.javamelody.JdbcWrapper.rebindDataSources(JdbcWrapper.java:467) ~[javamelody-core-1.82.0.jar:1.82.0]
        at net.bull.javamelody.SessionListener.contextInitialized(SessionListener.java:318) [javamelody-core-1.82.0.jar:1.82.0]
        at weblogic.servlet.internal.EventsManager$FireContextListenerAction.run(EventsManager.java:719) [com.oracle.weblogic.servlet.jar:12.2.1.4]
   ...

**Comment by evernat** [comment]
Thanks for the issue.
It should be fixed by a43fde0.
A snapshot build is available with the fix at http://javamelody.org/downloads/javamelody-core-1.84.0-SNAPSHOT.jar
Can you confirm that the fix works?

**Comment by matmouche** [comment]
Yes, it does fix the issue.
Thank you !
Also, I noticed that you have introduced a new method to check if the field exist	https://github.com/javamelody/javamelody/blob/a43fde0d58d252f88e83f251b3b35286f3e0d453/javamelody-core/src/main/java/net/bull/javamelody/JdbcWrapperHelper.java#L515

I guess this would be used to prevent the NPE while modifying the accessibility of the field but it seems that the call to this method is missing.

**Comment by matmouche** [comment]
Hm, forget it, the hasField method is called in JdbcWrapper. Sorry...

**Comment by matmouche** [comment]
When do you plan to release the 1.84.0 ?

**Comment by evernat** [comment]
The release 1.83.0 was not long ago (May, 8). So the release 1.84.0 will probably be near mid-july or before end of July.
