### ISSUE TITLE
javamelody not working after migrate spring boot 2.1.x to 2.2.x

### ISSUE THREAD

**Issue by winweb** [javamelody/javamelody#918]
when call inquiry, some data have these error messages. I used spring boot 2.1.14, there didn’t have any errors.

**My dependency library had:**
- Spring Boot Data JPA
- Hibernate
- Hiraki CP

These error message.
WARN  QueryParameterSetter$QueryMetadata - Failed to unwrap actual class for Query proxy. 
java.lang.NullPointerException: null
	at org.hibernate.query.internal.AbstractProducedQuery.unwrap(AbstractProducedQuery.java:1343)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bull.javamelody.JpaWrapper$QueryHandler.invoke(JpaWrapper.java:170)
	at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:300)
	at com.sun.proxy.$Proxy231.unwrap(Unknown Source)
	at org.springframework.data.jpa.repository.query.QueryParameterSetter$QueryMetadata.unwrapClass

**Comment by evernat** [comment]
It seems that something is calling `query.unwrap(null)`.
Can you give a less truncated stack-trace of the exception to understand what is calling `query.unwrap(null)`?
And can you give the source of a simple project to reproduce the issue?

**Comment by evernat** [comment]
By the way, I do not reproduce the issue at the moment, using spring-boot 2.2.7 and 2.3.0.

**Comment by evernat** [comment]
any news?

**Comment by evernat** [comment]
no response from the reporter, so closing as invalid
