### ISSUE TITLE
use mybatisplus with error

### ISSUE THREAD

**Issue by saury91** [javamelody/javamelody#924]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'statement' in 'class net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler'
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy148.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:294)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:63)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:62)
	at com.sun.proxy.$Proxy198.update(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.update(ServiceImpl.java:217)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl$$FastClassBySpringCGLIB$$76535273.invoke(<generated>)

**Comment by evernat** [comment]
Can you give the source of a simple project to reproduce the issue?

**Comment by saury91** [comment]
> Can you give the source of a simple project to reproduce the issue?
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Greenwich.SR1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.1.3.RELEASE</version>
        </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>3.1.1</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus</artifactId>
                <version>3.1.1</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-core</artifactId>
                <version>3.1.1</version>
            </dependency>

use mybatisplus lambda expression like this:
-------------------------------------------------------------------
baseMapper.selectList(Wrappers.<AlarmLog>lambdaQuery()
                .eq(AlarmLog::getStatus, 1));
--------------------------------------------------------------------
then start web app and get errors below:

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'statement' in 'class net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler'
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy144.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:158)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:76)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:62)
	at com.sun.proxy.$Proxy147.selectList(Unknown Source)

**Comment by evernat** [comment]
I do not find in the dependencies the version of the class `org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)` in this stack-trace.

**Comment by saury91** [comment]
> I do not find in the dependencies the version of the class `org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)` in this stack-trace.

![image](https://user-images.githubusercontent.com/64177647/86005799-a90f0680-ba47-11ea-8923-d53f5e99dbc3.png)
![image](https://user-images.githubusercontent.com/64177647/86005968-e378a380-ba47-11ea-8337-d34d27409656.png)

**Comment by evernat** [comment]
Ok, found the source.
Given that this is a "ReflectionException" on a java proxy (created by javamelody) of a java.sql.Statement or java.sql.Connection, it may be a case of some code trying to get an implementation specific attribute from a java.sql.Statement or java.sql.Connection which is supposed to be not implementation specific. Note that the [unwrap](https://docs.oracle.com/javase/6/docs/api/java/sql/Wrapper.html#unwrap(java.lang.Class)) method is supposed to be used on java.sql.Statement or java.sql.Connection to get an implementation specific class in the java.sql api.
I do not have the time to create a test case and to fix the code in mybatis-plus. So closing as invalid.

**Comment by saury91** [comment]
> Ok, found the source.
> Given that this is a "ReflectionException" on a java proxy (created by javamelody) of a java.sql.Statement or java.sql.Connection, it may be a case of some code trying to get an implementation specific attribute from a java.sql.Statement or java.sql.Connection which is supposed to be not implementation specific. Note that the [unwrap](https://docs.oracle.com/javase/6/docs/api/java/sql/Wrapper.html#unwrap(java.lang.Class)) method is supposed to be used on java.sql.Statement or java.sql.Connection to get an implementation specific class in the java.sql api.
> I do not have the time to create a test case and to fix the code in mybatis-plus. So closing as invalid.

I'm sorry to hear that my case is unsupport and really appreciate your quicly reply.
